### ISSUE TITLE
Movie special features do not list under moive

### ISSUE THREAD

**Issue by ryanlbates01** [jellyfin/Swiftfin#1017]
**Describe the feature you'd like**
When accessing via the web or the old Jellyfin iOS app I can see a movie's additional content/special features but when going to the same movie in Swiftfin they're not listed/the section is not shown

**Additional context**
not sure if this is a bug or a feature that has not been implemented yet.

**Comment by LePips** [comment]
Was implemented back in #593.

**Comment by ryanlbates01** [comment]
Can you provide steps to enable this feature as it does not show on my Apple TV

**Comment by Simonh2o** [comment]
> Can you provide steps to enable this feature as it does not show on my Apple TV

same here on tvos 18
