### ISSUE TITLE
Ability to hide "Recently Added" section at home screen

### ISSUE THREAD

**Issue by upstroke-version** [jellyfin/Swiftfin#1019]
**Describe the feature you'd like**
Currently, user can't hide "Recently Added" section of home screen. Even if this section is disabled on user's home settings via web version of jellyfin client, "Recently Added" section is still visible on Swiftfin.
I would love to hide this section because on horizontal screens like iPad, vertical space is valuable, and since each sections of categories on home screen already shows most recent contents, I don't really need "Recently Added" section.

**Additional context**

**Comment by LePips** [comment]
This is no longer an issue in the latest `main`.

**Comment by LePips** [comment]
Oops, I seem to have misunderstood the initial request.

**Comment by darrekk** [comment]
I'm new to the codebase but I think I can add a toggle to allow the user to show/hide the recently added section.  
Do we have access to the user settings from web? It would be nice to be able to keep these in sync.

**Comment by darrekk** [comment]
Added a PR here: https://github.com/jellyfin/Swiftfin/pull/1087
