### ISSUE TITLE
Extra’s do not show under movies or tv shows

### ISSUE THREAD

**Issue by ryanlbates01** [jellyfin/Swiftfin#1027]
### Describe the bug

As title says, extras/special features  do not show under movies of tv shows.

this doesn’t work on iOS devices or tvOS devices

tested with iPhone 14 and Apple TV 4th Gen HD

photos added for comparison between Swiftfin and the old jellyfin iOS app

![IMG_2086](https://github.com/jellyfin/Swiftfin/assets/28532253/13659a21-57a9-481f-808c-66cb707c2ff8)
![IMG_2087](https://github.com/jellyfin/Swiftfin/assets/28532253/dc0137f2-c0d6-4b69-8d4f-d7c2b0deeaeb)

### Application version

1.0.1

### Where did you install the app from?

App Store

### Device information

iPhone pro 14, tvOS

### OS version

iOS 17.4.1, tvOS 17.4

### Jellyfin server version

10.8.13

**Comment by LePips** [comment]
This has been implemented and will be released soon.

**Comment by ryanlbates01** [comment]
We can we expect the next stable release?
