### ISSUE TITLE
Why the app not update anymore in appstore?

### ISSUE THREAD

**Issue by wjfu99** [jellyfin/Swiftfin#1028]
I'm a IOS user who is an freshman to jellyfin. I'm very curious that why the swiftin and jellyfin mobile are both had their last update in March 2022, but the repos seem still under active development with commits. So, why not release the latest version built on the current repo? Because it's hard to believe the apps released two years ago can run well without massive issues.

**Comment by LePips** [comment]
You asked at the right time when we are trying to get another iOS release out. See the matrix/Discord channel for more details.
