### ISSUE TITLE
'Latest' sections display recently added items

### ISSUE THREAD

**Issue by ryanh2o3** [jellyfin/Swiftfin#1039]
### Describe the bug

On the IOS app home page, the 'Latest Films' and 'Latest Tv shows' sections display the recently added items of their respective libraries. 

### Application version

current main

### Where did you install the app from?

None

### Device information

iPhone 13

### OS version

iOS 17.4.1

### Jellyfin server version

10.8.0.2

**Comment by ryanh2o3** [comment]
@LePips I think 'Paths.getLatestMedia' in LatestInLibraryViewModel.swift is returning the most recently added media and not the latest. I was able to fix it by retrieving items like in RecentlyAddedViewModel and sorting by premiereDate instead. I can PR if this is an acceptable way to solve this.

**Comment by ryanh2o3** [comment]
I made a draft PR for it #1040

**Comment by ryanh2o3** [comment]
I just noticed that the terminology used in jellyfin web for the recently added films or tv shows is 'Latest'. Not sure I agree with that usage but maybe the titles for what I've done should be recently released instead?

**Comment by LePips** [comment]
Please see closing comment in PR.
