### ISSUE TITLE
Add Jumoog's intro skip / credit skip feature

### ISSUE THREAD

**Issue by barrio5** [jellyfin/Swiftfin#1042]
Hi, I would love to see [Jumoog's](https://github.com/jumoog/intro-skipper) intro and credit skip implemented. Is there any chance you could add this feature? I love this feature so much and would very much like to see this implemented. Thank you very much for your hard work :)

**Comment by LePips** [comment]
Official clients will not be implementing plugins. Please see all other closed issues about skip intro.
