### ISSUE TITLE
tvOS movies don’t load 

### ISSUE THREAD

**Issue by MillerApps** [jellyfin/Swiftfin#1054]
### Describe the bug

1. Load the app
2. Go to movies 
3. Only a few movies load. 
4. Expected to load all movie. 

### Application version

1.0.0(70)

### Where did you install the app from?

None

### Device information

A1842

### OS version

tvOS 17.4

### Jellyfin server version

10.9.1

**Comment by LePips** [comment]
Can we get more than just "won't load" with a screenshot?

**Comment by MillerApps** [comment]
It loads only 50 out 490 movies. 
![Screenshot 2024-05-15 at 6 14 54 PM](https://github.com/jellyfin/Swiftfin/assets/3836934/698a38f4-a039-45b3-8629-5bedf5cebc39)
