### ISSUE TITLE
Thumb Artwork used instead of Backdrop on Continue Watching

### ISSUE THREAD

**Issue by RebornCoding** [jellyfin/Swiftfin#1059]
### Describe the bug

1. Go to Shows
2. Start Episode
3. Go back and reload home
4. Hover towards watched show. Backdrop art is no longer used (But is correctly shown when entering into the show details)

### Application version

1.0.0(58)

### Where did you install the app from?

App Store

### Device information

Apple TV 4K A2843

### OS version

tvOS 17.4

### Jellyfin server version

10.9.1

**Comment by LePips** [comment]
This has since been fixed and is in `main`, but yet to be released.
