### ISSUE TITLE
Folders with specific caracters

### ISSUE THREAD

**Issue by Estarna** [jellyfin/SwiftFin#106]
When folder name begins with @before names, Swiftfin cannot access the files & subfolders under it.

examples:

"/Movies" is seen and can play
"/@Somesmovies" is not seen & files under it cannot be accessed.

**Comment by PangMo5** [comment]
Does it work normally in Jellyfin-Web?
And what does `@` prefix mean in the folder?

**Comment by Estarna** [comment]
It does work in the web, Jellyfin Media Player (Windows) and the android version.

I added "@"a long time ago this prefix to have the multimedia folders that I use most on top. I could have used "_" or another symbol. I mentionned it as an issue, since the server is handling it well. Also never have any issue with Kodi, Plex & Emby.

**Comment by acvigue** [comment]
what is the library storing.

**Comment by Estarna** [comment]
Folder setup:

/Multimedia

  /Books

  /Games

  /Music
    /Albums
    /Soundtrack
    /Songs

  /Pictures

  /Video
    /Movies
      /@Recent
      /@Unseen
      /Scene
      /BlurayRips
      /Remuxes
      /Etc

    /Series

**Comment by PangMo5** [comment]
I don't think it's a prefix issue.
I think it's a `recursive` value issue that parameter for items API.

---

acvigue: 

Does actually need the `shoulderBeRecursive` logic for `requestItmes` in `LibraryViewModel`?

I think since `includeItemType` is set, there will be no problem sending `recursive` that set true.
And this issue will be solved.

**Comment by PangMo5** [comment]
@Estarna 
Can you check if it work normally on the Search screen that entered from Item List screen?

**Comment by acvigue** [comment]
yes. otherwise favorites won't work.

**Comment by Estarna** [comment]
When going in "All Media" and then "search", all movies seem to be there.
when selecting a movie located in a subfolder, it shows, but when clicking on play, crashes and apps closes. 
Also, movies on subfolders appear in the "Latest Movies" section on Home screen. They just don't appear in the "All Media" section.

**Comment by acvigue** [comment]
web uses recursive as well.

**Comment by Estarna** [comment]
In fact, none of the movies located in subfolders appear  in the "All Media" section.

**Comment by PangMo5** [comment]
> web uses recursive as well.

Yeah, I mean, is it okay if we always send the "recursive" that set "true"?

**Comment by Estarna** [comment]
Confirm that is a recursive issue, did not see it first, sorry for that.
Cannot play any files in a sub level.

**Comment by acvigue** [comment]
> > web uses recursive as well.
> 
> Yeah, I mean, is it okay if we always send the `recursive` that set `true`?

No, sometimes we can't send recursive or it will break the links when clicking on a Cast member/genre/studio etc from an item page.

**Comment by acvigue** [comment]
> Confirm that is a recursive issue, did not see it first, sorry for that.
> Cannot play any files in a sub level.

Swiftfin doesn't support subfolders.

**Comment by acvigue** [comment]
is this still an issue @Estarna?

**Comment by Estarna** [comment]
> Swiftfin doesn't support subfolders.

I'm kind of surprised it doesn't. I may be wrong. The server, web, windows player and android version and some other forks that I'm using are managing subfolders without problem. I don't know if it is planned on an future roadmap.

**Comment by acvigue** [comment]
subfilders aren't recommended therefore not supported

**Comment by Estarna** [comment]
OK then. I appreciate the follow-up.
