### ISSUE TITLE
tvOS // Silent failure when attempting connection to server

### ISSUE THREAD

**Issue by kencieszykowski** [jellyfin/Swiftfin#1062]
### Describe the bug

I have a Jellyfin server running with Cloudflare DNS in front of it hitting a Caddy reverse proxy.  The following work as expected:
- iOS
- Web Browser
- Android
- Infuze on tvOS

The problem is that the Jellyfin application does not want to connect, nor does it display any sort of error that it's hitting.  I've looked through Caddy metrics and verified that there aren't any attempts for the connection hitting the server, and I'm using all standard ports.  Behavior is consistent whether I try to use `http` or `https` within the URI with my FQDN (all of the above platforms work with the `https` protocol).

I would have thought it was my configuration issue, but since all of the other platforms have had successful tests/streams, I have limited it to the tvOS client.  Can also confirm that CloudFlare security settings are not flagging any connection, nor do they see the connection attempts from the Jellyfin application (Infuse show up and have an allow rule).

Steps:
1. Open Application
2. Enter FQDN for Jellyfin server
3. Click 'Connect'
4. Button briefly greys out, and pops back to standard color 

### Application version

1.0.1

### Where did you install the app from?

App Store

### Device information

AppleTV 4k

### OS version

tvOS 17.5

### Jellyfin server version

Don't recall right now, but latest that uses Big Sur.  10.8.13 possibly

**Comment by LePips** [comment]
This no longer happens on `main` after #1045, but the views are unfinished and yet to be released.
