### ISSUE TITLE
Crash when using jellyfin 10.9.2 for new shows / movies

### ISSUE THREAD

**Issue by wyattoday** [jellyfin/Swiftfin#1063]
### Describe the bug

Add new shows / movies to server running Jellyfin 10.9.2 and swiftin crashes on iPhone or tvOS when trying to click through to the show / movie inside swiftin.

### Application version

1.0.1

### Where did you install the app from?

App Store

### Device information

Apple TV 4k

### OS version

tvOS is 17.5

### Jellyfin server version

10.9.2

**Comment by LePips** [comment]
I am unable to repro on `main` or with what's shipping for iOS 1.1 soon.

**Comment by wyattoday** [comment]
You know roughly when the next version will ship? (I know that hard to answer.)
