### ISSUE TITLE
Can't connect to wan address.

### ISSUE THREAD

**Issue by fusk-l** [jellyfin/Swiftfin#1069]
### Describe the bug

I'm trying to connect to a x.duckdns.org address on port 8896. This does not work. I do not if the port is the problem and it does not know how to handle "x.duckdns.org:8896"

Connection works fine from other devices, but not swiftfin.

### Application version

Can't find, but was installed 10 min ago.

### Where did you install the app from?

App Store

### Device information

A1625

### OS version

tvos 17

### Jellyfin server version

10.9.2

**Comment by LePips** [comment]
Please make sure to use the correct scheme: `http/https`. This is no longer an issue on `main`, but yet to be released for tvOS.
