### ISSUE TITLE
IOS's "Spatial Audio" feature doesn't work with Swiftfin

### ISSUE THREAD

**Issue by michaelharmonart** [jellyfin/SwiftFin#107]
I know the standard jellyfin ios app can playback surround sound videos with spatial audio as long as it's transcoded to aac and the app is set to use the native player. I know Swiftfin is based on mpv, so I don't know if it's possible to support the spatial audio feature, but I think it would make a great addition.

**Comment by acvigue** [comment]
we use libvlc. libvlc doesn't have support for spatial audio

**Comment by michaelharmonart** [comment]
Ah apologies, I guess I misremembered some comment about possibly switching to libmpv as allready having happened which isn't the case. I'll close the issue since clearly this is a libvlc problem.

**Comment by michaelharmonart** [comment]
Although I suppose I should ask. If I should be pounding on someone's door to support this, where would I do that? Would I put an issue up for libvlc, vlc itself, VLCkit? Is there plans from vlc to support this already?

**Comment by acvigue** [comment]
I think the door to pound on would be VLCKit :p

**Comment by michaelharmonart** [comment]
https://code.videolan.org/videolan/VLCKit/-/issues/514
Just if you want to stay updated

**Comment by sbucdaivs** [comment]
It looks like spatial audio support was added to libvlc. Would it be possible to reopen the issue? https://code.videolan.org/videolan/VLCKit/-/merge_requests/105

**Comment by LePips** [comment]
No, as we would still have to wait for VLCKit v4 to be released with all of the libvlc improvements in the recent years.
