### ISSUE TITLE
Since updated, live tv streams no longer load. 

### ISSUE THREAD

**Issue by extraslute** [jellyfin/Swiftfin#1070]
### Describe the bug

Live tv > pick any channel > get spinning wheel. 
Launch mobile app, get server error 
Launch web app, get server error 

the logs just say “error opening tuner. Zero bytes copied from stream SharedHttpStream and then a bunch of Microsoft.aspnetcore stuff. 

I’m able to directly view any of my streams in VLC just fine with the playlist m3u I’m handing to Jellyfin. 

### Application version

1.0.1(70)

### Where did you install the app from?

App Store

### Device information

All devices. ATV 4K, iPhone 15 pro max, MacBook Pro, web browser, mobile app, doesn’t matter 

### OS version

iOS 17.5, TVOS 17.4

### Jellyfin server version

10.9.2

**Comment by LePips** [comment]
This is a server issue
