### ISSUE TITLE
Update the App Store Version or make a new TestFlight-Build

### ISSUE THREAD

**Issue by mattipunkt** [jellyfin/Swiftfin#1078]
I really want to ditch Plex for Jellyfin, however, I do not want to pay for Infuse and the Version of SwiftFin currently available on the App Store is pretty much unusable. Therefore using Jellyfin as an Apple TV User seems to be a very bad experience. 
Could you please update the App Store version or (at least) give some information about the current state of art? (e.g. if you say everything is ready for testing in 1 month, I will surely wait)

Thanks in advance :)

**Comment by LePips** [comment]
We are currently in the process of providing updates. Please join the iOS development Matrix or Discord channels for updates.

**Comment by mattipunkt** [comment]
Where are links for those groups?

**Comment by LePips** [comment]
https://jellyfin.org/contact
