### ISSUE TITLE
swiftfin and blind user

### ISSUE THREAD

**Issue by axehell17** [jellyfin/Swiftfin#1092]
hello, I'm blind user of jellyfin. Sadely, swiftfin is not compatible with 'voiceover' on tvOs (I don't know for iOS, I haven't IPhone.
Option 'show title under picture' doesn't change the problem.
The same problem is present on androidTV with 'talkback', but  I can use the appli when I'm sorting my contents by letter.
Could you fix it?
Best regard

**Comment by axehell17** [comment]
humm, I'm not alone...Sorry for double-post but there is not answer for:
https://github.com/jellyfin/Swiftfin/issues/963
Thank for your future interest about it.
Best regard

**Comment by LePips** [comment]
Hello and thank you for using Swiftfin!

I apologize that the project is not that accessible, however accessibility is always an ongoing effort. You have found the previous issue about accessibility, so I will go ahead and close this.
