### ISSUE TITLE
Selected audio track “None” by default

### ISSUE THREAD

**Issue by oxixes** [jellyfin/Swiftfin#1095]
### Describe the bug

In the video player, by default the audio track “None” is selected (despite the audio playing). It should not make sense to have no audio track selected, so that should not be an option (it should in subtitle tracks).

Here is a picture of the problem:
![IMG_3076](https://github.com/jellyfin/Swiftfin/assets/38050447/7ef1e693-bb33-4153-a0a0-cc86a5e6448d)

### Application version

1.0.1

### Where did you install the app from?

TestFlight

### Device information

iPhone 12 Pro

### OS version

iOS 17.5.1

### Jellyfin server version

10.9.3

**Comment by holow29** [comment]
https://github.com/jellyfin/Swiftfin/issues/926

**Comment by oxixes** [comment]
Whoops, didn't see that. Thanks!
