### ISSUE TITLE
Consider Updating VLCKit Version (3.X.X -> 4.0.0)

### ISSUE THREAD

**Issue by JPKribs** [jellyfin/Swiftfin#1098]
**Describe the feature you'd like**
Swiftfin currently targets 3.4 for MobileVLCKit and 3.3 for TVVLCKit. I understand that MPV is also under consideration and it looks as though VLCKit hasn't resolved some of the more noticeable issues in these later versions (Delay on resume, HTTP 1.3 Support, etc). For these reasons, it may not be worth potentially introducing new variables and handling potential api changes.

**Additional context**

https://code.videolan.org/videolan/VLCKit/-/blob/master/NEWS

Version 4.0.0:
--------------
- Remove support for ARMv7s, use the regular ARMv7 slice instead
- Removed all API deprecated in version 3
- Rename buildMobileVLCKit to compileAndBuildVLCKit
- using libvlc HEAD leading to v4
- unified Xcode project for all 3 flavors of the framework
- new metadata API
- new track management and selection API
- support for two subtitles tracks at the same time
- new clock, time and position management with much greater precision
    - this allows subsecond seek intervals
- removed support to compile VLCKit as a static framework
- disabled bitcode support by default for tvOS
- improved nullability annotations
- improved debug logging API
- rewritten event management
- fully exposed libvlc C API
- Use NSDateComponents API for VLCTime.verboseStringValue

Version 3.5.0:
--------------
- Updated to libvlc 3.0.18-rc1
- Update libdsm to 0.4.0 plus upstream PR 160
- Disable IPv6 mode for UPnP multimedia server handling
- Fix UPnP IPv4 lookup regression on iOS devices
- Fix Bonjour lookup of SMB hostnames
- Update libsmb2 and its integration to prevent crashes and include bugfixes
- Improve nullability declarations of the VLCKit API
- Fix heating issue introduced through UPnP
- Add new debug logging API and deprecate the previous
- Fix concurrency issues in VLCMediaList
- Fix ARC issue when handling NSStreams in VLCMedia
- Fix crashes when using more than one logger with the new API
- Fix busy loop in UPnP support
- Replace VLCEventManager with an implementation based on lib dispatch
- Distribute VLCAudio header on macOS
- Fix crashes when handling VLCMediaLists with dynamic content
- Add new metadata API from VLCKitv4 and deprecate the previous implementation
- Add new VLCEventObjectManager preventing crashes on deallocation

**Comment by LePips** [comment]
I am not explicitly against updating to 4.0, however that's something they probably won't release for a very long time (it's not tagged). If that version somehow releases before I get to our mpv implementation then I can update my VLCUI project to accamadate any changes.
