### ISSUE TITLE
Next Up section not showing

### ISSUE THREAD

**Issue by CsErik2001** [jellyfin/Swiftfin#1106]
### Describe the bug

On the Home page the Next Up list is not showing, but if you change its orientation it comes back until a refresh or an app restart. 

### Application version

1.1

### Where did you install the app from?

App Store

### Device information

iPad Pro 6th gen.

### OS version

iPadOS 17.5.1

### Jellyfin server version

10.8.13

**Comment by simoncaron** [comment]
I'm also seeing this behavior on iPhone 15 Plus with both the current testflight version and the App Store version.

Looks like the loading of the "Up Next" section is failing from time to time. There are no errors in the queries made to the server. Here's an example where the section appears and disappears between refresh on the home screen:

https://github.com/jellyfin/Swiftfin/assets/8635747/fac29a4d-0243-4c96-a208-73213f55d07c
