### ISSUE TITLE
How about using SwiftFormat instead of SwiftLint?

### ISSUE THREAD

**Issue by PangMo5** [jellyfin/SwiftFin#111]
SwiftLint actually supports a lot of Lint, but it's just Lint.

As written in SwiftFormat README, SwiftFormat is designed focusing on autocorrect.
>Q. How is this different from SwiftLint?
>
>A. SwiftLint is primarily designed to find and report code smells and style violations in your code. SwiftFormat >is designed to fix them. While SwiftLint can autocorrect some issues, and SwiftFormat has some support for >linting, their primary functions are different.

There are sufficient rules for configuring the project.
https://github.com/nicklockwood/SwiftFormat/blob/master/Rules.md

Of course, it also support lint within Xcode.
https://github.com/nicklockwood/SwiftFormat#linting

SwiftLint also supports autocorrect, but it doesn't do anything. lol

**Comment by acvigue** [comment]
we have sonarcloud

**Comment by acvigue** [comment]
https://sonarcloud.io/dashboard?id=jellyfin_SwiftFin

**Comment by PangMo5** [comment]
I don't know if can sonarcloud solves this issue.
anyway if autocorrect is not required, you may close this issue xd

**Comment by acvigue** [comment]
all good :)
no, sonar doesn't do autocorrect but it does do code smells, bugs, style recommendations & more. 
IMO we don't really want autocorrect enabled on the CI as it may fxck something up, and that would be very bad :p

All right if I close this?

**Comment by PangMo5** [comment]
Okay, I agree with your opinion. :D
