### ISSUE TITLE
PagingLibraryView inline header resizes when safeArea changes

### ISSUE THREAD

**Issue by darrekk** [jellyfin/Swiftfin#1112]
### Describe the bug

Go to media tab
Click on library
See navigation bar resize and library content jumps

https://github.com/jellyfin/Swiftfin/assets/9374724/212378a8-25c7-4789-819d-df1338677b66

### Application version

1.0 and 1.1

### Where did you install the app from?

None

### Device information

iPhone 15 simulator and iPhone 14

### OS version

iOS 17.5

### Jellyfin server version

10.9.4

**Comment by LePips** [comment]
Duplicate #1033
