### ISSUE TITLE
DVR

### ISSUE THREAD

**Issue by lswee** [jellyfin/Swiftfin#1114]
Hey all, I've tried searching existing (including closed) issues and haven't found a thread on this topic, apologies if that's due to my lacklustre searching!

My current setup is Plex on a Pi and Infuse on tvOS. As Infuse doesn't have Live TV and DVR I utilise Plex's tvOS app to manage recording.

I would like to move to Jellyfin, but I'm unsure whether Swiftfin includes the ability to manage recording schedules. I can see Live TV is in testing, but does this include DVR and if not, is it on the roadmap?

**Comment by LePips** [comment]
Going to consider duplicate of #652
