### ISSUE TITLE
Rotation not working (not switching to landscape mode iOS)

### ISSUE THREAD

**Issue by fardeenfarrukh** [jellyfin/Swiftfin#1115]
### Describe the bug

On the Swiftfin iOS app it doesn’t go into landscape mode when you launch a video and rotate your phone it. It works when you launch the app while rotated into landscape mode but when you rotate again it goes back to portrait mode and stays there and doesn’t switch back.

### Application version

1.1(78)

### Where did you install the app from?

App Store

### Device information

iPhone 7

### OS version

iOS 15.8

### Jellyfin server version

10.9.4

**Comment by Squareheron942** [comment]
I have the same issue on iPhone 6s, though I was never able to get it into landscape mode at all. Notably on my iPhone 12 mini there is no issue.

**Comment by fardeenfarrukh** [comment]
> I have the same issue on iPhone 6s, though I was never able to get it into landscape mode at all. Notably on my iPhone 12 mini there is no issue.

Try closing the app off completely and then tilt your phone into landscape mode, doesn’t matter if it’s on the Home Screen and nothing happens, then launch the app in that position it should work at least that the way it’s working for me currently.

**Comment by ruizlenato** [comment]
Same probem

**Comment by lewis-fields** [comment]
I have the opposite problem.. it's only in landscape mode and won't work in portrait
