### ISSUE TITLE
Get Introskipper Plugin to work with tvOS-Swiftfin

### ISSUE THREAD

**Issue by anupamkumar** [jellyfin/Swiftfin#1123]
The [Intro-skipper plugin](https://github.com/jumoog/intro-skipper) is a really cool plugin that allows a user to skip intros and end-credits for TVShows. 

The plugin works on a web-browser by injecting a `div->button` element into the `videoPlayerContainer`. If the user clicks on this button the video jumps to a new precalculated timestamp (predetermined during analysis step performed by the plugin) and `web-videoplayer` reports the `timeupdate Progess Event` to the server.

I'll be honest, I have not looked at vlc-kit. So, I don't know if it's even possible to insert HTML elements into the playback/native-videoplayer. But it would be really cool if it can be done.

Alternatively, the [plugin's API](https://github.com/jumoog/intro-skipper/blob/master/docs/api.md) can be used to fetch the Intro and EndCredits timestamps for a TVEpisode. 
Swiftfin could make a async call to this API as soon as the user requests to play a TV-episode and when the server responds with the timestamps then, the player-UI can be updated to show a button with a label 'skip-intro' or something. 
Clicking this button can then move the video to the timestamp value provided by the Plugin API.

**Comment by itsrn** [comment]
I'd also love to see support for the plugin (if possible) in the iOS app, not just the tvOS app, because this plugin is really helpful.

**Comment by thornbill** [comment]
We will not provide support for third party plugins in official apps.

**Comment by realSZ27** [comment]
I assume you are already aware of this, but intro skipping is no longer a third party feature thanks to [media segments](https://jellyfin.org/posts/jellyfin-release-10.10.0/#media-segments)

**Comment by itsrn** [comment]
> I assume you are already aware of this, but intro skipping is no longer a third party feature thanks to [media segments](https://jellyfin.org/posts/jellyfin-release-10.10.0/#media-segments)

Thanks for pointing out! Didn't know this was a thing in 10.10 release until now.

So, does it mean that in the near future, a "Skip Intro" button will also be available in official clients (like Swiftin) if the server provides the marks generated by the "IntroSkipper" plugin?

**Comment by thornbill** [comment]
Yes it is possible. The web client shipped support in 10.10 and Android TV is in the 0.18 app release. I can't speak to how long it will take for Swiftfin to support them though. As always it depends on a volunteer having the time and desire to implement new functionality.

**Comment by foorschtbar** [comment]
The [media segments](https://jellyfin.org/posts/jellyfin-release-10.10.0/#media-segments) are a nice feature, but not a replacement for a simple skip button for intros and outros.
