### ISSUE TITLE
Swiftfin 1.1 on Apple TV ?

### ISSUE THREAD

**Issue by cutzenfriend** [jellyfin/Swiftfin#1126]
Hi,
in iOS I'm using version 1.1 already. But until today there is no update for tvOS in the App Store. Running version 1.0.1 there.

When does 1.1 land for tvOS?

**Comment by Mickey016** [comment]
Same question here, looks live the Apple TV store hasn’t been updated ?

**Comment by JPKribs** [comment]
Please see the prior discussion for this item:

https://github.com/jellyfin/Swiftfin/discussions/1099

**Comment by Mickey016** [comment]
Thanks @JPKribs for the clarification.
And kudos to the team for all the good work 👍
