### ISSUE TITLE
Not loading all libraries

### ISSUE THREAD

**Issue by Nathan118-S** [jellyfin/Swiftfin#1128]
It is only loading movies and favorites not home videos or music

**Comment by Nathan118-S** [comment]
![image](https://github.com/jellyfin/Swiftfin/assets/82177559/174d851c-9c7a-4f94-b810-0daf05293829)

**Comment by JPKribs** [comment]
At this time, Swiftfin has not implemented all Library types. 

I could be mistaken, but it looks like only **Movies**, **Shows**, **Mixed Movies & Shows**, and **Collections** are currently configured. Favorites are included as well but this is cross-media type.

I found this list of supported library types here:

https://github.com/jellyfin/Swiftfin/blob/main/Shared/ViewModels/LibraryViewModel/ItemLibraryViewModel.swift

**Comment by Nathan118-S** [comment]
Ok thank you

**Comment by Blackspell01** [comment]
In the code it says also "mixed". Does this mean that mixed library should be supported? Because for me it still doesn't seem to work with mixed

**Comment by luxychris2009** [comment]
HAS THERE BEEN ANY PROGRESS ON THIS?  DOES ANYONE KNOW?  all of my libraries are "home videos" ... and i would really like to use this apple tv app to play them!  i've tried Infuse ... however that only does "direct play" and will not allow me to transcode to lower qualities for streaming.  this would be a perfect solution!  IS THERE ANY WORKAROUND if "home videos" is being BLOCKED by swiftfin?  thanks!

**Comment by weegeeday** [comment]
This is still happeing. On latest apple TV. Is this going to be patched?

**Comment by JPKribs** [comment]
Please see our documentation for supported libraries here:

https://github.com/jellyfin/Swiftfin/blob/main/Documentation/libraries.md

**Comment by Kurbb** [comment]
it says its supported but it doesnt work???

**Comment by JPKribs** [comment]
> it says its supported but it doesnt work???

That was just updated for 1.4. You can see this now for our TestFlight or you can find it in our next release.

**Comment by Blackspell01** [comment]
Cool! Thank you for implementing this!
