### ISSUE TITLE
After 10.9.7 new meda libeary wont show 

### ISSUE THREAD

**Issue by isvein** [jellyfin/Swiftfin#1132]
### Describe the bug

1: updated server to 10.9.7
2: made an new video media libeary 
3: new libeary wont show up in swiftfin 
4: reinstalled app
5: still no show 

Meda libearies added before the update works.

### Application version

1.1(78)

### Where did you install the app from?

App Store

### Device information

iPhone XR 

### OS version

iOS 17.5.1

### Jellyfin server version

10.9.7

**Comment by JPKribs** [comment]
What library type did you add where it's not showing up?

At this time, Swiftfin only works for Movies, Shows, & Mixed Libraries. Additionally, Collections show as a "library".

**Comment by isvein** [comment]
Hello :)
I used the "Home Videos and Photos"  since this is game recordings. 
I did not know Swiftfin did not support this type yet :( 

Tried to make an new library with the type "Mixed Films and Programs", same happens.

If I make an regular "Movie" library it shows up, but none of the files/videos shows up, I guess because Jellyfin cant find them in any movie database

**Comment by JPKribs** [comment]
Interesting! Looking here: https://github.com/jellyfin/Swiftfin/blob/main/Shared/ViewModels/LibraryViewModel/ItemLibraryViewModel.swift

It looks like "Mixed" is there but I haven't personally tried it. It could just be Movies/Shows then... I believe eventually the goal is to have all types but for now Swiftfin is primarily for Movies and Shows as the other types are not currently implemented.

**Comment by LePips** [comment]
Swiftfin does not support home videos.
