### ISSUE TITLE
Release 1.1. on tvOS

### ISSUE THREAD

**Issue by ggobbe** [jellyfin/Swiftfin#1143]
**Describe the feature you'd like**

Can the recent 1.1.0 release be made available for tvOS?

**Additional context**

On tvOS, the app currently mentions the following: 

Version: 1.0.1 - Released 0 Mar 2023
Provider: Anthony Lavado
Requires: tvOS 15.0 or later (currenty installed is 17.5.1)

**Comment by john-pierre** [comment]
I would also really appreciate it if the 1.1.0 update could be made available for tvOS

**Comment by nielsvanvelzen** [comment]
#1126

**Comment by ggobbe** [comment]
Thanks, hadn't seen that one.
