### ISSUE TITLE
[Feture Request] Live TV Guide

### ISSUE THREAD

**Issue by M1noa** [jellyfin/Swiftfin#1146]
**Describe the feature you'd like**
A basic Live TV Guide on Apple TV like the web version of jellyfin. I dislike the current grid one, and a nice guide can go a long way!

**Additional context**
Examples
![Example](https://github.com/jellyfin/Swiftfin/assets/57844837/d96966e6-c531-44de-9197-3a476c906c04)
![Example2](https://github.com/jellyfin/Swiftfin/assets/57844837/d00a1a6f-2d51-4fbd-bdf0-b684ab837fa6)

**Comment by LePips** [comment]
Duplicate #842
