### ISSUE TITLE
When AirPods are removed, media continues playing out loud

### ISSUE THREAD

**Issue by Teelair** [jellyfin/Swiftfin#1160]
### Describe the bug

1. Starting playing media with AirPods in
2. Remove airpods while media is playing
3. Witness media continuing to play out loud, and not automatically pause. (This is a break in behavior with every other popular app such as YouTube, Netflix, Hulu, etc.)

### Application version

1.1(78)

### Where did you install the app from?

App Store

### Device information

iPhone 15 Pro

### OS version

iOS 18 dev beta 4, (this also happened on iOS 17)

### Jellyfin server version

10.8.13

**Comment by chickdan** [comment]
I am able to reproduce this with the Swiftfin player but switching to the native player it works as expected. Not a solution, I know, but I wanted to provide information for anyone looking into this bug (I'm currently looking but someone may beat me to it).

**Comment by UtkuGogcay** [comment]
![image](https://github.com/user-attachments/assets/6b982f2b-793a-42e8-905f-c3e92d6649e7) I think this happens because playing videos does not show up at media section in control center.

**Comment by UtkuGogcay** [comment]
#1166 probably is the same issue
