### ISSUE TITLE
媒体库缺失

### ISSUE THREAD

**Issue by mark7913** [jellyfin/Swiftfin#1162]
### Describe the bug

媒体库中只有电影和电视剧两个文件夹，其他文件夹缺失

### Application version

1.1（78）

### Where did you install the app from?

App Store

### Device information

iphone015pri

### OS version

17.5.1

### Jellyfin server version

10.8

**Comment by JPKribs** [comment]
> 媒体库中只有电影和电视剧两个文件夹，其他文件夹缺失
> There are only two folders in the media library, movies and TV series, and the other folders are missing

At this time, only Movies, TV Shows, and Collections are supported.
