### ISSUE TITLE
MultiUser Switch User AppleTV

### ISSUE THREAD

**Issue by Err0r0815** [jellyfin/Swiftfin#1164]
**Describe the feature you'd like**
On AppleTV there is an option to switch between mutltiple AppleIDs. It would be nice if i switch between these AppleIDs, also the Jellyfin User in the App would change.

**Additional context**
If i change the AppleID and there is no JEllyfin user, then it should be free to configure the connection and user. after the configuration it should remeber it if i come back to this AppleID.

**Comment by LePips** [comment]
Duplicate #258
