### ISSUE TITLE
Swiftfin crashes on login

### ISSUE THREAD

**Issue by lukeh990** [jellyfin/Swiftfin#1167]
### Describe the bug

I am able to add my Jellyfin server to the app. I am using a NGINX Reverse Proxy with HTTPS port 443 and a trusted certificate. 

When attempting to sign in when using user/pass or quick connect authentication the app will crash just after pressing the sign in button.

I was previously able to login to the server. But I removed the server from swiftfin, changed the name to one that uses spaces (No other special chars), and now I am unable to sign in.

### Application version

1.1 (78)

### Where did you install the app from?

App Store

### Device information

iPhone 13

### OS version

iOS 18 Public Beta 2 (22A5316k)

### Jellyfin server version

10.9.8

**Comment by lukeh990** [comment]
After a bit more testing, resetting the server name didn't change anything.

**Comment by spkesDE** [comment]
I have the same issue on the latest iOS 18 version using the same setup.
