### ISSUE TITLE
Wrong library primary image is used

### ISSUE THREAD

**Issue by sjorge** [jellyfin/Swiftfin#1194]
### Describe the bug

1. Open swiftfin
2. Hit the media icon on the bottom bar
3. See different image than on web, expo, or infuse

### Application version

1.2 (1)

### Where did you install the app from?

TestFlight

### Device information

iPhone 15 Pro

### OS version

iOS 17.5.1

### Jellyfin server version

10.9.9

**Comment by sjorge** [comment]
![image](https://github.com/user-attachments/assets/dca0f171-b558-456f-a072-eef5a4949645)

But on expo/web

![image](https://github.com/user-attachments/assets/252c00c8-df71-4a1a-9c3c-fce71a1d892c)

I don't like the auto generated ones so I set custom images. They seem to be picked up by all clients except swiftfin.

**Comment by LePips** [comment]
Disable `Settings -> Customize -> Random Image`
