### ISSUE TITLE
[iOS] Appearance settings item disapearing when toggingling Use Splashscreen

### ISSUE THREAD

**Issue by sjorge** [jellyfin/Swiftfin#1198]
### Describe the bug

I noticed this when double checking things for #1197 
![IMG_2676](https://github.com/user-attachments/assets/7793925f-6814-4911-ad11-75463cde4f4c)
![IMG_2677](https://github.com/user-attachments/assets/4246121e-df68-413b-9c28-52505500af9a)

When toggling `Use Spashscreen` the `Appearance` item gets hidden/unhidden. I'm guessing whatever is hiding/unhiding the service selection also accidentally hides the Appearance one.

### Application version

1.2 (2)

### Where did you install the app from?

TestFlight

### Device information

iPhone 15 Pro

### OS version

iOS 17.5.1

### Jellyfin server version

10.9.9

**Comment by LePips** [comment]
This is an intended design decision to have the dark mode appearance when using the splashscreen. I wouldn't have found just disabling the option to be any better.
