### ISSUE TITLE
Video Player white bars on edges

### ISSUE THREAD

**Issue by LeviSnoot** [jellyfin/Swiftfin#12]
v1.0.0 (18)
![image](https://user-images.githubusercontent.com/13402525/119533426-1d504800-bd86-11eb-95e8-2ba04d839686.jpeg)
iPad Pro 2018 12.9"
![image](https://user-images.githubusercontent.com/13402525/119533525-3527cc00-bd86-11eb-8b02-9918288f6a80.jpeg)
iPhone X Portrait
![image](https://user-images.githubusercontent.com/13402525/119533548-3eb13400-bd86-11eb-9ca2-4c165aaf3915.jpeg)
iPhone X landscape

**Comment by acvigue** [comment]
Does dark mode appear ok?

**Comment by LeviSnoot** [comment]
Dark mode makes the text in the status bar appear correctly and makes the background black, however it still causes pillarboxing in all instances.

**Comment by acvigue** [comment]
Fixed in #19
Pillarboxing is normal behavior currently. it fills the iPad screen while keeping the original aspect ratio

**Comment by LeviSnoot** [comment]
![image](https://user-images.githubusercontent.com/13402525/119548516-935cab00-bd96-11eb-9a12-bb41fd2766d8.jpeg)

iPad screen is not filled, even in dark mode.

**Comment by acvigue** [comment]
Hm. 
Let me look into this

**Comment by acvigue** [comment]
Device doesn't have a notch does it?

**Comment by LeviSnoot** [comment]
Nope, not the iPad. the iPhone does.

**Comment by acvigue** [comment]
Will be fixed in build 22 :)
