### ISSUE TITLE
Collection poster not displaying in portrait mode 

### ISSUE THREAD

**Issue by SkyDiver7199** [jellyfin/Swiftfin#1208]
### Describe the bug

Just go to collection, select the portrait layout, all of the posters is not being displayed. 
however, all posters display fine when switch to landscape mode
![IMG_2586](https://github.com/user-attachments/assets/830e7382-688d-406e-82dc-1c40955c7b6f)

### Application version

1.1(78)

### Where did you install the app from?

App Store

### Device information

iPhone 14 pro

### OS version

iOS 17.6.1

### Jellyfin server version

10.9.9

**Comment by SkyDiver7199** [comment]
![Uploading IMG_2587.png…]()

**Comment by SkyDiver7199** [comment]
![IMG_2587](https://github.com/user-attachments/assets/adca213b-6a59-470c-9143-f0588c36744d)

**Comment by LePips** [comment]
Has been fixed but is in TestFlight by #1133
