### ISSUE TITLE
Want option to limit next up in number of days like the web client

### ISSUE THREAD

**Issue by sjorge** [jellyfin/Swiftfin#1211]
**Describe the feature you'd like**
The web client has an option to limit `Next Up` to a certain number of days:
<img width="1032" alt="Screenshot 2024-08-25 at 18 39 22" src="https://github.com/user-attachments/assets/0267f0f6-95b2-4829-bc78-b434d71c19e9">

This is nice as I have a bunch of shows I've stopped watching a long time ago that show up.

Note: this started with 10.9.10 as the endpoint got tweaked to return all items now.

With it set to 90 days the web client shows these:
<img width="1346" alt="Screenshot 2024-08-25 at 18 37 44" src="https://github.com/user-attachments/assets/4de26e2b-06ad-4fff-bf94-2494c72c43a8">

On 10.9.10 swiftfin shows a very very very long scroll list (not found the end yet)
![Screenshot 2024-08-25 at 18 38 02](https://github.com/user-attachments/assets/b00cc604-d786-4431-b0f2-be574ee1776f)

![Screenshot 2024-08-25 at 18 38 04-1](https://github.com/user-attachments/assets/e23e013f-f7a7-446e-9919-85ea2ae1208a)

![Screenshot 2024-08-25 at 18 38 10-2](https://github.com/user-attachments/assets/578ee9b3-b974-4066-867a-541e058f1f34)

**Additional context**
n/a

**Comment by JPKribs** [comment]
Hey @sjorge, I thought this was a good addition. I was taking a look at how Jellyfin-Web was handling this and realized this was a really straight forward ask. Please see my PR below and let me know if you have any questions/changes:

https://github.com/jellyfin/Swiftfin/pull/1212

**Comment by sjorge** [comment]
Wow that was quick! Not that I have a way to build the PR to test, but I had a glance the code and it looks fine.

A nice solution to setting the number of days that also works well for tvOS!
