### ISSUE TITLE
Version 1.1.1 not available in AppleTV App Store

### ISSUE THREAD

**Issue by muggajoe** [jellyfin/Swiftfin#1218]
### Describe the bug

The latest version (1.1.1) of the Swiftfin app is not on the AppleTV App Store. The version I see in the store is v 1.0.1. I'm in Canada if that matters. 

### Application version

1.1.1

### Where did you install the app from?

App Store

### Device information

AppleTV 4K (model A1842 32GB)

### OS version

17,6,1

### Jellyfin server version

10.9.1

**Comment by thornbill** [comment]
https://github.com/jellyfin/Swiftfin/discussions/1099
