### ISSUE TITLE
There is no content in the app

### ISSUE THREAD

**Issue by mkhasson97** [jellyfin/Swiftfin#1224]
### Describe the bug

When I login there is no content at all (music and video) while in the official Jellyfin iOS app is working
Tried on multiple iOS devices and it is the same, on iOS 18 developer beta also now working

### Application version

1.1

### Where did you install the app from?

App Store

### Device information

iPhone 14 Pro

### OS version

iOS 17.6.1

### Jellyfin server version

10.9.10

**Comment by zPhoeniqz** [comment]
Also encountered this bug on the App Store version as well as the Testflight version.

iPhone 8
iOS 16.7.5

**Comment by mkhasson97** [comment]
Correct, I have the latest iOS 18 developer beta 8 on my iPhone 13 Pro and the issue is the same

**Comment by mkhasson97** [comment]
Correct, I have the latest iOS 18 developer beta 8 on my iPhone 13 Pro and the issue is the same

**Comment by mkhasson97** [comment]
I thought the music is also supported

**Comment by LePips** [comment]
Music is not supported. You can see the many closed issues on this.
