### ISSUE TITLE
Deleting device via dashboard results in 401, but now way to reauthenicate

### ISSUE THREAD

**Issue by sjorge** [jellyfin/Swiftfin#1228]
### Describe the bug

While trouble shooting a different issue I uninstalled + reinstalled swiftfin but while cleaning up the old device I delete the wrong one... so not a normal thing to happen but easy to replicate and it should be handled better.

(1. install swiftfin)
(2. add a server and sign in)
3. Delete the swiftfin device entry via the jellyfin dashboard
4. Get greeted with a 401 Auth error (Not unexpected)

Now to get out of this broken state you can either:
a) delete + install swift fin
b) hit user icon, hold on user, pick delete

Allowing to login again would be a better way to handle it, maybe by showing a button to do so. Alternatively show  the 401 Authentication error and 'logout' the user swiftfin side.

### Application version

1.2

### Where did you install the app from?

TestFlight

### Device information

iPhone 15 Pro

### OS version

iOS 17.5.1

### Jellyfin server version

10.9.10

**Comment by JPKribs** [comment]
I think this is a duplicate of https://github.com/jellyfin/Swiftfin/issues/1138

**Comment by sjorge** [comment]
Seems like it.
