### ISSUE TITLE
UK AppleTV store still shows v1.0.1 (IOS shows 1.1)

### ISSUE THREAD

**Issue by RedNo7** [jellyfin/Swiftfin#1235]
### Describe the bug

Goto Apple TV store (UK)
Search for Swiftfin
Version is 1.0.1

### Application version

1.1.1

### Where did you install the app from?

App Store

### Device information

AppleTV, 4th gen

### OS version

17.6.1

### Jellyfin server version

n/a

**Comment by sjorge** [comment]
1.1 was never released for tvOS, so that is correct.

**Comment by RedNo7** [comment]
Oh. well, at least I'm not going mad.
Is there any intention of fixing the TVOS version?  ...this is the single reason I still can't use JellyFin (as nothing plays).
