### ISSUE TITLE
iOS/iPadOS 18: Backdrop image interferes with UI when viewing a show/movie’s details

### ISSUE THREAD

**Issue by Tanjoodo** [jellyfin/Swiftfin#1237]
### Describe the bug

1. Click any TV show or movie
2. Scroll down
3. Observe that the details are hard to read due to the backdrop image interfering with the white text and other UI elements. 

Screenshots below. 
![IMG_0050](https://github.com/user-attachments/assets/8d55b2d2-ff11-42f8-bf4d-a8f5c93ca5fd)

![IMG_0051](https://github.com/user-attachments/assets/8cb71d83-b8c1-4454-9194-3d1dc79e2522)

For the record, this was observed on iPad mini and iPhone on iOS 18. Problem appears in both portrait and landscape orientations on iPad mini. 

The same cannot be observed on iPhone on iOS 17.X
### Application version

1.1(78)

### Where did you install the app from?

App Store

### Device information

iPad mini (6th generation)

### OS version

iPadOS 18.0 (22A3354)

### Jellyfin server version

10.9.9

**Comment by Aeases** [comment]
can reproduce

**Comment by Phippe** [comment]
This is fixed in version 1.2

**Comment by Phippe** [comment]
I haven't seen it reported yet, but this issue seems to have reoccurred on iOS 26 (Swiftfin 1.3, Server 10.10.7, iPhone 11).

**Comment by JPKribs** [comment]
> I haven't seen it reported yet, but this issue seems to have reoccurred on iOS 26 (Swiftfin 1.3, Server 10.10.7, iPhone 11).

One of the packages we used needed to be updated to work for iOS 26. This is resolved on our TestFlight and will be included on our next release:

https://github.com/jellyfin/Swiftfin/pull/1706

Edit: This fix exists in our current TestFlight now!
