### ISSUE TITLE
What is the appletv IOS app ID?

### ISSUE THREAD

**Issue by patrickharris** [jellyfin/Swiftfin#1238]
Can anyone tell me what the swiftfin appletv IOS app ID is? When I deselect swiftfin native player, homeassistant correctly receives play/pause information, but I'm unable to specifically target swiftfin app, as I do not know what it's app ID is. Infuse app ID for instance is com.firecore.infuse.

**Comment by thornbill** [comment]
Should be `org.jellyfin.swiftfin` I believe.

**Comment by LePips** [comment]
That is correct. If that doesn't work, this may be the same issue as #935

**Comment by patrickharris** [comment]
This works - thank you!

**Comment by rwjack** [comment]
To clarify, this is not related to 935
