### ISSUE TITLE
Double Touch not recognized

### ISSUE THREAD

**Issue by mdebbar** [jellyfin/Swiftfin#1239]
### Describe the bug

The "Double Touch" gesture isn't being recognized during playback. I tried setting it to "Pause/Play" and "Aspect fill" but it doesn't work. Other gestures are working fine for me.

<img width="784" alt="image" src="https://github.com/user-attachments/assets/1afb02b1-dba8-4c3f-b033-e521e5fc05be">

### Application version

1.1 (78)

### Where did you install the app from?

App Store

### Device information

iPhone 15 Pro & iPad Pro 12.9" (4th gen)

### OS version

iOS 18.0 & iPadOS 17.6.1

### Jellyfin server version

10.9.10

**Comment by lfsty** [comment]
yeah, got the same problem
