### ISSUE TITLE
Server Version not being updated in settings view

### ISSUE THREAD

**Issue by Retch** [jellyfin/Swiftfin#1249]
### Describe the bug

When you go to the server settings in Swiftfin, the server version will be the one when the connection to the server was made. When you update the server, the new version info is not being fetched again.

### Application version

1.1 (78)

### Where did you install the app from?

TestFlight

### Device information

iPhone 12 Pro, iPad Mini 5

### OS version

iOS 18.0, iPadOS 18.0

### Jellyfin server version

10.9.11

**Comment by JPKribs** [comment]
Starting in 1.2, we no longer have a server version included in the server portion of the settings.
