### ISSUE TITLE
View route improvement and deep-linking support

### ISSUE THREAD

**Issue by PangMo5** [jellyfin/Swiftfin#125]
Currently Swiftfin's view route is hard to understand and complicated. 
I'll resolve it.

And I will also support some deep links while working on related works.

**Comment by PangMo5** [comment]
I tried many libraries, but I didn't like anything.
I'll look into it more when I get a better library.

**Comment by PangMo5** [comment]
https://github.com/SwiftUIX/Coordinator
https://github.com/Bahn-X/swift-composable-navigator
https://github.com/frzi/SwiftUIRouter
https://github.com/rundfunk47/stinsen

**Comment by LePips** [comment]
Just saw your most recent comment. Looking at that list, i like swift-composable-navigator. It's similar to the coordinator pattern in that navigating throughout the app is out of the responsibility of the views. However, this would require an entire re-work of your PR, which I know sucks.

**Comment by PangMo5** [comment]
Yes, I also like the swift-complementable-navigator, but it seems the problem is that the "tab" isn't supported yet :(
I think there's a PR related to this.
