### ISSUE TITLE
Prioritize Apple TV over iPhone/iPad

### ISSUE THREAD

**Issue by RespectIsEverything** [jellyfin/Swiftfin#1252]
I could be mistaken, but it seems that Apple TV should be the priority target device for a media server.
The preferred manner to watch media is on a TV, not a 5" screen which requires constant hand stabilization.

Context:

It's been 4 months since the iPhone release of 1.1.1
Meanwhile, tvOS is on 1.0.1 from 18 months ago.

**Comment by LePips** [comment]
PRs are welcome.
