### ISSUE TITLE
No media shown after Swiftfin login

### ISSUE THREAD

**Issue by Gibber** [jellyfin/Swiftfin#1253]
### Describe the bug

From Swiftfin on my iOS devices I can access the Jellyfin server and sign in no problem but that it is.
After sign in the only thing on the Home screen is "Home" and the only thing on the Media screen is "All Media" and "Favorites".
How do I get to my media?
The official Jellyfin client works normally from the same server. 

### Application version

1.1 (78)

### Where did you install the app from?

App Store

### Device information

iPhone X iOS 16.7.10   and   iPad Pro iOS 17.7

### OS version

see above

### Jellyfin server version

10.9.11

**Comment by LePips** [comment]
What type of content do you have?

**Comment by Gibber** [comment]
Well That would explain it! My media is photos and music!!
Thanks for the quick response.
