### ISSUE TITLE
Shuffle Button for TV Shows on iOS and tvOS clients

### ISSUE THREAD

**Issue by sarveshshah** [jellyfin/Swiftfin#1257]
**Describe the feature you'd like**
Jellyfin web clients and other media players have a shuffle button within the TV show folder.  It randomly plays episodes and is an amazing feature. Are there any plans to implement this feature on iOS and tvOS clients?

Screenshot:
![image](https://github.com/user-attachments/assets/b3b626a3-6cb0-4b22-98f3-ebc9742be2c7)

**Comment by adiberk** [comment]
This would be amazing both at the season level and the overall show level (across seasons)

**Comment by LePips** [comment]
Considering a duplicate of #673.
