### ISSUE TITLE
tvOS 1.2

### ISSUE THREAD

**Issue by ryanlbates01** [jellyfin/Swiftfin#1262]
Good evening.

Great work on 1.2, looks like you all have put a lot of effort into the release :) I see in 1.2’s release notes there’s some updates for tvOS.

When will 1.2 be available on the tvOS App Store yet as I’m still only 1.0.1 available at the moment?

**Comment by LePips** [comment]
Apologies, but the current situation hasn't changed for tvOS.

https://github.com/jellyfin/Swiftfin/discussions/1099

**Comment by ryanlbates01** [comment]
just wanted to know if there was any rough timeline for a tvOS update?

I’ve come to realise the current tvOS version is more buggy than I first realised. I’ve now confirmed there are audio-sync issues with the current version which now I’ve realised it is making it unusable. I’ve since had to move over to infuse player.

the iOS version works great and would love to be able to have the same experience on my appleTV as this is how I view my content.

Appreciate all the work you guys put in.
