### ISSUE TITLE
TVOS is multiple versions behind. Only 1.0.1 is available.

### ISSUE THREAD

**Issue by kwjett** [jellyfin/Swiftfin#1263]
### Describe the bug

Open App > Navigate to Settings > Scroll to bottom
Version shows 1.0.1 still

Checking App store on AppleTV shows 1.0.1 as latest. But on iPhone and iPad 1.2 is latest.

Checked with multiple households/accounts/ATVs

![IMG_6317](https://github.com/user-attachments/assets/affe4706-279a-42d1-a2f1-080827ed7f4f)
![IMG_6318](https://github.com/user-attachments/assets/d59787f9-ca0b-456c-9f35-99db084cf156)

### Application version

1.0.1

### Where did you install the app from?

App Store

### Device information

Apple TV 4K

### OS version

TVOS 18.0 (22J357)

### Jellyfin server version

10.9.9

**Comment by LePips** [comment]
Please see #1262.

**Comment by kwjett** [comment]
You should probably put something in the readme that TVOS won’t be getting updates to prevent all of these PRs.
