### ISSUE TITLE
Chapter Slider no longer work in  1.2(4)

### ISSUE THREAD

**Issue by nokaka** [jellyfin/Swiftfin#1265]
### Describe the bug

Chapter Slider no longer work in 1.2(4)

![IMG_9842](https://github.com/user-attachments/assets/a160ecd8-975d-438e-90b9-ca6f9baf0ba7)

### Application version

1.2(4)

### Where did you install the app from?

App Store

### Device information

Chapter Slider no longer work in 1.2(4)

### OS version

18.0.1

### Jellyfin server version

 10.9.3

**Comment by nokaka** [comment]
![IMG_9843](https://github.com/user-attachments/assets/985a2cbd-d82d-4260-bc8e-0c1fcf83734c)

**Comment by LePips** [comment]
Does this media have chapters?

**Comment by nokaka** [comment]
All chapter sliders disappeared in Swiftfin. But it works fine in jellyfin web.
![IMG_9844](https://github.com/user-attachments/assets/f592e544-772f-491e-b27e-205579d08015)

**Comment by nokaka** [comment]
It works fine in 1.2(3)
![IMG_9847](https://github.com/user-attachments/assets/6b62243e-c3d0-4a90-8ac6-888c91877d3b)
![IMG_9846](https://github.com/user-attachments/assets/351e3cf1-ee9d-4564-b62a-1fc52c02ec14)

**Comment by chickdan** [comment]
I noticed this recently as well, I don't know if something changed with iOS 18 or from the Jellyfin Server but media where I had previously seen chapters no longer have them. Honestly though, I don't even remember what that media was so I could be misremembering and I haven't had a chance to do any investigation.

**Comment by chickdan** [comment]
I've traced it back to #1169 as that's when the chapters stop appearing.

**Comment by LePips** [comment]
Thanks for finding that. I will probably create a 1.2.1 branch for that small fix based off the 1.2 tag instead of waiting for 1.3, as I want my video player refactor to be in that version.
