### ISSUE TITLE
Update Menu Bar to match Apple's UX Conventions

### ISSUE THREAD

**Issue by ultratiem** [jellyfin/Swiftfin#1285]
The current menu bar in 1.3 is sorted in the following order and labels Search rather than using the standardized search icon:

![IMG_1229](https://github.com/user-attachments/assets/a7d457a8-4b81-4ef5-bb70-ff1ba1e4b390)

But this unfortunately doesn't match Apple's own UX conventions. Below are taken from Books and the App Store. As you can see, they include search at the end, and rather than label it, they use the standardized "search" icon available in SF Symbols.

![IMG_1230](https://github.com/user-attachments/assets/77c265e6-9657-4a31-84d5-d2561ddaa0c4)
![IMG_1231](https://github.com/user-attachments/assets/1dd7915e-72f1-448d-8eb9-93cd2477f516)

To make Swiftfin a better fit into Apple's ecosystem, please consider adopting the same UX conventions.

Moreover, rather than labeling the first most screen "Home", using the terminology "Library" may be a stronger fit as that best describes the screen's contents.

Thank you for your consideration.

**Comment by LePips** [comment]
Considering duplicate with #1034, which would move to (closer) to using the updated tab bars.

**Comment by LePips** [comment]
No.
