### ISSUE TITLE
Apple TV Version stuck on 1.0.1

### ISSUE THREAD

**Issue by salarx** [jellyfin/Swiftfin#1301]
### Describe the bug
If I go to [https://apps.apple.com/ca/app/swiftfin/id1604098728](url), the latest version of Swiftfin for Apple TV is 1.2. But when I see on Apple TV Apple Store, it's 1.0.1. 

### Extra Information

- I signed up for TestFlight in early 2023, but currently I don't have any app listed under TestFlight.
- I have tried removing / adding my Apple Store account again, and even resetting my Apple TV Device.

### Application version

1.0.1

### Where did you install the app from?

TestFlight

### Device information

Apple TV 4K (3rd Generation)

### OS version

tvOS 18.1 (22J580)

### Jellyfin server version

10.10.0

**Comment by thornbill** [comment]
https://github.com/jellyfin/Swiftfin/discussions/1294
