### ISSUE TITLE
macOS native app (NOT iPad PORT)

### ISSUE THREAD

**Issue by lumaa-dev** [jellyfin/Swiftfin#1304]
Title is pretty clear. Please make a full macOS port of the app, and NOT a "Designed for iPad" macOS app (it seems like it was previously possible)

**Comment by sjorge** [comment]
I don't think that is in scope for swiftfin, there is already a decent client.
https://github.com/jellyfin/jellyfin-media-player

It direct plays nearly everything you throw at it.
