### ISSUE TITLE
Next up on TVos doesn't seem to work

### ISSUE THREAD

**Issue by justdanyul** [jellyfin/Swiftfin#1309]
### Describe the bug

When watching TV series, the "Next up" functionality that allows us to continue watching where we left off, is broken for me. It's suggesting episode I already watched. I ensured that this episode is already marked as watched. But it doesn't seem to do any difference.

### Application version

1.0.1 (70)

### Where did you install the app from?

App Store

### Device information

Apple TV 4K 3rd Generation

### OS version

TVos 18.1

### Jellyfin server version

10.10.0

**Comment by JPKribs** [comment]
Currently, this is a known item with tvOS. We have another open issue here: https://github.com/jellyfin/Swiftfin/issues/1155 & https://github.com/jellyfin/Swiftfin/issues/784. I am going to close this as a duplicate but please follow our discussion for this item at either of those issues or please see our tvOS Status Update for information on when we can expect to see our next changes to tvOS. 

I don't want to make any commitments for timing, but this item can be found [here](https://github.com/jellyfin/Swiftfin/discussions/1294) as 'Reactive Home Screen'.
