### ISSUE TITLE
[TVOS] Ability to choose which libraries TV Shows and Movies are pulled from

### ISSUE THREAD

**Issue by archessmn** [jellyfin/Swiftfin#1315]
**Describe the feature you'd like**
I would like some way to select which of my libraries get used for the TV Shows and Movies categories. Currently both categories also pull data from another library which is not marked as "Shows" or "Movies" in Jellyfin, but as "Other", which is adding unrelated videos into both feeds.

**Comment by LePips** [comment]
See #1317.
