### ISSUE TITLE
Response status code was unacceptable: 403

### ISSUE THREAD

**Issue by dorkbuttt** [jellyfin/Swiftfin#1319]
### Describe the bug

Receiving error code 403 when tapping on any media (folders display their contents with proper thumbnails, but that's it).

"Response status code was unacceptable: 403."

### Application version

1.3(2)

### Where did you install the app from?

TestFlight

### Device information

iPhone 13 Pro Max

### OS version

iOS 18.2 (22C5131e)

### Jellyfin server version

10.10.2

**Comment by JPKribs** [comment]
403 is 'Forbidden' which most likely means that your login session is no longer valid. Did you remove this device from Jellyfin Web? Could you go to:

Sign Out -> Delete this User -> Sign Back in and see if this issue persists?

**Comment by dorkbuttt** [comment]
@JPKribs I've done that, on different devices, and removing the app and reinstalling it. In each instance, it remains forbidden. Even on my iPad.

**Comment by JPKribs** [comment]
Interesting. So this is only impacted on Swiftfin with no other clients being impacted? Are you connecting using a reverse proxy? Can you confirm that, if you are accessing that outside of your network, this user is enable for remote access?

What I'm kind of focused on here is a 403 error means Swiftfin successfully connected to the server, and the server returned back a forbidden error. Meaning, something about the connection information provided is not valid. Usually, I get this when I remove a device on web since the session is no longer valid. But, I've also been able to re-create this when I try to connect to an HTTPS server via HTTP. The last way I get this is I have accounts that do not have external access. So when I try to access the server a non-external account it will give me a 403.

If none of those do the trick, would you be able to try looking at the network belongs in Swiftfin? They should be in settings > logs.

**Comment by dorkbuttt** [comment]
@JPKribs Yes, Swiftfin is the only app that is throwing a 403 error. I connect using the reverse proxy manager NPMPlus on Unraid, making the certificate in the manager, downloading it, converting it to .pfx, and uploading it to be read by Jellyfin (Though I may be complicating this. I have NPMPlus using the certificate to encrypt *to* the app's local port (I think this is how I should say it) while Jellyfin itself has the certificate in its Networking settings. Plus, the certificate is saved as .pfx and I am using NPMPlus which labels its certificates as TLS instead of SSL, if those make at all a lick of difference). And yes, the account is enabled for remote access; I can very easily hop onto my laptop (specifically) and watch what I want on the Jellyfin client. 

When I do connect locally (via 192.168..), Firefox throws a warning that the certificate is for the external domain only, not the local IP. And here are the logs for when I log in and try to access any piece of media on Swiftfin:

https://paste.sr.ht/~dorkbutt/bff27b35a071becea1a2a10297d563222dfee715

**Comment by JPKribs** [comment]
Just a quick note, you may want to delete out your APIs / Domain Name. Here is the cleaned up impacted log:

```
13:55:21.565 · GET · 403 Forbidden · 40 ms
–––––––––––––––––––––––––––––––––––––––
/Users/[USER_ID]/Items?fields=AirTime&fields=CanDelete&fields=CanDownload&fields=ChannelInfo&fields=Chapters&fields=ChildCount&fields=CumulativeRunTimeTicks&fields=CustomRating&fields=DateCreated&fields=DateLastMediaAdded&fields=DisplayPreferencesId&fields=Etag&fields=ExternalUrls&fields=Genres&fields=HomePageUrl&fields=ItemCounts&fields=MediaSourceCount&fields=MediaSources&fields=OriginalTitle&fields=Overview&fields=ParentId&fields=Path&fields=People&fields=PlayAccess&fields=ProductionLocations&fields=ProviderIds&fields=PrimaryImageAspectRatio&fields=RecursiveItemCount&fields=Settings&fields=ScreenshotImageTags&fields=SeriesPrimaryImage&fields=SeriesStudio&fields=SortName&fields=SpecialEpisodeNumbers&fields=Studios&fields=BasicSyncInfo&fields=SyncInfo&fields=Taglines&fields=Tags&fields=RemoteTrailers&fields=MediaStreams&fields=SeasonUserData&fields=ServiceName&fields=ThemeSongIds&fields=ThemeVideoIds&fields=ExternalEtag&fields=PresentationUniqueKey&fields=InheritedParentalRatingValue&fields=ExternalSeriesId&fields=SeriesPresentationUniqueKey&fields=DateLastRefreshed&fields=DateLastSaved&fields=RefreshState&fields=ChannelImage&fields=EnableMediaSourceDisplay&fields=Width&fields=Height&fields=ExtraIds&fields=LocalTrailerCount&fields=IsHD&fields=SpecialFeatureCount&enableUserData=true&ids=[ITEM_ID]

URLSessionDataTask
–––––––––––––––––––––––––––––––––––––––
Host: [REDACTED]
Date: Nov 19, 2024 at 1:55:21 PM (EST)
Duration: 39.9 ms

Request Headers (4)
–––––––––––––––––––––––––––––––––––––––
Accept: application/json
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9
Authorization: MediaBrowser Device=iPhone, Version=1.3, Token=[REDACTED], Client=Swiftfin iOS, DeviceId=[REDACTED]

Request Body
–––––––––––––––––––––––––––––––––––––––
–

Response Headers (11)
–––––––––––––––––––––––––––––––––––––––
Alt-Svc: h3=”:443”; ma=86400
Content-Encoding: br
Content-Type: text/html
Date: Tue, 19 Nov 2024 18:55:21 GMT
Strict-Transport-Security: max-age=63072000; includeSubDomains; preload
Vary: accept-encoding
content-security-policy: upgrade-insecure-requests
referrer-policy: strict-origin-when-cross-origin
x-content-type-options: nosniff
x-frame-options: SAMEORIGIN
x-xss-protection: 0

Response Body (148 bytes)
–––––––––––––––––––––––––––––––––––––––

<html>
<head><title>403 Forbidden</title></head>
<body>
<center><h1>403 Forbidden</h1></center>
<hr><center>NPMplus</center>
</body>
</html>
```

Based on the log, the 403 Forbidden response and the Response Body indicate the following potential issues:

###Key Observations

The line <center>NPMplus</center> suggests the request is being blocked by Nginx Proxy Manager (or similar middleware, such as a reverse proxy). The issue is likely not with Jellyfin itself but with the proxy sitting in front of it.

###Likely Causes

**Request Too Long**

The URL might be exceeding a configured length limit in the reverse proxy, causing it to reject the request.

###Troubleshooting Steps:

**Step 1: Validate Swiftfin Works with the Proxy Disabled**

Test connect to Swiftfin directly using the http://192.168.X.X:port and validate if this issue persists. If it persists, we can confirm this is a Swiftfin/Jellyfin issue opposed to the proxy.

**Step 2: Check Proxy Logs**

Review the Nginx Proxy Manager (or other proxy) logs for this request. Look for:

Block reasons (e.g., 413 Request Too Large, rate-limiting).

WAF or firewall-related blocks.

**Step 3: Adjust Proxy Rules**

Increase allowed URL length:

If Nginx is blocking due to the long query string, increase the buffer size in your proxy’s configuration:

http {
    large_client_header_buffers 4 16k;
}

Adjust Security Headers:

Temporarily disable overly restrictive headers (like content-security-policy) to verify if they are causing the issue.

I hope this helps!

**Comment by dorkbuttt** [comment]
Upon observing my proxy manager's own logs, which I didn't think to do until you brought it up in Step 2, there was a setting that I checked without much thought and it showed up as being the culprit: ModSecurity. Pretty sure that is another rabbit hole for me to jump down so I will simply leave it deactivated with everything else up (HSTS and its security headers also remaining up). Turning that off solved my 403 issue connecting to the domain name, however simply trying to access the server through local IP also does not work as it claims the certificate for the server is invalid. *This* is because I forced https so I doubt it is an issue related to what we're discussing here. 

Also, since you mentioned it (and what dawned on me as soon as I sent it) I deleted the original paste link since it seemed to have served its point. Juggling this between school is definitely making me a bit careless in hopes of things just working. Thanks so much!

NPMPlus Log Entry in Question: 
```
2024/11/21 02:49:03 [error] 283615#283615: *127667 [client 174.103.109.27] ModSecurity: Access denied with code 403 (phase 2). Matched "Operator `StrEq' with parameter `0' against variable `TX:MSC_PCRE_LIMITS_EXCEEDED' (Value: `1' ) [file "/data/etc/modsecurity/modsecurity-default.conf"] [line "146"] [id "200005"] [rev ""] [msg "ModSecurity internal error flagged: TX:MSC_PCRE_LIMITS_EXCEEDED"] [data ""] [severity "0"] [ver ""] [maturity "0"] [accuracy "0"] [hostname "172.17.0.15"] [uri "/Users/7a8fef8dbe654d96af0c36c83a2c92fc/Items"] [unique_id "173215374362.578063"] [ref ""], client: 174.103.109.27, server: media.dorkbutt.lol, request: "GET /Users/7a8fef8dbe654d96af0c36c83a2c92fc/Items?fields=AirTime&fields=CanDelete&fields=CanDownload&fields=ChannelInfo&fields=Chapters&fields=ChildCount&fields=CumulativeRunTimeTicks&fields=CustomRating&fields=DateCreated&fields=DateLastMediaAdded&fields=DisplayPreferencesId&fields=Etag&fields=ExternalUrls&fields=Genres&fields=HomePageUrl&fields=ItemCounts&fields=MediaSourceCount&fields=MediaSources&fields=OriginalTitle&fields=Overview&fields=ParentId&fields=Path&fields=People&fields=PlayAccess&fields=ProductionLocations&fields=ProviderIds&fields=PrimaryImageAspectRatio&fields=RecursiveItemCount&fields=Settings&fields=ScreenshotImageTags&fields=SeriesPrimaryImage&fields=SeriesStudio&fields=SortName&fields=SpecialEpisodeNumbers&fields=Studios&fields=BasicSyncInfo&fields=SyncInfo&fields=Taglines&fields=Tags&fields=RemoteTrailers&fields=MediaStreams&fields=SeasonUserData&fields=ServiceName&fields=ThemeSongIds&fields=ThemeVideoIds&fields=ExternalEtag&fields=PresentationUniqueKey&fields=InheritedParentalRatingValue&fields=ExternalSeriesId&fields=SeriesPresentationUniqueKey&fields=DateLastRefreshed&fields=DateLastSaved&fields=RefreshState&fields=ChannelImage&fields=EnableMediaSourceDisplay&fields=Width&fields=Height&fields=ExtraIds&fields=LocalTrailerCount&fields=IsHD&fields=SpecialFeatureCount&enableUserData=true&ids=4ba9743833f7a7c203b231afb13284f5 HTTP/3.0"
```

Swiftfin Certificate Untrusted Warning:
```
Server Certificate Untrusted

GET
http://192.168.0.212:8096/System/Info/Public

URLSessionDataTask
–––––––––––––––––––––––––––––––––––––––
Host: 192.168.0.212
Date: Nov 20, 2024 at 10:24:38 PM (EST)
Duration: 346.3 ms

Error
–––––––––––––––––––––––––––––––––––––––
Domain: NSURLErrorDomain
Code: -1202 (Server Certificate Untrusted)
Description: Error Domain=NSURLErrorDomain Code=-1202 "The certificate for this server is invalid. You might be connecting to a server that is pretending to be “192.168.0.212” which could put your confidential information at risk." UserInfo={NSLocalizedRecoverySuggestion=Would you like to connect to the server anyway?, _kCFStreamErrorDomainKey=3, NSErrorPeerCertificateChainKey=(
    "<cert(0x114209500) s: media.dorkbutt.lol i: E5>",
    "<cert(0x11e220e00) s: E5 i: ISRG Root X1>"
), NSErrorClientCertificateStateKey=0, NSErrorFailingURLKey=https://192.168.0.212:8920/System/Info/Public, NSErrorFailingURLStringKey=https://192.168.0.212:8920/System/Info/Public, NSUnderlyingError=0x3012df360 {Error Domain=kCFErrorDomainCFNetwork Code=-1202 "(null)" UserInfo={_kCFStreamPropertySSLClientCertificateState=0, kCFStreamPropertySSLPeerTrust=<SecTrustRef: 0x302b5b180>, _kCFNetworkCFStreamSSLErrorOriginalValue=-9843, _kCFStreamErrorDomainKey=3, _kCFStreamErrorCodeKey=-9843, kCFStreamPropertySSLPeerCertificates=(
    "<cert(0x114209500) s: media.dorkbutt.lol i: E5>",
    "<cert(0x11e220e00) s: E5 i: ISRG Root X1>"
)}}, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalDataTask <10C2A01F-D8FC-466A-920A-B15C7B0F2429>.<1>"
), _kCFStreamErrorCodeKey=-9843, _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <10C2A01F-D8FC-466A-920A-B15C7B0F2429>.<1>, NSURLErrorFailingURLPeerTrustErrorKey=<SecTrustRef: 0x302b5b180>, NSLocalizedDescription=The certificate for this server is invalid. You might be connecting to a server that is pretending to be “192.168.0.212” which could put your confidential information at risk.}

Request Headers (3)
–––––––––––––––––––––––––––––––––––––––
Accept: application/json
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.9

Request Body
–––––––––––––––––––––––––––––––––––––––
–

Response Body
–––––––––––––––––––––––––––––––––––––––
–
```

**Comment by JPKribs** [comment]
No worries! Happy to hear you found the configuration to make this work!
