### ISSUE TITLE
tvOS - Super Choppy Scrolling and Posters clumped together

### ISSUE THREAD

**Issue by Piermaria** [jellyfin/Swiftfin#1324]
### Describe the bug

As per title scrolling the movie gallery is very choppy and quite slow. Also posters clump together at the bottom of the screen while scrolling vertically in the gallery.![Image](https://github.com/user-attachments/assets/da5ebaef-f35c-42f2-8a0c-221c24545fb4)

### Application version

1.0.1(70)

### Where did you install the app from?

AppStore

### Device information

AppleTV 4K

### OS version

tvOS18.1

### Jellyfin server version

Latest Stable

**Comment by Simonh2o** [comment]
Experiencing the same issue when scrolling, the items are stacked on top of eachother for a few seconds before being re-ordered once you stop scrolling.

**Comment by Piermaria** [comment]
Hi Simon,

In my case once I stop scrolling, the items remain stacked.

Thanks
