### ISSUE TITLE
Display Movie Rating

### ISSUE THREAD

**Issue by foorschtbar** [jellyfin/Swiftfin#1335]
**Describe the feature you'd like**

I miss the rating of movies in the app. In the WebUI I could see it, but the App shows only Audio, Subtitle and other information on the poster, but no information about the rating.

**Additional context**

(WebUI)
![image](https://github.com/user-attachments/assets/b5d6470c-ef8e-4f77-8c77-fecd21eed6a6)

(App)
![image](https://github.com/user-attachments/assets/ee5a6868-61b3-43a7-95a5-9592a6e217f8)

**Comment by JPKribs** [comment]
If you scroll to the bottom of the Item page, Ratings are in the “About Section.”

**Comment by foorschtbar** [comment]
> If you scroll to the bottom of the Item page, Ratings are in the “About Section.”

Oh! Thank u. I wouldn't have thought of looking for it there.

Then I'll close the issue here and open a feature request to add the rating to the poster.
