### ISSUE TITLE
Can't Play a Movie but only Trailers

### ISSUE THREAD

**Issue by FancyNerd92** [jellyfin/Swiftfin#134]
Can't play a movie but only the trailers of them. I don't have a problem with other Jellyfin players but from my iPhone X i can't watch any movie in my LAN Network... Any ideas?

**Comment by LePips** [comment]
Do you have trailers for the movies within your Jellyfin media? Does this only happen when both the server and phone are on the same network?

**Comment by acvigue** [comment]
SwiftFin doesn't include support for trailers. Are you sure it's not the opposite issue.

**Comment by FancyNerd92** [comment]
Yes im sure. My media are x265, 4K HDR, TRUE HD 7.1 or DTS.... and i thik is an issue with audio and x265 format... because my trailers are x264, 1080p, ACC

**Comment by LePips** [comment]
How are the trailers stored alongside your movies? Sorry, I've never used trailers.

I'm thinking this may be an issue with the Jellyfin SDK getting media from the server or how we handle media received from the server, I'm not sure.

**Comment by LePips** [comment]
Stale.
