### ISSUE TITLE
ipa file for tvOS

### ISSUE THREAD

**Issue by ptfuzi** [jellyfin/Swiftfin#1344]
Hi, 
How can I get the file to sideload into my appleTV?

Version on AppStore seems outdated compared to the  phone version.

Couldn’t file info on how to get the file, also don’t have Xcode

**Comment by jannislehmann** [comment]
The tvOS app is still being updated and rebuild. You can follow the status [here](https://github.com/jellyfin/Swiftfin/discussions/1294).

**Comment by JPKribs** [comment]
@jannislehmann is absolutely correct that this is where we are tracking our next update. We hope to have a TestFlight as soon as it's ready, at which time you can sign up for our TestFlight here: https://testflight.apple.com/join/SqNPfdxq

We do not provide an IPA outside of the App Store or TestFlight.

If you're interested in contribution to Swiftfin, you can see the steps to set up your environment below. However, XCode is required.
https://github.com/jellyfin/Swiftfin/blob/main/Documentation/contributing.md
