### ISSUE TITLE
Not Accepting Self-Signed HTTPS Cerificate

### ISSUE THREAD

**Issue by dcjulian29** [jellyfin/Swiftfin#1370]
### Describe the bug

Attempting to connect to my local server, swiftfin refuses to accept the self-signed certificate and there is no way to accept it

### Application version

Latest

### Where did you install the app from?

App Store

### Device information

iPad pro

### OS version

18

### Jellyfin server version

10.10.3

**Comment by LePips** [comment]
Please see #379.
