### ISSUE TITLE
overhaul video controls ui

### ISSUE THREAD

**Issue by oatmealm** [jellyfin/Swiftfin#139]
**Describe the feature you'd like**

Make the skip control UI less obtrusive and precise. 

**Additional context**

Right now the forward/backward skip controls, which are overlaid on the video, appear and disappear on every touch because of the message "loading" that pops up. 

It's very disruptive but also seem make it difficult to asses how far you've progressed, since the video preview doesn't update to reflect the current position. So you end up skipping too far.

**Comment by acvigue** [comment]
>It's very disruptive but also seem make it difficult to asses how far you've progressed, since the video preview doesn't update to reflect the current position. So you end up skipping too far.

how are we supposed to do this without thumbnails.

**Comment by LePips** [comment]
I believe this can be closed because of:
https://github.com/jellyfin/Swiftfin/pull/152
https://github.com/jellyfin/Swiftfin/pull/149

**Comment by LePips** [comment]
I will put this with: https://github.com/jellyfin/Swiftfin/pull/157
