### ISSUE TITLE
Testflight App for tvOS

### ISSUE THREAD

**Issue by raoulk** [jellyfin/Swiftfin#142]
I successfully installed your Testflight App on iOS/iPadOS.
But in my AppleTV's Testflight, there is no Swiftfin App.

Am I too stupid, or is there currently only the iOS App available?

Disclaimer
I'm got my AppleTV only a few weeks ago and am still kind of a newbie.
But I successfully installed https://github.com/ABJC/ABJC-tvOS via Testflight.

**Comment by acvigue** [comment]
<img width="833" alt="Screen Shot 2021-08-15 at 1 39 47 PM" src="https://user-images.githubusercontent.com/34462061/129487364-8cad4f30-b570-4607-a1d2-38987a3100bc.png">
