### ISSUE TITLE
Cannot use jump buttons while video is paused

### ISSUE THREAD

**Issue by winterqt** [jellyfin/Swiftfin#147]
### Describe the bug

1. Pause a video
2. Attempt to use the jump buttons

Expected behavior: for them to work(?)
Actual behavior: nothing happens

The check for if the video is paused was added with the initial implementation of the jump buttons in https://github.com/jellyfin/Swiftfin/commit/198516b8a96469ba88554626ced3535da2017125, so I'm not sure if this is a technical limitation, or a design choice, or what, but it threw me off a bit. If it was a design choice, then feel free to close this.

### Application version

1.0.0 (59)

### Where did you install the app from?

TestFlight

### Device information

iPhone 12

### OS version

iOS 15 beta 5

### Jellyfin server version

10.7.6

**Comment by LePips** [comment]
I agree that the UX should be that jumping forward/backward is allowed while paused.

After playing with the video player for a little bit, we _might_ just have to change the behavior of changing the state of the video player. 

Might be tedious but will be better in the long run. Low priority because of this imo.

**Comment by LePips** [comment]
I will put this with: https://github.com/jellyfin/Swiftfin/pull/157

**Comment by LePips** [comment]
Limitation of VLCKit but comment says it should be fixed in 4.0

https://code.videolan.org/videolan/VLCKit/-/issues/452

**Comment by LePips** [comment]
I'm going to close this as we have to wait for VLCKit v4 for this fix. The release will not be missed and will have a special announcement.
