### ISSUE TITLE
Default filters are inconsistent

### ISSUE THREAD

**Issue by winterqt** [jellyfin/Swiftfin#148]
### Describe the bug

To reproduce:
1. Open a library view
2. Observe the active filters
3. Reset the filters
4. Observe the active filters

When initially opening the library view, the filters are:
- Sort by date added
- Display order: descending

However, when pressing reset, the filters are:
- Sort by name
- Display order: ascending

The default filters when opening a view should be the same as they currently are when you press reset. These are also the default display filters used by the other Jellyfin clients.

### Application version

1.0.0 (59)

### Where did you install the app from?

TestFlight

### Device information

iPhone 12

### OS version

iOS 15 beta 5

### Jellyfin server version

10.7.6

**Comment by acvigue** [comment]
Opening the library view from the home screen (i.e. latest items, the see all button) is intended to pull items in descending order by date added.

**Comment by winterqt** [comment]
> Opening the library view from the home screen (i.e. latest items, the see all button) is intended to pull items in descending order by date added.

Got it, then there's no issue here. Apologies.

**Comment by acvigue** [comment]
No problem!
