### ISSUE TITLE
Open Discussion - Contribution Guidelines

### ISSUE THREAD

**Issue by LePips** [jellyfin/Swiftfin#156]
Open discussion for what should be part of Contribution Guidelines for this project. These should be general ideas as specifics can be discussed in their own Issue/thread when the docs are actually being written.

**Comment by LePips** [comment]
Starting off, some of mine include:

**Git Flow**

**Comment by stevebyatt10** [comment]
>   Attach work to an Issue. Or, if given permission, we can expand usage of the _Projects_ section to track work done by people (which I prefer so that Issues is solely for Feature requests, bugs, or discussions)

I think this is a good idea especially with more people contributing, or Draft PR's, just to see what is currently being worked on and what not.

**Comment by LePips** [comment]
Hey everyone,

I've started drafting the Contribution Guidelines in a markdown file at my repo: https://github.com/LePips/markdown-sandbox

It's a work in process at the moment and will ping this issue again once I feel like it's in a good spot to be "approved" and moved over into the `Wiki` section of this repo and properly formatted there. Don't be afraid to comment on what I have written and fork/make a PR if you would like to.
