### ISSUE TITLE
Next Episode Button in the Middle of the Screen on iPad

### ISSUE THREAD

**Issue by f1yankees** [jellyfin/Swiftfin#158]
### Describe the bug

When approaching the end of an episode, the Next Episode button appears in the middle of the screen at about ~5min to go, obstructing the view.

### Application version

60

### Where did you install the app from?

TestFlight

### Device information

iPad Pro 

### OS version

iPad OS 14.7.1

### Jellyfin server version

10.7.6

**Comment by LePips** [comment]
https://github.com/jellyfin/Swiftfin/pull/162

**Comment by acvigue** [comment]
Thanks!

**Comment by LePips** [comment]
The work for this was merged and will be in the next Testflight build. Closing.
