### ISSUE TITLE
Support for “other” library type

### ISSUE THREAD

**Issue by kdoubledubs** [jellyfin/Swiftfin#159]
I have a mixed content library set as “other” to display my short film library which includes both tv show and movie content. These libraries do not display in the app.

**Comment by charleypeng** [comment]
yeah, i think this function is also needed , because when I download some short video clips for later watch, those clips can not be seen except the "Index" column

**Comment by acvigue** [comment]
a pr is welcome.

**Comment by LePips** [comment]
I will also be restructuring how media is handled throughout the app, I can include that in that work when I get to it. It might be this weekend cause I have time
