### ISSUE TITLE
.STRM compatibility/playback request

### ISSUE THREAD

**Issue by eqpaisley** [jellyfin/Swiftfin#160]
**Describe the feature you'd like**
Would like to be able to play .strm files via Swiftfin

**Additional context**

**Comment by LePips** [comment]
Closing as if it isn't supported by VLCKit, then there's nothing we can do and it should be transcoded.

**Comment by pythcon** [comment]
Why was this issue closed out? Aren't strm files supported by VLCKit? @LePips

**Comment by LePips** [comment]
This issue was closed because it isn't naturally supported. However after this I was in conversation with somebody to have .strm file support but this is right at the bottom of my list.
