### ISSUE TITLE
[tvOS] Clicking/scrolling down on the Home tab takes you to the All Media tab

### ISSUE THREAD

**Issue by dkindt** [jellyfin/Swiftfin#164]
After signing into the app, the all media tab only displays the text "Library."

When I scroll to the Home tab, I see media from my server. However, when I attempt to scroll down, I'm redirected to the All Media tab.

At this point, when I scroll back to the left, the All Media tab remains highlighted (with the text now being white).

I've tried using two remotes -- the physical Apple TV remote, and the Apple TV remote on my iPhone. Both yield the same result.

**Comment by LePips** [comment]
This is mainly because the tvOS app hasn't been developed to that point

**Comment by dkindt** [comment]
I believe this is the line causing the problem: https://github.com/jellyfin/Swiftfin/blob/main/JellyfinPlayer%20tvOS/MainTabView.swift#L49 .

Should line 49 be: `.tag(Tab.home)` instead of `.tag(Tab.allMedia)`?

**Comment by dkindt** [comment]
@LePips I updated the title to align with what I was actually trying to report

**Comment by gregcsw** [comment]
Just updated to tvos 15 and now the Home tab functions as expected. 

The All Media tab still only displays the word Library.
