### ISSUE TITLE
[iOS] Blank pages

### ISSUE THREAD

**Issue by sambartik** [jellyfin/Swiftfin#167]
Hey, the "Home" and "All media" panels are all blank after exiting the app from the app switcher. However, when I go to settings it still says "Signed in as x". The only temporary solution is to sign out and login again.

Before exiting the app everything was displaying correctly.

# Steps to reproduce:
- Open Jellyfin app.
- Sign in to a Jellyfin account
- Close the app via app switcher
- Open Jellyfin app once more.

# Additional info:
- Swiftfin testflight build: 1.0.0 (60)
- iOS version: dev beta 8 iOS 15.0 (19A5340a)
- Jellyfin version: 10.7.7
- Jellyfin URL: https://192.168.1.x/jellyfin/

# Pictures
![Home](https://user-images.githubusercontent.com/63553146/132979237-3129746a-891c-4f25-9821-18cccff8cbba.png)

![All media](https://user-images.githubusercontent.com/63553146/132979241-2ec713f6-d1e3-4cc2-ad8c-93bbd2cf620c.png)

**Comment by LePips** [comment]
This happens because network calls are failing and we don't have error messages on those pages. This is part of some network refactoring I am doing right now.

**Comment by sambartik** [comment]
I have found out that this was related to an issue where my jellyfin server informations changed after closing the app and thus failed to connect to server afterwards. Even if I logged out and then logged in, info was correct only until I closed the app again. 

Reinstalling swiftin resolved my issue.

**Comment by icyphox** [comment]
I'm facing this exact issue. I've tried logging out/logging in, reinstalling, etc. but to no avail. The UI is blank.

**Comment by LePips** [comment]
Yeah, guess I'll re-open since error messages aren't implemented on the home and library page

**Comment by dotnetdan** [comment]
I just installed the app and all I see is blank pages in Home and All Media. But I'm able to connect to my server from the ios client that's available on the official app store (am I right that Swiftfin is a separate from that application? I didn't see an ios client repo anywhere)
