### ISSUE TITLE
REGRESSION: Swiftfin doesn't switch between x264 audio or sub tracks, other players do

### ISSUE THREAD

**Issue by sambhavsaggi** [jellyfin/Swiftfin#168]
### Describe the bug

Streaming x264 video works, but if it has multiple audio tracks, Swiftfin refuses to switch between them.

1. Upload a mkv x264 with multiple audio tracks, rescan, etc
2. Use jellyfin desktop and verify switching audio tracks work
3. Swiftfin doesn't change audio tracks

### Application version

1.0.0(60)

### Where did you install the app from?

TestFlight

### Device information

iPhone 6s

### OS version

iOS 14.8

### Jellyfin server version

10.7.7.0

**Comment by sambhavsaggi** [comment]
This is a regression from 1.0.0(59) in which the system was working.

**Comment by acvigue** [comment]
this may have something to do with video player rewrite.

**Comment by LePips** [comment]
My current work hasn't touched anything with this but I have also observed this bug with my anime. I can address this with my refactoring.

**Comment by sambhavsaggi** [comment]
Seems like HEVC embedded subtitles in MKVs aren't detected either (TestFlight 66, iOS 15.1)
