### ISSUE TITLE
Unable to use TV remote to control Chromecast playback

### ISSUE THREAD

**Issue by edenman** [jellyfin/Swiftfin#177]
### Describe the bug

1. Click on a video
2. Press play
3. Press Chromecast button, select device
4. Try to pause video with the TV's remote, nothing happens.

Motivation: I usually start playing media from my phone but then use the TV remote to control playback/volume/etc so I don't have to keep the media player app up on my phone. FWIW this workflow works great on Emby.  I've got no idea how the Chromecast implementations differ but this would be great to fix.   I'm also new to Jellyfin so let me know if this is something I should file in a different project, I don't see much chromecast code in this app.  Should this go in https://github.com/jellyfin/jellyfin-chromecast instead?

### Application version

1.0.0 (64)

### Where did you install the app from?

TestFlight

### Device information

iPhone 13 mini

### OS version

iOS 15.0.1

### Jellyfin server version

10.7.7

**Comment by LePips** [comment]
Per your concerns about placement, this belongs here.

I don't think we're consuming the events from casted stream to pause/play/everything else. I'll take a look in my video player refactor.

**Comment by LePips** [comment]
Since Chromecast was regressed out, I will close this and it is marked in the main Chromecast issue as a capability requirement.
