### ISSUE TITLE
iPad Enhancements

### ISSUE THREAD

**Issue by harryofbath** [jellyfin/Swiftfin#186]
**Describe the feature you'd like**
Support for playing back 4:3 content in full screen. Picture in Picture support. Multitasking support. Keyboard shortcuts - spacebar to play/pause, arrow keys for scrubbing etc.

**Additional context**
The ability to zoom in/out, allowing for 4:3 or native aspect ratio.

**Comment by LePips** [comment]
A lot of this is part of my video player refactor like the aspect ratio.
PIP is part of it too where I want to implement the native video player and it automatically gives us PIP.

Multitasking support is something we can look at that wouldn't take too much time, whereas keyboard shortcuts for navigating the app (on top of inside the video player) would take longer.

**Comment by LePips** [comment]
I will close this soon with specific tasks that are possible. Aspect fill isn't possible sadly but the keyboard navigation is. PiP and Multitasking are part of larger features

**Comment by LePips** [comment]
Closing this now as either they are now implemented, yet to be merged, or other specific issues have been created detailing implementation. However, PiP won't be implemented for a very long time due to a lot of view handling we would have to handle.

**Comment by harryofbath** [comment]
Been looking over the VLCKit documentation, and wouldn't `fillScreen` fix the aspect ratio? Maybe I'm mis-interpreting the docs, but I think it should be possible, considering the official VLC app is fully capable of it. It's referenced in both VLCVideoView and VLCVideoLayer. Of course I have no idea how it would be implemented, but if you think it would be possible, I would greatly appreciate it.

**Comment by LePips** [comment]
No, as it doesn't do what you think it does. That's a custom property in the sample applications they provide, not an actual implementation in VLCKit.

The iOS VLC app does have aspect fill and works by increasing the scale of the video buffer from VLCKit, as seen here: https://code.videolan.org/videolan/vlc-ios/-/blob/master/Sources/VLCPlaybackService.m#L929. It also has no animation.

I do something similar here https://github.com/jellyfin/Swiftfin/pull/315 where I scale the _rendering view_ that VLCKit renders to with a nice little animation.

**Comment by harryofbath** [comment]
Ah cool, didn't see that. Thanks for all your hard work.
