### ISSUE TITLE
tvOS - Navigation Problems

### ISSUE THREAD

**Issue by wormuths** [jellyfin/Swiftfin#201]
### Describe the bug

Just generally, navigation seems worse on 1.0.0 (66).  I know it's a work in progress, so this is just a general placeholder for navigation issues in different places.

I have found in many places that the back button doesn't operate as expected.  For example, instead of backing out of a television season, it will take you out of the app entirely.  I found several times where I had to log out and back in just to return to the main home page.

The interface is looking up though.  Thanks for all the work...

### Application version

1.0.0 (66)

### Where did you install the app from?

TestFlight

### Device information

Apple TV 4K

### OS version

tvOS 15

### Jellyfin server version

10.7.7

**Comment by nikhil96widhani** [comment]
I can confirm this happens on my 4k apple tv

**Comment by LePips** [comment]
After further development, this isn't because of a navigation issue but the app crashing when exiting the player.
