### ISSUE TITLE
Home Screen "Latest" Context / Home Screen Improvements

### ISSUE THREAD

**Issue by Jinxyface** [jellyfin/Swiftfin#203]
I believe this was fixed before, but it must have came back with a recent update. For example, on my browser, my newest TV episodes:

![image](https://user-images.githubusercontent.com/19889486/138627911-9bc32393-b4ef-4e57-904a-5fd9464a54a3.png)

However, on the iOS app, it doesn't show the newest episodes of my TV series, but rather just the latest (newest) series that has been added:

![photo_2021-10-24_21-56-35](https://user-images.githubusercontent.com/19889486/138628117-e2d455e1-b9c7-40d5-9735-cebe95eaa274.jpg)

But when I do manual searches, the newest episodes have been added:

![photo_2021-10-24_21-56-39](https://user-images.githubusercontent.com/19889486/138628137-965200a0-2375-49ca-8f31-6d7613c985f6.jpg)

Not really a bad breaking issue or anything, just feel like it's a consistency issue that would make for a more polished experience.

let me know if there's any other info I can provide.

**Comment by LePips** [comment]
I believe the main issue reported here was fixed by #895.
