### ISSUE TITLE
iOS - Bottom Tab Taps

### ISSUE THREAD

**Issue by cheetashock** [jellyfin/Swiftfin#209]
Tapping on bottom tabs (Home, All Media) should take you to the main page for that tab.

**Comment by LePips** [comment]
Developer note: May need to ping the Stinsen project about this

**Comment by PangMo5** [comment]
When I checked in the past, the function did not work on Pure `TabView` in `SwiftUI`.

I don't understand why it's not supported as a basic function. lol

**Comment by LePips** [comment]
Tracked issue in Stinsen: https://github.com/rundfunk47/stinsen/issues/40

This will take a while.

**Comment by LePips** [comment]
I'm going to close this as this is something we can't actually do. Going to have to wait for SwiftUI to mature.
