### ISSUE TITLE
macOS - Adjust UI for macOS Screen

### ISSUE THREAD

**Issue by f1yankees** [jellyfin/Swiftfin#214]
Logging this so people know Swiftfin works on macOS with Apple Silicon chips

Adjust the UI bounds with the latest Human Interface Guidelines from Apple.  May also need to select different deployment settings.

Potentially helpful: https://developer.apple.com/forums/thread/652276

**Comment by LePips** [comment]
Swiftfin working on Mac right now is just a fun coincidence we found out because it's also on the Mac TestFlight, which @acvigue should look at removing. We are not building Swiftfin for Mac at the moment and will not take any issues for it.

**Comment by acvigue** [comment]
LOL i thought i had it removed :p
