### ISSUE TITLE
Clean up dependencies for native M1 Xcode

### ISSUE THREAD

**Issue by LePips** [jellyfin/Swiftfin#217]
Dependencies need to be cleaned up in order to use Xcode natively on M1 Macs.

Issues come from `google-cast-sdk` and `Puppy`. We may just need to replace `Puppy` as our logging entirely.

**Comment by bestlem** [comment]
What can be done about google-case-sdk?

**Comment by LePips** [comment]
For google-cast arm64 has to be an ignored architecture for the Debug target but Puppy has to be built in arm64, which is why we need to replace it in order to set the right flags

**Comment by LePips** [comment]
Follow this issue for when this can be done: https://stackoverflow.com/questions/70574070/google-cast-sdk-not-working-in-apple-m1-pro-chipset/70618073
