### ISSUE TITLE
Default Sort order

### ISSUE THREAD

**Issue by LeviSnoot** [jellyfin/Swiftfin#22]
Right now when you open a library it sorts the titles Z-A by default. Would be preferred to sort A-Z. Or at least if it remembered your sort preference.

![image](https://user-images.githubusercontent.com/13402525/120050311-3f172c80-c01d-11eb-98ea-ca8b0928e1b3.png)

**Comment by acvigue** [comment]
Yep. It should be A-Z. Thanks for catching that!

**Comment by acvigue** [comment]
Fixed in next build
