### ISSUE TITLE
The player does not support TLS1.3.

### ISSUE THREAD

**Issue by zhangguojvn** [jellyfin/Swiftfin#232]
### Describe the bug

When my nginx only enable tls1.3, the video cannot be played (It always loading). 
When I allow tls1.2 on my server, I can play the video.

### Application version

1.0.0(66)

### Where did you install the app from?

TestFlight

### Device information

iPhone 12

### OS version

iOS 15

### Jellyfin server version

10.7.7

**Comment by LePips** [comment]
Can you please supply Jellyfin logs?

**Comment by zhangguojvn** [comment]
This is nginx log
access_log
`192.168.0.31 - - [18/Nov/2021:12:56:49 +0800] "POST /jellyfin/Sessions/Playing HTTP/2.0" 204 0 "-" "JellyfinPlayer%20iOS/66 CFNetwork/1312 Darwin/21.0.0"
192.168.0.31 - - [18/Nov/2021:12:56:50 +0800] "POST /jellyfin/Sessions/Playing HTTP/2.0" 204 0 "-" "JellyfinPlayer%20iOS/66 CFNetwork/1312 Darwin/21.0.0" `

error_log
`2021/11/18 12:58:53 [info] 2858#0: *41445 SSL_do_handshake() failed (SSL: error:14209102:SSL routines:tls_early_post_process_client_hello:unsupported protocol) while SSL handshaking, client: 192.168.0.31, server: 0.0.0.0:443
2021/11/18 12:58:54 [info] 2858#0: *41449 SSL_do_handshake() failed (SSL: error:14209102:SSL routines:tls_early_post_process_client_hello:unsupported protocol) while SSL handshaking, client: 192.168.0.31, server: 0.0.0.0:443
2021/11/18 12:58:54 [info] 2858#0: *41450 SSL_do_handshake() failed (SSL: error:14209102:SSL routines:tls_early_post_process_client_hello:unsupported protocol) while SSL handshaking, client: 192.168.0.31, server: 0.0.0.0:443 `

Jellyfin has no errors in the log.
It seem like VLC don’t support tls1.3.

**Comment by LePips** [comment]
This actually seems like a profile issue on our side? Idk, TLS 1.3 should be automatically enabled for us. This isn't a VLC issue

https://superuser.com/questions/1217220/how-do-i-enable-tls-1-3-in-ios-and-macos

**Comment by acvigue** [comment]
iOS supports TLS 1.3, but it is not enabled by default. App Transport Security requires that servers support TLS 1.2 as there is not yet a way to enable TLS 1.3 on a per-app basis by modifying ATS settings. You must install the provisioning profile from the Apple Developer web site to enable TLS 1.3

**Comment by higbee4** [comment]
I think this might need another look. It looks like TLS 1.3 was enabled by default starting with iOS 12.2. https://support.apple.com/guide/security/tls-security-sec100a75d12/web

With the release of iOS 15 apple officially deprecated TLS 1.0 and 1.1. They also recommended supporting  the use of 1.3 in addition to 1.2.

My reverse proxy has the min version set to 1.3 and all the other services behind it work fine on iOS, implying 1.3 works fine. But this app doesn’t work unless I enable 1.2.

**Comment by LePips** [comment]
Sorry, I've been meaning to and forgot. I'll get to this

**Comment by LePips** [comment]
I've read up and reached out to peers about this so actually if the problem comes from being unable to load a video but you can connect to your server/navigate just fine, then the problem actually does come from VLCKit unlike I originally thought.

There aren't any issues related to TLS 1.3 in VLCKit's repo but there's absolutely nothing that we can do on our end about this.

**Comment by thgoebel** [comment]
For reference: https://code.videolan.org/videolan/VLCKit/-/issues/595
