### ISSUE TITLE
Frequent crashes

### ISSUE THREAD

**Issue by hotsno** [jellyfin/Swiftfin#238]
### Describe the bug

The app crashes very frequently. From what I've seen so far it's crashed when pressing play to start playing a video, as well as pressing the back button while in the video player. It seems to be random, sometimes a video will cause a crash, other times the same video will play. It crashes most of the time though.

I'm new to iOS so I'd appreciate some help on how to send logs, if possible and necessary.

### Application version

1.0.0 (66)

### Where did you install the app from?

TestFlight

### Device information

iPhone 13

### OS version

15.0.2

### Jellyfin server version

10.7.7

**Comment by LePips** [comment]
Whenever the app crashes it will ask you to send logs via TestFlight, just say yes and we will get the crash logs through there.

**Comment by hotsno** [comment]
All right, I think I did it once before making the bug report and did it two more times just now

**Comment by LePips** [comment]
I've been playing around with lots of different types of media and have narrowed down what types of media cause crashes. Are you experiencing these crashes while trying to use `ass` subtitles?

**Comment by LePips** [comment]
Gonna close as the behavior will be documented that causes these crashes
