### ISSUE TITLE
Movie Version Implementation

### ISSUE THREAD

**Issue by cheetashock** [jellyfin/Swiftfin#240]
Integrate the movie version feature built in to Jellyfin.

**Comment by LePips** [comment]
Hello, what do you exactly mean by movie "version"?

**Comment by cheetashock** [comment]
In the regular Jellyfin app and web you can select with version of movie you would like (Director's Cut, Different Resolutions, etc) before watching. Here's the requirements for naming the different files.

[https://jellyfin.org/docs/general/server/media/movies.html](https://jellyfin.org/docs/general/server/media/movies.html)

**Comment by LePips** [comment]
Oh yes, that stuff. Thank you
