### ISSUE TITLE
[iOS] ASS Subtitles not displayed

### ISSUE THREAD

**Issue by oxixes** [jellyfin/Swiftfin#242]
### Describe the bug

When I watch a show and I enable subtitles, they are not displayed at all. The subtitle format is ASS. I solve this issue in the App Store app by forcing them to be burned into the video, but there is not an option for it in this app.

### Application version

1.0.0 (66)

### Where did you install the app from?

TestFlight

### Device information

iPad Pro (11 inch) (2º gen)

### OS version

iPadOS 15.0.2

### Jellyfin server version

10.7.7

**Comment by sambhavsaggi** [comment]
Related: #168

**Comment by oxixes** [comment]
Closed with merge of #250.

**Comment by LePips** [comment]
So it's okay that this is closed (as the task to embed ass subtitles is part of something larger) but only sometimes will ass subtitles show (depending on the track) and it will sometimes cause the app to crash when exiting the player or when attempting to switch to a track. It's a crash in VLCKit and I believe it happens with unsupported fonts.

**Comment by oxixes** [comment]
Well, I have experienced what you said with the latest version of the app (I compiled the master branch), but I decided to close this issue as the subtitles are already displayed (although they make the app crash in many cases, as you said) and decided to wait for the next TestFlight release to create a new issue for this in case some fixes are added before it. I will also try to experiment a bit more what kind of ass subtitles (with and without custom fonts) make the app crash. Thanks for your work anyways.

**Comment by LePips** [comment]
That's awesome, thanks. I already know what I need to do in order to fully support ass subtitles by embedding them in the stream, so I don't want you to go through the trouble of figuring out what fonts are/aren't supported as there isn't anything we can do with that.

**Comment by oxixes** [comment]
Thanks! I was going to try anyways as I have a similar issue with other clients (it seems that ASS subtitles are very problematic, in the end I’ll probably change them to VTT or SRT as they seem to have less problems, and I already have a script to do that).

**Comment by LePips** [comment]
Ooh if you could share that script with me, that'd be great as I have many animes I'd like to convert

**Comment by oxixes** [comment]
Sorry for the delay, It was very late in my country yesterday and I have been busy.
Sure, I created [a gist](https://gist.github.com/oxixes/ab1018b80a6812cc45fa4870eb208da7) with the script and a readme (I also added a fix for duplicated dialogues that happened with some effects in ASS).
