### ISSUE TITLE
Overflow on page when viewing a movie or show

### ISSUE THREAD

**Issue by haykkh** [jellyfin/Swiftfin#249]
Apologies if this issue has been brought up before, I couldn't find it.

### Describe the bug

Go to any episode or show and the left and right sides of the page will be cut off

https://user-images.githubusercontent.com/5832225/147590862-a8d0ef71-2ee4-4179-9d75-a49faa8465b6.MP4

It's usually not a fully problematic bug as you can still tap `play` on most pages, but on some (like some episodes of Leonardo from my attached video) so much of the page is cut off that you can't tap on `play`.

### Application version

1.0.0 (66)

### Where did you install the app from?

TestFlight

### Device information

iPad Pro (12.9-inch) (2nd generation), iPad Pro (12.9-inch) (3rd generation)

### OS version

iPadOS 15.2

### Jellyfin server version

10.7.7

**Comment by PangMo5** [comment]
It seems to be a problem solved in the #222 
But it has not been uploaded to the testlight yet.
If it is uploaded, I will close the issue after checking it.

**Comment by haykkh** [comment]
Ah that's it yes! thanks a lot

**Comment by haykkh** [comment]
Fixed in build (67). Thanks again everybody!
