### ISSUE TITLE
Cursor disappears on tvOS settings page

### ISSUE THREAD

**Issue by jorritolthuis** [jellyfin/Swiftfin#263]
### Describe the bug

1. Connect a server
2. Go to the settings tab
3. Go down one step
4. Notice that nothing is highlighted 
5. Go down another step
6. Notice that 'server' is highlighted

This seems to indicate that the cursor is hidden at 'user'. However, because the user cannot interact with this user entry, it does not make sense to have the cursor interact with it.

### Application version

6386bc9

### Device information

Apple TV 4K Gen 1

### OS version

tvOS 15.1.1 (19J581)

### Jellyfin server version

10.7.7

**Comment by LePips** [comment]
Thanks for your PR, I'll actually make the user row a button (with no action) and that will give us a visual indicator when it's focused. It needs to be able to be focused so that the form can be scrolled correctly

**Comment by jorritolthuis** [comment]
Thanks, that would also fix my confusion.
