### ISSUE TITLE
Release swiftfin in IPA.

### ISSUE THREAD

**Issue by vegedb** [jellyfin/Swiftfin#268]
**Describe the feature you'd like**
Please release an IPA for switftfin.

**Additional context**
TestFlight requires the latest IOS to be used. An ipa can be easily sideloaded to test without updating.

**Comment by LePips** [comment]
This isn't an issue of Testflight, we manually have it as iOS 15 being the minimum requirement.

**Comment by vegedb** [comment]
> This isn't an issue of Testflight, we manually have it as iOS 15 being the minimum requirement.

Yes there's iterations of iOS 15 and that's what I'm talking about. TestFlight simply requires the latest.

Its fine to make an IPA that requires ios 15. As jellyfin is mostly a foss/self hosted project, it should have an option to have an .ipa tbh.

**Comment by vegedb** [comment]
Just a notification **Bump** made edits, hope you read it.

**Comment by LePips** [comment]
I know what ipa's are and thank you for showing your use case as I preemtively closed. I will have to discuss this to provide the releases and who will handle them. Automated releases may not happen.

As a clarifying note, TestFlight also doesn't require updating to the latest minor versions of iOS, proof is that I'm still on `15.1` with `15.2` being out. It also isn't necessarily good to compare applications that are completely different.

**Comment by vegedb** [comment]
> I know what ipa's are and thank you for showing your use case as I preemtively closed.

Thanks for reopening it! 

Another GREAT example for you and others to know is https://github.com/qnblackcat/uYouPlus/releases

Hope to have it available to sideload soon!

**Comment by LePips** [comment]
I'm going to close this as we will soon provide the next build as an ipa (after 69) and plan to be consistent afterwards.
