### ISSUE TITLE
tvOS playback with server in different subnet broken

### ISSUE THREAD

**Issue by hendrik1120** [jellyfin/Swiftfin#272]
### Describe the bug

instant feedback report:
first of all, thanks @LePips for the new player. Works great on iOS!

tvOS on the other hand after clicking the "Play" Button on any movie in the library simply just shows a black screen with the new player at the bottom.
It also doesn't spin up any disks on my server for the playback.

I build the app beforehand using Xcode on my AppleTV and I simply thought that I probably did something wrong :D
If you need more info pls let me know.

### Application version

1.0.0(68)

### Where did you install the app from?

TestFlight

### Device information

AppleTV 4k

### OS version

tvOS 15.2

### Jellyfin server version

10.7.7

**Comment by LePips** [comment]
You say you built from Xcode so is this the dev version or the Testflight version?

**Comment by hendrik1120** [comment]
both, Xcode and TestFlight

**Comment by LePips** [comment]
I'm able to play on both, would you mind trying through the "Cinematic" views (currently toggle-able in the settings) and see if that fixes it? I didn't touch the old views and how it handles playback but those will soon be re-done

**Comment by hendrik1120** [comment]
No difference using the Cinematic Views. Playback on version 66 worked and on my iPhone it works too. I use an AppleTV 4k, the old version. Maybe that's the problem.

**Comment by LePips** [comment]
Hm maybe it's attempted to be transcoded as transcoding is currently not implemented.

**Comment by LePips** [comment]
Transcoding was actually removed because I was unable to test with it, I should be able to re-implement it tonight (trivial) and then I'd ask that you try with the Xcode version on whatever PR I have

**Comment by hendrik1120** [comment]
I am not sure about when Jellyfin tries to transcode but I tested h.264 and h.265 in 1080p and 4k in both mkv and mp4 and nothing plays. Usually it can direct stream these formats

**Comment by LePips** [comment]
Yes that is interesting as those should be fine. I'll try a couple things that should narrow down the issue

**Comment by hendrik1120** [comment]
The only thing that I can think of is that because I got the Jellyfin Server setup in a different subnet it might break. But it works on iOS and the previous versions worked as well. 
Btw I can only build for tvOS because I haven't jet figured out how to fix the google-cast-sdk issue in Xcode on M1 Macs.

**Comment by hendrik1120** [comment]
figured it out. Unlike the iOS App, the tvOS App can't playback with the server being in a different subnet.
Fix for now: move server in same subnet as tv

**Comment by LePips** [comment]
Cool that you found the issue, sorry that it happens. I'll take a look at this but we may not be able to fix this. Nothing changed regarding the networking for tvOS both on the app configuration and stream configuration (nothing regarding the stream construction affects that). VLCKit doesn't have an issue with this either. I'll try a few things and if nothing comes out of it I will close this.

**Comment by LePips** [comment]
I apologize as I'm perplexed as to why this used to work and now doesn't. If you're able to load your libraries but can't play media then it narrows down the issue to VLCKit but nothing was changed with our VLCKit implementation to affect this. I'm going to close as this isn't something that seems fixable.

**Comment by hendrik1120** [comment]
Yeah, the problem is indeed really weird. I also tried some different things but couldn't find any additional networking requirements for TVVLCKit.
I also don't think that many people will be affected by this as only few use vlans in their homes.

Thanks for investigating and sorry for creating such a big issue in the beginning.

**Comment by simphide** [comment]
I also have the same problem, but my Apple TV is in the same subnet as my jellyfin server. I am also using the older Apple TV 4K. When I try to playback any video it only shows a black screen, but in the Jellyfin dashboard it says, that the video is playing...

**Comment by LePips** [comment]
This may be a transcoding issue, apologies as it will be fixed in the next build. (this may also be the solution to the original problem)
