### ISSUE TITLE
JellyfinAPI Refactoring

### ISSUE THREAD

**Issue by PangMo5** [jellyfin/Swiftfin#277]
Currently, I am improving https://github.com/jellyfin/jellyfin-sdk-swift.

Existing jellyfin-sdk-swift is using https://github.com/OpenAPITools/openapi-generator.

When using `openapi-generator`, there was a problem because it did not match the current specification given by https://api.jellyfin.org/openapi/jellyfin-openapi-stable.json
So, it is not fully automated because the file is being generated by temply modifying `api.json`.

And I found a tool https://github.com/kean/CreateAPI (although it's still pre-release), 
It is dependent on https://github.com/kean/get and supports only concurrency .
and as a result of creating an API locally, I confirmed that it works normally without any problems that occurred when using `openapi-generator`.

When it's organized to a bit,
I'll leave a draft PR on the https://github.com/jellyfin/jellyfin-sdk-swift repo and Swiftfin repo.

However, it is expected that it will be very difficult to modify the codes to suit the newly created API. 😭 

And I hope we can discuss whether concurrency is really productive and how the performance will be. 🤔

**Comment by LePips** [comment]
What changes would this make to API calls at their call site? It will look entirely different?

**Comment by PangMo5** [comment]
It'll a lot of functions change to async functions.
The method of calling will be changed as described in [Docs](https://github.com/kean/get#sending-requests).

**Comment by PangMo5** [comment]
> What changes would this make to API calls at their call site? It will look entirely different?

It'll a lot of functions change to async functions.
The method of calling will be changed as described in Docs.

**Comment by LePips** [comment]
Hm yeah that might introduce a lot of work. Ping me in the sdk project once you get something up about it and I'll check it out

**Comment by LePips** [comment]
I don't see that anything has been worked on this. By taking a look at things, I say we should stay with our current API structure to prevent a massive overhaul of the entire project.

**Comment by PangMo5** [comment]
> I don't see that anything has been worked on this. By taking a look at things, I say we should stay with our current API structure to prevent a massive overhaul of the entire project.

Yes, that's right.
Recently, I have been so busy with my personal works that I have not been able to touch..
If I improve it, I'll response to some extent with `Combine` so that the existing API part is not modified as much as possible.
This is probably necessary as Jellyfin API keeps updating.

**Comment by PangMo5** [comment]
I'll take a look at it today.

**Comment by LePips** [comment]
Don't worry! I was just looking through issues, don't work on this if you don't have time or it becomes a stressor.
