### ISSUE TITLE
4K H265 playback doesn't work on iPad Air 2

### ISSUE THREAD

**Issue by andrein** [jellyfin/Swiftfin#285]
### Describe the bug

1. Play a H265 video
2. That's it, video won't play. No error message, it just displays the loading spinner.

I believe this is related to https://github.com/jellyfin/jellyfin-expo/issues/261

It looks like the iPad Air 2 doesn't support hardware decoding for H265, but I don't have any lower resolution h265 files in my library to confirm that software decoding actually works.

I believe a possible fix is to have H265 videos should be transcoded server side to H264 for anything with a processor older than the Apple A9 (judging by the comments on https://github.com/jellyfin/jellyfin-expo/issues/261)

### Application version

1.0.0.(68)

### Where did you install the app from?

TestFlight

### Device information

iPad Air 2

### OS version

iPadOS 15.0

### Jellyfin server version

10.7.7

**Comment by LePips** [comment]
Thank you for opening this issue. Would you be able to provide a source of media of 4k H265? I just don't have any.

DM me on Matrix for that 😉

**Comment by acvigue** [comment]
wait are we no longer transcoding videos? this used to be implemented specifically because one of my dev devices is the Air 2 lol

**Comment by LePips** [comment]
For some reason we aren't getting a transcoded URL, even when I tried to force one via bandwidth or making the codecs unavailable. 

The check for a transcoded URL is there but it just isn't working 🤷‍♂️ however that work may not be in the latest TestFlight. I also have an iPad Air 2 lying around somewhere I can test with in a bit.

**Comment by andrein** [comment]
In my case, this issue wasn't actually caused by the codec, but by the fact that my server had a BasePath configured. #309 fixes that issue for me.
