### ISSUE TITLE
tvOS Recommendations

### ISSUE THREAD

**Issue by G10vanni74** [jellyfin/Swiftfin#286]
Hello 

First of all, I find your app very well on its way to being the best.
I love the media view with the big fanart it's great.

I have 3 Apple TVs of different generations and Jellyfin Native works well, can be a bit media loading but acceptable.

Many questions on the continuation of your development:

Is it possible to add an 'add to favorites' button next to the play button and put on the right, the synopsis of the media? Which will balance the bottom line

Will there be media image chapters?

Consider creating a home screen unlike any other popular app, much like the Apple TV app where all new media or media to watch will appear at the bottom with the fanart behind it ?

Will there be a light mode as offered by TVOS ?

There will be an option to switch the covers to landscape mode because all the fanarts are available on Jellyfin server ?

Thank you for creating Jellyfin Native, I love it and happy new year !!!

**Comment by LePips** [comment]
Hi and thank you for asking, I plan on, like, all of that!

**Comment by G10vanni74** [comment]
Searching by actor would also be good.
actor pics, cast and crew in circle like tvos on the media page will be great

is it possible to plan it too?

 thanks

**Comment by LePips** [comment]
Cast and Crew is a trivial implementation. They won't be circles and most cropping of the actor/actresses face is awkward since most portrait shots are not centered. This won't look exactly like Apple TV.

**Comment by G10vanni74** [comment]
Hello
I just saw my application update on my apple tv, and I finally find what I've been looking for for years and I think I'm not the only one
a. homescreen in the apple way, beautiful simple intuitive a big thank you.

I don't have time to browse native jellyfin yet but I wanted to know if it was possible
to have thumbnail where the title of the media appears different from the fanart which is in the background or to have the possibility of doing it manually?

Can you choose the first line between recent media and to follow?

Thank you again for this Great  work !!!

**Comment by LePips** [comment]
The title will just be the item's title name, which is either the movie or series name. This will not be customizable.

**Comment by G10vanni74** [comment]
If I understand correctly, the thumbnail will be identical to the wallpaper and the artwork will be replaced by the title above the row of movies?

**Comment by LePips** [comment]
I'm sorry, I don't understand exactly what you're pointing out.

Just to tell you how it works: items have 1 or 2 images: the primary image or a backdrop image. For movies and a tv series, they generally have both where the primary image is the poster and the backdrop image is the large, landscape image. For episodes, they only have the large landscape image.

The items for the large home view on tvOS uses these respectfully:
- for movies : use its own backdrop image and movie title
- for tv shows : use the _series_ backdrop image and _series_ title

**Comment by G10vanni74** [comment]
Sorry 

In fact I wanted to know just on the homepage if it was possible to have a cover in landscape format different from the large image of the wallpaper when it is possible knowing that the pictures are available on the server (photo)


![apple-tvplus-now-available-11119 jpg landing-big_2x](https://user-images.githubusercontent.com/76523016/149635011-ce0726df-0d8f-4012-8b66-f367f8c150c0.jpg)

![apple-tv-app-1-840x473](https://user-images.githubusercontent.com/76523016/149635022-3c4f27af-83d2-49da-8aba-c9e5620a645b.jpg)


For me, cover picture and wallpaper are the same picture

  thank you

**Comment by LePips** [comment]
No, getting multiple images like this isn't possible. We are only guaranteed to be given up to a single primary photo and a single backdrop photo.

**Comment by G10vanni74** [comment]
ok thank you for taking the time to answer me

**Comment by LePips** [comment]
So, I'm actually gonna roll back my comments a bit and try something.

I said that "We are only guaranteed to be given up to a single primary photo and a single backdrop photo." however thumb photos are generally easy to get. So, I might try it such that _if_ a person has a thumb image, then that image is the small card and the backdrop is the big cinematic view.

This will only affect the home cinematic view. For item views it will be a long ways away as I still design those.

**Comment by G10vanni74** [comment]
Awesome, great news !

 Jellyfin provides a lot of thumbnails and if you can't find them, you can find Apple's thumbnail  on https://bendodson.com/projects/itunes-artwork-finder/

**Comment by LePips** [comment]
Hm I'll have to see if we can use that, might follow under copyright/usage rights

**Comment by LePips** [comment]
So we can't just plug-and-play with that and I also wouldn't feel comfortable with it because it goes through _his own_ servers where he parses it and such. However, This is very simply to make a plugin with. I might try that out but that specifically will be a very long ways away.

**Comment by G10vanni74** [comment]
You were absolutely right, in addition jellyfin provided enough thumbnail in its library to use them with Jellyfin Native That's why I like your new thinking. It would be a shame not to use them. I'm waiting to see your test
Personally I do not use it but I heard about it on other sites
 I only use jellyfin server because it is better and there is a choice!

**Comment by LePips** [comment]
So just found out there's a plug-in already to get ITunes images into your library

https://github.com/MrTimscampi/jellyfin-plugin-itunes

**Comment by G10vanni74** [comment]
In the home screen, the recommendations, will it be possible to choose the items that will be highlighted. 
 Currently the media in progress  appear first
followed by the TV shows then come the mines or recent movies and recent TV shows.  
my question is as follows: can we choose the media that will be highlighted, for example recent movies or recent tv shows?
  thank you

**Comment by LePips** [comment]
I plan on many home screen improvements under https://github.com/jellyfin/Swiftfin/issues/203

**Comment by LePips** [comment]
I'm going to close this as some of the original requests are either implemented or are as a part of continued development.
