### ISSUE TITLE
Support QuickConnect

### ISSUE THREAD

**Issue by 9p4** [jellyfin/Swiftfin#288]
Support signing in via QuickConnect

https://jellyfin.org/docs/general/server/quick-connect.html

**Comment by LePips** [comment]
This will come in 2 parts:

1 - simple start quick-connect session and implement quick-connect sign in
2 - test by invalidating quick-connect sessions. I think this may just throw errors as the session no longer has a valid API key

**Comment by thornbill** [comment]
Just a heads up in case you were unaware, there were some changes to how quick connect works in 10.8. You probably don't want to spend time implementing support for the 10.7 method. 😉

**Comment by LePips** [comment]
Thanks for the update!

**Comment by LePips** [comment]
@thornbill Where can I look at an unstable spec just so I can check 10.8 out?

**Comment by crobibero** [comment]
Currently you can view the unstable spec here: https://repo.jellyfin.org/api.html?version=unstable

Soon:tm: you'll be able to view the spec at https://api.jellyfin.org?version=unstable

**Comment by LePips** [comment]
Marked as external, waiting for 10.8 release
