### ISSUE TITLE
[feature request] Double-tap forward/backward player controls

### ISSUE THREAD

**Issue by avion540** [jellyfin/Swiftfin#30]
I would like to be able to double-tap the player backward/forward time skip buttons. YouTube and Netflix have this and it's so convenient.

**Comment by acvigue** [comment]
And what would double tapping do? Time skip twice as much?

**Comment by avion540** [comment]
No, double tapping would just skip ahead 15s. [Here's](https://www.dropbox.com/s/7ix5kblbagkdiud/double-tap%20youtube%20example.mp4?dl=0) an example video from the iOS YouTube app.

**Comment by acvigue** [comment]
working on this
