### ISSUE TITLE
Default to English if string is not translated

### ISSUE THREAD

**Issue by oxixes** [jellyfin/Swiftfin#303]
### Describe the bug

Currently, if a string is not translated to the device language, the name of that string is shown. Instead of that the English version of that string should be shown.

Example:
![EDE44603-AFC2-454B-8AA8-FDE3223A8F24](https://user-images.githubusercontent.com/38050447/149598919-d9fdbf07-68e3-432f-84ed-6b582508066e.png)

### Application version

1.0.0 (69)

### Where did you install the app from?

TestFlight

### Device information

iPad Pro (11 inch) (2 gen)

### OS version

15.2

### Jellyfin server version

10.7.7

**Comment by LePips** [comment]
Developer note: implement custom lookup function
https://github.com/SwiftGen/SwiftGen/blob/stable/Documentation/Articles/Customize-loading-of-resources.md
