### ISSUE TITLE
Music popped up

### ISSUE THREAD

**Issue by charleypeng** [jellyfin/Swiftfin#312]
### Describe the bug

well I see this project do not have plan to manage music library, but in this latest debug release, latest added music files come out (just two or three of them). 

### Application version

1.0.0(69)

### Where did you install the app from?

TestFlight

### Device information

iphome12

### OS version

ios 15.2

### Jellyfin server version

10.7.6

**Comment by LePips** [comment]
This was fixed, will be  in the next build.
