### ISSUE TITLE
all movies from one folder show as "unaired"

### ISSUE THREAD

**Issue by foss-** [jellyfin/Swiftfin#316]
### Describe the bug

Added a folder with concert movies to Jellyfin. That folder also shows up in Swiftfin. Previously playing content was no problem but in the latest TestFlight release 1.0.0 (69) all items show as `Unaired` and there is no way to play them.

### Application version

1.0.0 (69)

### Where did you install the app from?

TestFlight

### Device information

iPhone xr

### OS version

15.2.1

### Jellyfin server version

10.7.7

**Comment by LePips** [comment]
This is fixed, will be in the next version (after 69)
