### ISSUE TITLE
The loading of the media a little longer

### ISSUE THREAD

**Issue by G10vanni74** [jellyfin/Swiftfin#318]
### Describe the bug

When I'm on the media page, movies or TV shows.
The media quickly reloads twice even if the media is already found.

It makes mini flashes every time

### Application version

the last

### Where did you install the app from?

TestFlight

### Device information

Apple TV 4.  4K and 4K 2021

### OS version

tvOS15.3

### Jellyfin server version

the last

**Comment by LePips** [comment]
This isn't really a bug, but something we have to do as an optimization. Gonna close as all optimizations are a work in progress and I'm going to redo those views soon.
