### ISSUE TITLE
Keyboard Shortcuts

### ISSUE THREAD

**Issue by LePips** [jellyfin/Swiftfin#322]
Mainly on iPadOS but iOS would also benefit as well. Recognize keyboard input on the video player.

Some basic commands:
- space: play/pause
- left/right keys: jump back/forwards
- escape: close
- c: toggle subtitles (if available)
- Command+right key: next item (if available)
- Command+left key: previous item (if available)
- Command+n: toggle autoplay (if available)

I was thinking about a custom overlay view that will flash a corresponding icon or whatnot once a key is pressed (similar to the current jump lengths on swipe gestures), however that is optional and a polish feature way down the road.

**Comment by PangMo5** [comment]
Did you start working on this?
If not, can I do this?

**Comment by LePips** [comment]
I have not and probably won't personally
