### ISSUE TITLE
Device Dependent Item Sizes

### ISSUE THREAD

**Issue by cheetashock** [jellyfin/Swiftfin#329]
With the new collections integration, I was checking them out. It took quite a long time for me to figure out that I had to scroll horizontally to see more content. Horizontal scrolling isn't an issue, just make it more obvious that you need to scroll horizontally. Maybe make it so the next movie "peaks out"?

![image](https://user-images.githubusercontent.com/1431563/150439540-d65bec6b-7887-4f1d-8ed5-60fac4aff2c1.png)

**Comment by LePips** [comment]
This definitely sounds like a design improvement. What device are you using? On my big iPhone 11 Pro Max, items peek just fine but we may need to adjust some sizing depending on device, which is fine.

**Comment by cheetashock** [comment]
iPhone 12 Pro, so you are correct.
