### ISSUE TITLE
[feature request] Display episode number for each episodes

### ISSUE THREAD

**Issue by userobvixus** [jellyfin/Swiftfin#33]
Hi, I can’t know what number of my episode is, it could be better to display number of episode like S1E01. before the title 
Thanks you for your works your application is great !
![D8ACD2F8-5163-4A9F-A0CD-60BAAD32054F](https://user-images.githubusercontent.com/73913514/120560876-dad0e000-c403-11eb-8288-972cc2de1c44.png)
![D8A8F282-E54E-4890-BF76-3F426F6B7A49](https://user-images.githubusercontent.com/73913514/120560879-dc9aa380-c403-11eb-89a2-669996cffbaf.png)

**Comment by acvigue** [comment]
will be added in latest build
