### ISSUE TITLE
No local servers found

### ISSUE THREAD

**Issue by smidley** [jellyfin/Swiftfin#334]
### Describe the bug

When opening the application for the first time to add a server, no local servers are found on the network.  I'm not sure if this scanning is even in place yet, or auto triggered.  In any case, no servers are listed even though I have a local LAN server.  I am able to type in the local IP address of my server and use it just fine, it would just be nice to skip that and select it from a list.  This happens both on iOS and tvOS

### Application version

1.0.0

### Where did you install the app from?

TestFlight

### Device information

Apple TV 4K 2nd gen, Apple iPhone 11 Pro

### OS version

tvOS 15.2, iOS 15.2

### Jellyfin server version

10.7.7 (docker)

**Comment by LePips** [comment]
Just to check on iOS, go to to the Settings _app_ -> Swiftfin and make sure Local Network is enabled

**Comment by LePips** [comment]
No, it should always show since we ask for local network permissions and if you ever try to use it on cellular it will have an option to not use cellular data.

Maybe trying it on cellular really quick will do that? My assumption is that the prompt to allow local network access didn't show. I do have the thought to re-prompt/open settings if we don't have the necessary permissions, especially when I finish Chromecast.

**Comment by LePips** [comment]
That as well, we use that port for the discovery service. I would recommend bridge mode for the container if you don't have that configured.

**Comment by alteredtech** [comment]
```yaml
    ports:
      - 8096:8096
      - 8920:8920 #optional for HTTPS
      - 7359:7359/udp #optional local discovery
      - 1900:1900/udp #optional
```
This is my docker-compose file, so if there is a place in unraid to add an additional port that is what you need to do. Then *fingers crossed* local discovery should work.

**Comment by smidley** [comment]
> ```yaml
> ```yaml
>     ports:
>       - 8096:8096
>       - 8920:8920 #optional for HTTPS
>       - 7359:7359/udp #optional local discovery
>       - 1900:1900/udp #optional
> ```
> 
> 
>     
>       
>     
> 
>       
>     
> 
>     
>   
> This is my docker-compose file, so if there is a place in unraid to add an additional port that is what you need to do. Then fingers crossed local discovery should work.
> EDIT: So I just discovered this with my docker setup for local connection. Now this is an educational guess and has not been tested for proof. If your container is using bridge networking, it will have the container create an ip address and then NAT from the host (unraid in your example) to the container. When you attempt to join the server, your client does not know how to get to 172.18.0.2 (example ip of the container inside your host) and since that ip is not on the local network, it tries to route out the router. What should get around this is to use host networking rather than bridge networking. Something else that could work is creating a static route that points to the host from your router.
> ```

Yes, I just discovered this as well.  I am using bridge mode, and added the 7359 port.  In the Swiftfin app, I see the server listed now automatically, but it's the container IP 172.17.0.3 and I'm not able to actually connect to it from my client.  Is it recommended to use host networking for Jellyfin?  I've heard that bridge mode should be used.

**Comment by smidley** [comment]
Additionally, if port 7359/UDP should be exposed by default, the docker image for Unraid should be updated since it's not included.  I'm not sure where this officially resides, but if someone wants to point me to it, I can do a PR.

**Comment by LePips** [comment]
> recommended to use host networking for Jellyfin

I apologize for my original comment to use bridging mode, you should use _host_ mode like you said.

**Comment by LePips** [comment]
I believe it recommends host mode, since with host mode you don't need to explicitly expose anything; it acts like one machine

**Comment by LePips** [comment]
Gonna close since issue is fixed
