### ISSUE TITLE
List Video and Audio tags in video overview

### ISSUE THREAD

**Issue by smidley** [jellyfin/Swiftfin#336]
When looking at a video, it should be obvious what the resolution and color options are for the video.  Things like 4k, HD, HDR, Dolby Vision, etc.

Here's a screenshot of the current view:
![image](https://user-images.githubusercontent.com/421573/150575205-e41be5ee-2f5f-4d9e-aace-768a5ae35be2.png)

Here's a screenshot of the same video in Infuse that shows the video tags:
![image](https://user-images.githubusercontent.com/421573/150575290-6b8a0609-33c5-49a2-bf50-9cdb649583e5.png)

It would also be great to see audio tags such as Dolby Atmos, or 5.1, etc.

Another example of an app showing audio tags:
![image](https://user-images.githubusercontent.com/421573/150575779-3ebb560f-ac2c-4e4b-aebe-2e8ab13c9b61.png)

**Comment by LePips** [comment]
This will come when I kind of refactor these views.
