### ISSUE TITLE
Appearance And Next video 

### ISSUE THREAD

**Issue by G10vanni74** [jellyfin/Swiftfin#341]
It's great to have found the solution to be able to use the thumbnails      thank you !

I wanted to know if these functions are part of the application
To know:

an Appearance option". Select "Light", "Dark"

and an. "next video" function which will be represented by a window which will appear a few seconds from the end of an episode giving the choice to stop or to continue

**Comment by LePips** [comment]
Appearance is planned.

We are axing the idea of a window popping up during playback and replacing them with buttons that are always up for previous and/or next episode on the overlay.
