### ISSUE TITLE
All Media tab is empty & Music won't play

### ISSUE THREAD

**Issue by dotnetdan** [jellyfin/Swiftfin#343]
### Describe the bug

The all media tab doesn't show any results from my library.

I'm able to browse albums via Home>Recently Added. When I tap on any album, it doesn't show any tracks and I cannot play the album.

My library contains music only. I'm accessing my server via Nginx reverse proxy, https only. In comparison everything works fine through the official iOS app.

### Application version

1.0.0(69)

### Where did you install the app from?

TestFlight

### Device information

iPhone 7

### OS version

iOS 15.2

### Jellyfin server version

10.7.7

**Comment by LePips** [comment]
1- you say you're on build 69, use the new TestFlight link to get build 70
2- Swiftfin doesn't support music. What you see right now is just an oversight from a filter

**Comment by dotnetdan** [comment]
Interesting

> Swiftfin doesn't support music

> Swiftfin is a modern client for the Jellyfin media server. Redesigned in Swift to maximize direct play with the power of VLC and look native on all classes of Apple devices. 

Might be slightly misleading there

**Comment by LePips** [comment]
We will clarify that it's only for video playback, thank you
