### ISSUE TITLE
Media views with Logo ?

### ISSUE THREAD

**Issue by G10vanni74** [jellyfin/Swiftfin#345]
1 / Is it possible to insert media logos in the media view ?
 .
Insert them in such a way that they only appear in the media page because when the logos appear in the main page, it's too busy.

<img width="1128" alt="Capture d’écran 2022-01-23 à 14 12 43" src="https://user-images.githubusercontent.com/76523016/150680154-c56c0642-26a0-4aa1-bf14-e3ac5804b05c.png">

I tried for the fanart seasons but couldn't separate them, what I put for the media view also appears
in the recommendations on the home page.

Is it possible to use the Jellyfin logo only on the media page?

<img width="1128" alt="Capture d’écran 2022-01-23 à 14 11 27" src="https://user-images.githubusercontent.com/76523016/150680133-6189e014-883c-4014-88e9-6d7ee8ff2df2.png">

2/ Will there be an option to use landscape posters, thumbnails, which I think is the more modern format for views instead of classic posters.
Many applications like infuse, plex, Squire, use this classic cover format.

As Swiftfin is intended as a native application to tvOS,

Why not ?

**Comment by LePips** [comment]
Logos is something I've thought about, especially since 10.8 will be able to get logos from TMDB since the provider the server uses was updated. However it's pretty low priority for me right now

**Comment by perrinpagess** [comment]
+1 for horizontal movie posters
