### ISSUE TITLE
Navigate TV Shows episodes

### ISSUE THREAD

**Issue by TheoBrigitte** [jellyfin/Swiftfin#347]
**Describe the feature you'd like**

On tvOS there is currently no way to navigate through the list of  TV Shows seasons and episodes. The only available option is to click Play which start the next unwatched episode.

I would like to be able to select which season / episode I want to watch in a TV Show.

**Comment by LePips** [comment]
Have you enabled cinematic views from the settings? Those are the views that I will transition to while I redo the current "compact" views. These views have episode selection.

**Comment by TheoBrigitte** [comment]
Ok this work in the cinematic views. Thanks.

Looking forward to have this in the compact views also.
