### ISSUE TITLE
Faster rewing & fast forward

### ISSUE THREAD

**Issue by TheoBrigitte** [jellyfin/Swiftfin#348]
**Describe the feature you'd like**

On tvOS I currently can only rewind & fast forward by 15 seconds interval by pressing left or right arrow keys.

I would like to be able to rewind & fast forward much faster.

**Ideas**

Being able to move the timeline cursor using the arrow keys. Short keypress +10sec, long keypress +1mn
This gives a very fast and accurate way of moving in time.

![rewind_fast_forward](https://user-images.githubusercontent.com/6536819/150803013-a2e091f6-7e04-4ec9-bc7f-fd22ced1a670.gif)

This comes from MrMC app.

**Comment by LePips** [comment]
You can edit the jump lengths in the settings

**Comment by TheoBrigitte** [comment]
Ok, thanks 30sec jump is an improvement but still not ideal/too slow.

Looking forward to see more improvements here.
