### ISSUE TITLE
Quick navigation

### ISSUE THREAD

**Issue by TheoBrigitte** [jellyfin/Swiftfin#349]
**Describe the feature you'd like**

I would like to have a way to quickly navigate through my large collection of movies.

Moving down row by row is very slow. I need something where I can move through the list much fast.

**Idea**

I found quite piratical to hit right arrow and see a alphabetical navigator poping up on MrMc.

![navigation](https://user-images.githubusercontent.com/6536819/150803824-84e3f479-e15e-49c6-99b4-7b770be024b4.gif)

**Comment by LePips** [comment]
I will put this with https://github.com/jellyfin/Swiftfin/issues/333
