### ISSUE TITLE
[feature request] Add Airplay and Chromecast support

### ISSUE THREAD

**Issue by sschiea956** [jellyfin/Swiftfin#35]
I’m not sure if each casting protocol should be split into its own issue.

**Comment by acvigue** [comment]
airplay supported though control center
chrome cast tbd

**Comment by bestlem** [comment]
On IPad 15 this does not seem to be so - control centre does not affect where the output goes

I watch the video on my iPad and want to play sound on my Homepods.

**Comment by Manlycookiebear** [comment]
I have the same problem on an Ipad 8 with iOS 15. If I switch to the Airplay device the sound from Swiftfin is not playing on my Airplay speaker.
