### ISSUE TITLE
Trailers 

### ISSUE THREAD

**Issue by G10vanni74** [jellyfin/Swiftfin#350]
Do you plan to add the trailers, if so
Will it be inserted in the media page or will it appear in a dedicated tab on the homescreen , recommandation ? 

or not planned

**Comment by LePips** [comment]
It _can_ happen, but not for a very long time.

**Comment by G10vanni74** [comment]
I did not completely understand. ,
what do you mean ?

**Comment by LePips** [comment]
Trailers aren't planned but can eventually be implemented, but it will be a very long time.
