### ISSUE TITLE
Safe Area Aspect Fill and Percent based Scaling

### ISSUE THREAD

**Issue by perrinpagess** [jellyfin/Swiftfin#352]
**Describe the feature you'd like**

Aspect fill to safe area on devices with a notch. Percent based scaling would also be nice for iPads. 

**Additional context**

Some cinemascope (and other widescreen aspect ratio) videos have hardcoded letter box bars to make them 16:9. Implementing safe area aspect fill would eliminate the need to transcode and crop the black bars from the video source. Some videos have pillar box bars hardcoded (4:3, 15:9, etc.) to make them 16:9 and percent based scaling would remedy that issue (iPads have a taller than 16:9 aspect ratio so hardcoded pillar boxes mainly affects them).

**Comment by LePips** [comment]
I attempted to aspect fit the safe area during my aspect fill work however something was off with my math and I just abandoned it.

Percent based however will be more difficult.

**Comment by perrinpagess** [comment]
Nplayer has percent based scaling but I'm not sure how they do it. I think they implement safe area aspect fill as a saved percentage for each device. The percentage based scaling works for their "software", "hardware", and "quicktime" decoders. What makes percent based scaling difficult? I'm curious why many players don't have the ability of percent based scaling.

**Comment by LePips** [comment]
Just math people have to figure out

**Comment by LePips** [comment]
Okay sadly, this might be impossible for us to do with VLCKit. In order to perform the scaling, we would scale the video buffer accordingly. However, this also scales the subtitle buffer as in VLCKit they output to the same view.

**Comment by perrinpagess** [comment]
That's unfortunate :(

Does VLCKit have the ability to respect bitstream filters? With ffmpeg you can "crop" a video in metadata by tagging it as a different resolution than it actually is (e.g., tagging a hardcoded 16:9 cinemascope movie as 1920x800) and players that support it can display the cropped video.

https://ffmpeg.org/ffmpeg-bitstream-filters.html

This isn't as easy as safe area aspect fill but is a possible solution and also a general enhancement.

**Comment by LePips** [comment]
No, they just have all output in a single stream

**Comment by perrinpagess** [comment]
Oh ok
