### ISSUE TITLE
Cinematographic view

### ISSUE THREAD

**Issue by G10vanni74** [jellyfin/Swiftfin#353]
I wanted to know if for the bottom of the page of the media view, elements could be brought such as the sypnosys, the rate of the media , the definition like 4k, HDR, 1080 .....( like this)
![AAFAA6DC-4B2D-4CD2-91EF-364EA089C26A](https://user-images.githubusercontent.com/76523016/151522336-75ea1282-7c4f-47f3-b837-e581bb36eb21.png)

This would also fill in the bottom part. Which seems unbalanced to me

is it possible ? can you plan it ?
Thanks

**Comment by LePips** [comment]
I plan to add more tags in https://github.com/jellyfin/Swiftfin/issues/336 however I'm not going to make it look just like Apple TV.

**Comment by G10vanni74** [comment]
yes of course, I just wanted to give you an example of filling.
I could have sent the media page of INFUSE PRO 7 which is not bad too
