### ISSUE TITLE
Support for Photos?

### ISSUE THREAD

**Issue by moritzj29** [jellyfin/Swiftfin#357]
**Describe the feature you'd like**
It would be really great to have support for the media type Photos. So basically just viewing static images, eventually automatic change to next picture after x seconds.

**Additional context**
There is no app for viewing a self-hosted photo library on Apple TV at the moment. So it would be a really nice feature. But I understand that there probably enough work to do with core functionalities... Unfortunately, I have no clue programming in Swift.

**Comment by LePips** [comment]
We won't be looking to host other types of media either in this app, or for a very long time.
