### ISSUE TITLE
Can't play audio on iPad chnage output to airplay speakers

### ISSUE THREAD

**Issue by bestlem** [jellyfin/Swiftfin#361]
### Describe the bug

Run and show video on iPad

I can't change where the audo goes to.

On web and on Jellyfin app and many other video apps - there is the usual icon to send audio to another device.

On other apps that don't have this icon then you can usually pull down the control centre and use that chnage the audio output.

### Application version

Latest

### Where did you install the app from?

TestFlight

### Device information

11 in iPad Pro - 2018

### OS version

ios 15.3 and previous

### Jellyfin server version

 10.8.0

**Comment by LePips** [comment]
Is this a bug or a feature request? If a request, I don't intend to populate with another button.

**Comment by bestlem** [comment]
It is a bug that you can't make the audio come out of airplay speakers even if just via Control Center. It is a normal function of any video app 
I accept adding the standard icon to send the audio as in in many video apps -e.g. Jellyfin, vlc , mplayer derivatives, Amazon Prime, BBC iPlayer, nPlayer could be considered a feature request.

**Comment by LePips** [comment]
I'm able to play audio via Airplay on other speakers just fine. For the feature request, I won't be adding another button if it can just be done via the Control Center, it requires a lot more functionality that isn't worth doing.

**Comment by bestlem** [comment]
OK I have a bug - using Control Center does NOT work.

**Comment by hendrik1120** [comment]
@bestlem Yep it's definitely NOT working via the control center. 
@LePips Every app on the store has this button: Netflix, Prime, Twitch, YouTube, Plex, even the native player has it.

**Comment by hendrik1120** [comment]
Bluetooth speakers seem to be working fine. I bet that it is a VLC Kit issue again and won't be fixed.
Streaming audio via AirPlay with the native player however works just fine if you only want to listen to music, as the native player can only display blackscreens.

**Comment by bestlem** [comment]
@hendrik1120 Streaming audio via AirPlay works fully on

native player
Plex 
nVideo
AmazonPrime
VLC
BBC iPlayer
JellyFin
YouTube

and in other cases you need to use control centre.

The only ones that seem NOT TO WORK AT ALL are
SwiftFin
ITV Player

I think Swi

**Comment by hendrik1120** [comment]
@bestlem I think your comment got cut off... I don't get what you are trying to say.
I switched to the Infuse 7 player for content on my Jellyfin server and AirPlay works with it too.
