### ISSUE TITLE
Vidéo Playback lag

### ISSUE THREAD

**Issue by G10vanni74** [jellyfin/Swiftfin#368]
### Describe the bug

I have vidéo playback problem

little lag and not clear 
![C62E590F-A172-42BA-BD26-48C0B9CFC48F](https://user-images.githubusercontent.com/76523016/152817903-8117114b-dfab-49dd-b2c9-0c6f9b2ca63e.jpeg)

### Application version

The last 

### Where did you install the app from?

TestFlight

### Device information

Apple TV 

### OS version

15.3

### Jellyfin server version

The last

**Comment by LePips** [comment]
Is this a transcoded stream?

**Comment by G10vanni74** [comment]
I tried with and without trancoding: I always have mini Lag and a not clear image,

My internet connection is fiber and I run everything with a SYNOLOGY ds 218 play

I compared the same scene with Plex and the playback seems smoother.

What setting should I do with jellyfin?

**Comment by LePips** [comment]
Sorry, there could be a lot of reasons for this. Does this happen with other JF clients? Other types of media?

I'll need at least server logs when viewing the lagging media.

**Comment by stp6778** [comment]
Lags comes with apps player which does'nt use file frequency
video file: 1920x1040@23.976
atv : adapt frequency

swiftfin : force directplay on or off; native player off  
tv signal stay at 50Hz => lags

swiftfin : force directplay on or off; native player on 
tv signal switch to 24Hz => no lags ; transcode seems always active

**Comment by LePips** [comment]
Sorry, but this is a VLCKit error that we can't do anything about.
