### ISSUE TITLE
Playback jerks

### ISSUE THREAD

**Issue by m1k314z** [jellyfin/Swiftfin#371]
### Describe the bug

Video playback jerks every few seconds on tvOS 15.3

### Application version

1.0.0(69)

### Where did you install the app from?

TestFlight

### Device information

AppleTV4K(2019)

### OS version

tvOS15.3

### Jellyfin server version

10.7.7

**Comment by LePips** [comment]
You saw your on build 69. Update to build 71 by using the new TestFlight link and report whether the issue continues.
