### ISSUE TITLE
No HDR effects

### ISSUE THREAD

**Issue by yueyingjuesha** [jellyfin/Swiftfin#375]
### Describe the bug

When streaming HDR video, there is no HDR effect in current video

### Application version

1.0.0(58)

### Where did you install the app from?

TestFlight

### Device information

Iphone 12 pro

### OS version

ios 15.3

### Jellyfin server version

10.7.6

**Comment by LePips** [comment]
Thank you for the issue. However, the missing HDR comes from the lack of it in VLCKit and there is nothing that we can do about it.
