### ISSUE TITLE
tvOS sound issue

### ISSUE THREAD

**Issue by advinliu** [jellyfin/Swiftfin#376]
Testing on tvOS, with dual HomePod mini and default eARC output - seems the sound are not in sync, it just play on the left one for 0.5sec and switch to right one, then flipping back to the left one. It just keep going on, and happened on different media source and format.
Confirm the Apple TV and HomePod work well with YouTube/Apple Music, and it behave normally when using Apple TV VLC app to access Jellyfin library via UPnP.

**Comment by LePips** [comment]
Thank you for the issue and apologies for the late reply, however this is an issue of VLCKit and we cannot fix this.
