### ISSUE TITLE
tvOS App Crash when playing back content recorded from Live TV

### ISSUE THREAD

**Issue by AndrewBreyen** [jellyfin/Swiftfin#377]
### Describe the bug

Pick "recorded shows" from other menu
Select a show that is recorded
Press play
app crashes

This content is able to be played back via Jellyfin app, via the web UI, and is accessible via the file system.

In the swiftfin iOS app, content shows "unaired"

### Application version

1.0.0(69)

### Where did you install the app from?

TestFlight

### Device information

Apple TV 4k

### OS version

latest tvOS

### Jellyfin server version

10.7.7

**Comment by LePips** [comment]
I anticipate the error is still there, but update to build 71 available with the new TestFlight link.

**Comment by AndrewBreyen** [comment]
Actually, it looks like that fixed it! Didn't realize that there was a new link. 
Thanks!
