### ISSUE TITLE
Can't open downloaded subtitles

### ISSUE THREAD

**Issue by Amazingzz614** [jellyfin/Swiftfin#378]
Can't open jellyfin downloaded subtitles

**Comment by LePips** [comment]
Thank you for the issue, however I'm going to need more details. What do you mean by "can't open"? Are you not able to select them from the subtitle menu? And if so, are they showing? I would recommend visiting the documentation on properly naming downloaded subtitles and testing on the web client before going any further.

**Comment by Amazingzz614** [comment]
Thank you for your reply, the subtitle problem has been resolved, but the app will collapse on my iPhone13pro
