### ISSUE TITLE
Rotating orientation doesn't rescale playing video

### ISSUE THREAD

**Issue by aniqueta** [jellyfin/swiftfin#38]
Great to see the rapid development of this app. This may be a known issue, but when rotating the device orientation from portrait to landscape during an active playback, the video does not re-scale to appropriately. Experienced this on an iPad. Thanks.

**Comment by acvigue** [comment]
it shouldn't allow you to rotate the device. it should auto lock on landscape that's weird

**Comment by acvigue** [comment]
stale, closing
