### ISSUE TITLE
Subtitles appear outside of viewport when the video is set to fill screen

### ISSUE THREAD

**Issue by tkafka** [jellyfin/Swiftfin#380]
### Describe the bug

When I toggle the video zoom to fill the screen on a landscape iPhone with a notch (ex. XS), the subtitles stay with the video picture, and as the video zooms in, the subtitles move partially out of the screen making them unreadable.

Regular view (video is unnecessarily small):
![IMG_0945](https://user-images.githubusercontent.com/876717/154864584-55e71fa1-c2ad-46ed-8652-7a530040e9ec.PNG)

Zoomed-in view (subtitles are out of viewport):
![IMG_0944](https://user-images.githubusercontent.com/876717/154864603-e86199dd-9c66-4fec-a0d1-969ad60f18d5.PNG)

I think that subtitles should stay in a same place on screen regardless of the video zoom level, if this is technically possible.

### Application version

1.0.0 (71)

### Where did you install the app from?

TestFlight

### Device information

iPhone XS Max

### OS version

15.3

### Jellyfin server version

10.7.7

**Comment by LePips** [comment]
Thank you for the issue, however this is a quirk of VLCKit and there's nothing we can do about it.
