### ISSUE TITLE
Vertical scrolling judder

### ISSUE THREAD

**Issue by livedreamsg** [jellyfin/Swiftfin#381]
### Describe the bug

Edit: Actually, this is happening on the Home Screen as well now. 

There is judder when scrolling through content vertically, possibly due to the ProMotion display. This does not seem to appear in the home screen or when scrolling horizontally. 

Judder when scrolling vertically within a show:
https://user-images.githubusercontent.com/62317830/155148107-b9ea5e9f-113c-4e37-8b3e-4b82bbbbd9de.MP4

No judder when scrolling horizontally within a show:
https://user-images.githubusercontent.com/62317830/155148716-d65dbb7c-ecf4-465b-b025-504d864f3f50.MP4

No judder when scrolling vertically on the home screen:
Uploading RPReplay_Final1645538714.MP4…

 

### Application version

1.0.0(71)

### Where did you install the app from?

TestFlight

### Device information

iPhone 13 Pro Max

### OS version

15.3.1

### Jellyfin server version

10.7.6

**Comment by LePips** [comment]
This kind of shutter is no longer visible with latest developments.
