### ISSUE TITLE
Infinite scrolling

### ISSUE THREAD

**Issue by livedreamsg** [jellyfin/Swiftfin#382]
**Describe the feature you'd like**
Can we get infinite scrolling through content? What I mean by this is that when we scroll vertically, there is a pause to load new content once you've reached the bottom of the screen. The pause is very minor, maybe half a second to a second long, but it's still quite annoying. The feature request is for there to not be a pause at all(like the Jellyfin app), and you can keep scrolling without the delay. 

**Additional context**
How it currently is:
https://user-images.githubusercontent.com/62317830/155153878-8b7bf779-08a2-453e-a9e0-f3ba61b084fb.MOV 

How it is on Jellyfin:
https://user-images.githubusercontent.com/62317830/155154091-4c602117-2986-4700-8ee2-45432b0b62f1.MOV

**Comment by LePips** [comment]
Thank you for the request. However we're opting for lazy loading of content, mainly due to the large amount of data that items send.
