### ISSUE TITLE
Number seasons in numerical order

### ISSUE THREAD

**Issue by livedreamsg** [jellyfin/Swiftfin#383]
**Describe the feature you'd like**
Can we get seasons numbered in numerical order, and not by the starting digit?

How it is:
![image](https://user-images.githubusercontent.com/62317830/155159765-8cdc486d-031b-4c4d-b54b-427c4ea987b1.png)

**Additional context**
Seasons are categorized by their starting digit, instead of the logical way which is 1-9,10-19, etc.

**Comment by hendrik1120** [comment]
If somebody has trouble finding this, the menu only shows up after navigating down to a single episode.
