### ISSUE TITLE
Screen doesn't switch to portrait mode after video is played.

### ISSUE THREAD

**Issue by livedreamsg** [jellyfin/Swiftfin#384]
Edit: Fixed the picture order. 

### Describe the bug

This one's pretty self explanatory. When your device is in portrait mode and you play a video, it doesn't go back to portrait mode when you exit out of it(it remains in landscape).

![IMG_4715](https://user-images.githubusercontent.com/62317830/155173837-2e88cd0d-5434-4a29-a22e-33a8a67872f9.PNG)
![IMG_4716](https://user-images.githubusercontent.com/62317830/155174051-1bf56ff6-0638-4bc5-8951-2110e2210666.PNG)
![IMG_4717](https://user-images.githubusercontent.com/62317830/155174064-3f7ebbbf-9c30-440e-845e-0024ce9f7b18.PNG)

### Application version

1.0.0(71)

### Where did you install the app from?

TestFlight

### Device information

iPhone 13 Pro Max

### OS version

15.3.1

### Jellyfin server version

10.7.6

**Comment by hendrik1120** [comment]
Can confirm. Rotating the phone resets it back into portrait mode. This was already fixed once in #102, so it's definitely a bug.

**Comment by awb1015** [comment]
Just had this issue with the most recent build. I noticed though that once I disabled the rotation lock the phone (iPhone X) rotated back to portrait after having been stuck in landscape post media play
