### ISSUE TITLE
Sub menu for Random Button / change watched or unwatched status 

### ISSUE THREAD

**Issue by gismox88** [jellyfin/Swiftfin#385]
Would be great to have an button for a sub menu to play TV Shows randomly or a film.

other great possibility would be to change the status of the series/movie watched and unwatched. 

Toggling watched / unwatched only in cinematicview off, but then you see only the actual episode

**Comment by LePips** [comment]
1 - I'll track this in https://github.com/jellyfin/Swiftfin/issues/416
2 - You can
3 - ?
