### ISSUE TITLE
Experimental native player doesn't work with hevc/x265 and no PIP

### ISSUE THREAD

**Issue by 23doors** [jellyfin/Swiftfin#387]
### Describe the bug

Playing x265 mkv content in native player ends up with just black screen. Audio is playing normally.
Wanted to use native player to get PIP on iOS but seems it doesnt work even with x264 content. 

### Application version

1.0.0(71)

### Where did you install the app from?

TestFlight

### Device information

iPhone 13

### OS version

iOS 15

### Jellyfin server version

10.7.7

**Comment by LePips** [comment]
Thank you for the issue. The native player is an experimental feature and I won't be taking issues for it. See this discussion about its implementation: https://github.com/jellyfin/Swiftfin/discussions/324
