### ISSUE TITLE
Cannot connect to Server through Cloudflare

### ISSUE THREAD

**Issue by Huskydog9988** [jellyfin/swiftfin#39]
On 1.0.0 (33) I am unable to connect to my jellyfin server using its domain name. After trying various solutions, like those found in #2, disabling the Cloudflare proxy solved the issue. (For the sake of notation, jelly is being proxied through traefik.) I'm not sure why this connection issue exists, but I can say I've only seen it within this app.

**Comment by acvigue** [comment]
i’m using cloudflare too - with traefik. i need more details

**Comment by Huskydog9988** [comment]
That is as much detail as I know. There are no logs that I know of that can say why this is occurring. If your looking for URLs I tried through Cloudflare:
- http://domain.name
- https://domain.name
- http://domain.name:80
- https://domain.name:443

**Comment by acvigue** [comment]
do you have any url rewrite rules enabled - what is the ssl cert presented on both origin & edge?

**Comment by Huskydog9988** [comment]
It could be that I'm relying upon Cloudflare's 'flexible' ssl cert, and no I don't have any rewrites.

**Comment by Huskydog9988** [comment]
After just glancing at cloudflare's firewall logs it appears that the app was triggering Bot fight mode. Not sure what could cause this. The most likely issue in my mind is that http client is doing something cloudflare doesn't like.

**Comment by acvigue** [comment]
I remember coming across that in testing. It happens with both the swift client and the android client

**Comment by Huskydog9988** [comment]
Not that it would be a high priority, but I think this should at least be looked into. Besides me wanting to be able to use Cloudflares bot defenses, I do think this could have some serious effect in the future. I'm not sure what that is, but I have a creeping feeling that it might.

**Comment by acvigue** [comment]
it’s due to cloudflare. bot fight mode is not meant for production due to a multitude of false positives. swiftfin just uses generic HTTP requests and CloudFlare is probably getting 
mad at the user agent of “alamofire”

Enable IUAM if it becomes a problem

**Comment by acvigue** [comment]
or go into page rules and disable bot fight mode per subdomain
