### ISSUE TITLE
Switch subtitles while playing

### ISSUE THREAD

**Issue by rexzhang** [jellyfin/Swiftfin#395]
When learning a language, you need to switch back and forth between subtitles to practice listening

**Comment by LePips** [comment]
You can switch subtitles on both players.

**Comment by rexzhang** [comment]
Sorry, I didn't make myself clear.
Yes, I can switch in iPad versions, but not in tvOS. tvOS only allows me to choose whether to turn on subtitles or not.

**Comment by rexzhang** [comment]
My environment: tvOS 15.3, Swiftfin 1.0.0(71), installed from TestFlight

**Comment by LePips** [comment]
You can change subtitles on tvOS by accessing the menu my clicking down on the newest remote or tapping on the bottom of the touchpad remote. We will eventually be changing how this menu is accessed.

**Comment by rexzhang** [comment]
Thanks! I found it! This way is better than swiping down on the touchpad. It works well if there are hints in the interface
