### ISSUE TITLE
subtitles not displayed. (etc smi, srt ...)

### ISSUE THREAD

**Issue by mak3S** [jellyfin/Swiftfin#399]
### Describe the bug

The ass subtitles are displayed properly, but no subtitles such as smi or srt.

### Application version

1.0.0(58)

### Where did you install the app from?

TestFlight

### Device information

iphone x

### OS version

ios 15

### Jellyfin server version

10.7.6

**Comment by PangMo5** [comment]
Use the updated app on new TestFlight link.

https://github.com/jellyfin/Swiftfin#%EF%B8%8F-testflight
