### ISSUE TITLE
Search not working

### ISSUE THREAD

**Issue by tknx** [jellyfin/Swiftfin#400]
### Describe the bug

Tried a few searches and picked a couple items from suggested list but results not displayed 

![3DB09461-0336-4AE8-9F0E-C03DC30B6D25](https://user-images.githubusercontent.com/29260341/159815361-c80e596e-85dc-4173-951a-c871266e1b14.png)

### Application version

1.0.0(58)

### Where did you install the app from?

TestFlight

### Device information

iPhone 13

### OS version

Latest

### Jellyfin server version

10.7.6

**Comment by PangMo5** [comment]
Use the updated app on new TestFlight link.
If you still have a problem, you can reopen the issue.

[jellyfin/Swiftfin#%EF%B8%8F-testflight](https://github.com/jellyfin/Swiftfin#%EF%B8%8F-testflight)
