### ISSUE TITLE
tvOS - trying to play videos that require conversion results in a black/blank screen and no sound

### ISSUE THREAD

**Issue by mueslimak3r** [jellyfin/Swiftfin#403]
### Describe the bug

Transcoded and direct stream playback opens the player but just shows a blank/black screen and no audio. I can swipe up to show the player UI.

All app settings are defaults.

This occurs for all videos I've tested which require transcoding. Here's an example:

`TranscodeReasons=AudioCodecNotSupported,ContainerBitrateExceedsLimit`

<img width="986" alt="Screen Shot 2022-03-26 at 2 08 11 PM" src="https://user-images.githubusercontent.com/28824542/160257448-bd4b82a7-f0a2-40c9-916b-ebedf846b319.png">

### Application version

1.0.0 (74)

### Where did you install the app from?

TestFlight

### Device information

4th Gen Apple TV (A1625)

### OS version

tvOS 15.3 (19K547)

### Jellyfin server version

10.8-alpha5 (official docker image)

**Comment by LePips** [comment]
This is actually a bug in 10.8.0 that will be fixed soon in the 10.8.0 Beta soon.

https://github.com/jellyfin/jellyfin/pull/7496
