### ISSUE TITLE
Airplay - No video 

### ISSUE THREAD

**Issue by miIktoast** [jellyfin/Swiftfin#404]
### Describe the bug

Streaming to Roku via airplay, no video displayed only audio.

- connect airplay to tv from cc

-  start playing a show

- Tv plays audio & shows black background w music note, video continues to play on phone

### Application version

1.0.0 (74)

### Device information

iPhone 11 Pro Max

### OS version

15.4

### Jellyfin server version

10.7.7

**Comment by LePips** [comment]
We do not currently support Airplay.
