### ISSUE TITLE
Can not play video over https 

### ISSUE THREAD

**Issue by i6941** [jellyfin/Swiftfin#409]
### Describe the bug

1. I running Jellyfin 10.8 behind the DSM's reverse proxy, and the https is set on the reverse proxy
2. I can view the list and play video by chrome /jellyfin mobile/infuse
3. But when I using Swiftfin and click the play button, playback screen will appear but not play

### Application version

1.0.0(74)

### Where did you install the app from?

TestFlight

### Device information

iphone 12

### OS version

ios 15.4.1

### Jellyfin server version

10.8

**Comment by LePips** [comment]
Are you using TLS 1.3?

**Comment by i6941** [comment]
> 

Thanks, you are right. It's ok when I set it to TLS 1.2.
