### ISSUE TITLE
Subtitles Disappear When Set to Fill Screen

### ISSUE THREAD

**Issue by dannymichel** [jellyfin/Swiftfin#413]
### Describe the bug

When you set the video to fill screen for some(not all) videos with *.ass* subtitles disappear.

### Application version

1.4.1 (5.4.1.0)

### Where did you install the app from?

App Store

### Device information

iPhone Xs Max

### OS version

15.3.1

### Jellyfin server version

10.8.0

**Comment by LePips** [comment]
Thanks for the issue, however this is an issue of VLCKit and we can't do anything about it.
