### ISSUE TITLE
Incorrect season order in season drop down on tv show page

### ISSUE THREAD

**Issue by tamburra** [jellyfin/Swiftfin#415]
### Describe the bug

Odd behavior of what is displayed when choosing a season from the drop down on TV show page. Ordering differs depending on how far down you scroll on the page before you click the drop down. 

![45B652E5-D708-4ED5-BED5-BC75F72BCF4D](https://user-images.githubusercontent.com/16267805/164163408-6f778e9a-9f97-4601-a305-40ccb39d0d4f.png)
![5C4975D0-82F4-440F-AEFF-5BCBE1D46DC8](https://user-images.githubusercontent.com/16267805/164163419-7f9d290f-1b08-4736-8e80-96a42836fbc5.png)

### Application version

1.0.0(74)

### Where did you install the app from?

TestFlight

### Device information

iPhone 12 max

### OS version

iOS 15.4.1

### Jellyfin server version

10.8 beta 2

**Comment by LePips** [comment]
This was fixed in https://github.com/jellyfin/Swiftfin/pull/405 which is yet to be released.
