### ISSUE TITLE
Pressing Logout under settings immediately crashes the app

### ISSUE THREAD

**Issue by iamnewtogithubhelpme** [jellyfin/swiftfin#42]
Pressing Logout under settings immediately crashes the app. Using iPad 8th Gen on iOS 14.x

**Comment by acvigue** [comment]
that's the point.

**Comment by iamnewtogithubhelpme** [comment]
> that's the point.

Ok. I assumed it may come back to login screen.

**Comment by acvigue** [comment]
It's in progress - very low priority at this point :)
