### ISSUE TITLE
-1003 Unknown Error

### ISSUE THREAD

**Issue by JoshLoecker** [jellyfin/Swiftfin#421]
### Describe the bug

I entered the URL of my server (http://192.168.50.31:8096) and I receive an error that says “-1003 Error. Unknown Error”. 

### Application version

1.0.0 (74)

### Where did you install the app from?

TestFlight

### Device information

Apple TV 4k 2nd Generation

### OS version

tvOS 15.3

### Jellyfin server version

10.7.7

**Comment by JoshLoecker** [comment]
I’ve updated to tvOS 15.4.1 and get the same error

**Comment by LePips** [comment]
Thank you for the issue. This error corresponds to being unable to resolve the host.

https://developer.apple.com/documentation/foundation/1508628-url_loading_system_error_codes/nsurlerrorcannotfindhost

**Comment by JoshLoecker** [comment]
I see you’ve got a new commit to fix this, thank you! Restarting my Apple TV also fixed the issue.
