### ISSUE TITLE
I hope to add sliding fast-forward, screen projection, and interface custom display

### ISSUE THREAD

**Issue by sj724640907** [jellyfin/Swiftfin#423]
The interface supports resizing, displays banners or covers or posters, and can be classified by actors and types.  Interface lock can be enabled to prevent do not touch during playback

**Comment by LePips** [comment]
Thank you for the request. Your request seems very encompassing and vague. 

What do you mean by "resizing"? Like different sized portrait items? I have a note for this in https://github.com/jellyfin/Swiftfin/issues/329

For classified by "actors" and "types" you can select an actor to see their media. There are planned improvements for this screen.

Gesture locking is in progress at https://github.com/jellyfin/Swiftfin/pull/412. Fast forwarding is also planned and was briefly mentioned there.

**Comment by sj724640907** [comment]
Adjusting the size means that you can display the cover, poster or banner just like the web page. In addition, after the update of the iPhone 12, the horizontal screen cannot be switched to the vertical screen. There is no solution. I still hope that it is more convenient to swipe on the playback interface to fast-forward and rewind.
