### ISSUE TITLE
Swiftfin iOS only showing limited number of media

### ISSUE THREAD

**Issue by advinliu** [jellyfin/Swiftfin#424]
Under “All Media” and whether I select which folder I created, it will only show the first 16 media. If I change the sorting orders, it will show another 16 selection.

Everything works fine on web browsers though, or is it a limitation of Swiftfin?

Swiftfin version 1.0.0 (74)

**Comment by LePips** [comment]
Thank you for the question. You can scroll down to the bottom of what's current showing and it will lazy-fetch more content of the library. It's an iterative process to improve the experience of this screen so that others won't be confused in the future.

**Comment by advinliu** [comment]
Thanks for the comment, but I tried to scroll to the bottom and it is still showing 16 medias starting with “A”
![9AAA2104-D5E6-482E-A28F-82C3C4AA8A5B](https://user-images.githubusercontent.com/15702279/165879911-79f3dcea-0d15-4b7b-ab1a-a8112a8f2798.png)

**Comment by LePips** [comment]
Oh, interesting. I'll mark this as a bug now and in the next release you'll be able to provide log files so we can see what's going on.

**Comment by LePips** [comment]
Should no longer be an issue due to https://github.com/jellyfin/Swiftfin/pull/536, forgot to tag this issue.
