### ISSUE TITLE
V1.0.0 (75) network error

### ISSUE THREAD

**Issue by Ramsin** [jellyfin/Swiftfin#429]
I installed, from scratch, V1.0.0 (75)...

Auto discover of server doesn't find anything, and when trying to add it manually (regardless if using hostname:port or ip:port) it responds with "-1003 Error Unable to find Host"

This can be resolved by installing (74), adding the server (which gets auto discovered), and then updating to (75), however, when trying to add another server...you get the same response.

**Comment by LePips** [comment]
This error is because the phone cannot find the host, which is something that you will have to look within your network. This is also why the auto-discover does not work.

**Comment by Ramsin** [comment]
Are you sure you read the whole problem? Because (74) has no problems auto discovering or adding manually. It's only when I installed (75) that the issue came about.

**Comment by LePips** [comment]
Apologies, the server discovery was actually broken and is fixed in https://github.com/jellyfin/Swiftfin/pull/432. However, the -1003 error still corresponds to the phone being unable to find the host.
