### ISSUE TITLE
Can not display subtitles with server 10.8.0-beta3

### ISSUE THREAD

**Issue by rexzhang** [jellyfin/Swiftfin#435]
### Describe the bug

I can choose the subtitle language, but nothing will be displayed. This is true for both Chinese and English subtitles.

BTW:
- I have checked the “Force Direct Play"
- It works fine when the Jellyfin server is 10.7

### Application version

1.0.0 (74)

### Where did you install the app from?

TestFlight

### Device information

Apple TV 4K (2nd generation)

### OS version

iOS 15.4.1(19L452)

### Jellyfin server version

10.8.0-beta3(from docker hub)

**Comment by LePips** [comment]
Thank you for the issue, does this issue persist on other clients?

**Comment by sambartik** [comment]
Could #417 be related?

**Comment by LePips** [comment]
Depends if they're external subtitles and also the server version is alpha 3. The other issue hasn't been investigated yet.

**Comment by rexzhang** [comment]
> Thank you for the issue, does this issue persist on other clients?

Jellyfin Mobile(iOS) 1.4.1(5.4.1.0), Expo 39.0.0 + iOS 15.4.1 + iPhone 12 mini, It's work.

infuse 7.3.10(4085) + InfuseSync 1.4.2.0 + iPhone/AppleTV, It's work.

> Depends if they're external subtitles and also the server version is beta 3. The other issue hasn't been investigated yet.

Yes, It's external subtitles

**Comment by rexzhang** [comment]
Built-in subtitles can be displayed. If there is a built-in subtitle, it will be forced to display

**Comment by LePips** [comment]
I'll mark this as duplicate for #417.
