### ISSUE TITLE
cannot load ass subtitle when playing a m2ts file

### ISSUE THREAD

**Issue by leiguan118** [jellyfin/Swiftfin#439]
### Describe the bug

When I play a m2ts video, the ass subtitle is not shown. The subtitle option is correct，but the subtitle is not shown in the video. The subtitle is correct when playing other formats such as mkv. My subtitle language is Chinese and Japanese.

### Application version

1.0.0(75)

### Where did you install the app from?

TestFlight

### Device information

iPad mini 6

### OS version

15.4.1

### Jellyfin server version

10.7.7

**Comment by holow29** [comment]
Is this an external sub, I'm guessing? Probably related to #417

**Comment by LePips** [comment]
I will close this as a duplicate as I'm assuming an external subtitle.
