### ISSUE TITLE
Horizontal thumbs

### ISSUE THREAD

**Issue by dannymichel** [jellyfin/Swiftfin#442]
I know it might sound stupid but a huge reason I switched to Emby and ultimately Jellyfin is because next up and continue watching are horizontal thumbnails rather than vertical posters. It'd be great if that were included in swiftfin.

**Comment by pixselious** [comment]
An option to have 16:9 thumbnails in the libraries would be great too. I have a library for YouTube videos, and it just crops the thumbnails.
