### ISSUE TITLE
Picture in Picture 

### ISSUE THREAD

**Issue by ReclinesMC** [jellyfin/Swiftfin#444]
**Describe the feature you'd like**
I would like support for Picture in Picture on iOS, if possible.

**Comment by LePips** [comment]
Only possible as described in https://github.com/jellyfin/Swiftfin/discussions/324 through the native player. Not possible with VLCKit, possibly with mpv but that's for a lot later.

**Comment by ReclinesMC** [comment]
thats unfortunate
