### ISSUE TITLE
Space after Siri dictation

### ISSUE THREAD

**Issue by ReclinesMC** [jellyfin/Swiftfin#447]
### Describe the bug

1. Open SwiftFin on AppleTV
2. Enter a url to connect to via dictation
3. Connecting will fail

This happens because dictation adds a space after the url. This could easily be fixed by ignoring the space at the end.

### Application version

1.0.0 (75)

### Where did you install the app from?

TestFlight

### Device information

Apple TV 4K

### OS version

latest

### Jellyfin server version

latest

**Comment by ReclinesMC** [comment]
Small note: I believe it also happens with usernames when logging into a server

**Comment by rifffraf** [comment]
its standard behavior on iOS that a space will be added to every autocorrected word or Siri input.
