### ISSUE TITLE
TvOS Cannot scroll down on show detail screen

### ISSUE THREAD

**Issue by franta27** [jellyfin/Swiftfin#448]
### Describe the bug

On Apple TV you cannot scroll down on show list in show detail screen if the show has only one season. That's because scrolling down will select 2nd season. If there is only one you are stuck.

### Application version

1.0.0 (75)

### Where did you install the app from?

TestFlight

### Device information

Apple TV 4K

### OS version

15.4.1

### Jellyfin server version

10.7.7

**Comment by LePips** [comment]
No longer an issue due to https://github.com/jellyfin/Swiftfin/pull/492, forgot to tag this issue.
