### ISSUE TITLE
could not connect to not secure http server with a custom port

### ISSUE THREAD

**Issue by yalagin** [jellyfin/Swiftfin#449]
### Describe the bug

**Describe the bug**
could not connect to not secure http server : http://example.thddns.net:8880/
only  https://example.thddns.net:8880/ urls are allowed 
or maybe it's because I have custom port 8880 
original app also don't work 

**I get an error**
could not connect to server

**System (please complete the following information):**
 - iOS Version: 15
 - Jellyfin Expo version: 1.4.1(5.4.1.0)
 - Jellyfin Server version:10.7.7

**To Reproduce**
I am trying to add my own server (http://example.thddns.net:8880/) with  http://  not secure connection 
with custom port 8880 and it's not working. I tried Finamp and it is working

### Application version

1.0.0(58)

### Where did you install the app from?

TestFlight

### Device information

iphone 13 pro

### OS version

ios 15

### Jellyfin server version

10.7.7

**Comment by LePips** [comment]
Is this a Swiftfin or Expo issue, or both? You're also on version 58, please update to the latest version (75) through the new TestFlight link.

**Comment by yalagin** [comment]
thanks for answering 
it's both
well sorry I wrote wrong number I just downloaded new version form TestFlight

**Comment by yalagin** [comment]
well maybe problem with custom port and not secure connection in ios 
I even can not open jellyfin in iphone's  browser 
but I can open in android or in desktop
