### ISSUE TITLE
ipadOS - Tapping to skip opens the overlay

### ISSUE THREAD

**Issue by MrTimscampi** [jellyfin/Swiftfin#455]
### Describe the bug

1. Play a video
2. Tap on the screen to skip ahead
3. If you tap an odd number of times, the overlay opens

From a quick investigation, it seems the behavior is to only add to the skip count every even taps, while odd taps are ignored and just open the overlay when you stop tapping.

In contrast, YouTube does not open the overlay and takes every tap after the second one into account, adding 15s to the skipped time for each tap.

### Application version

Current TestFlight as of June 5th, 2022

### Where did you install the app from?

TestFlight

### Device information

iPad Air 2022

### OS version

15.5

### Jellyfin server version

10.7.7

**Comment by LePips** [comment]
This is more of a request. The tap behavior is intended right now just to be double tap.

**Comment by PangMo5** [comment]
Oh, it certainly looks different from Youtube in consecutive tap gestures.
If UX on Youtube is better, we can change it the same way.

**Comment by MrTimscampi** [comment]
The main thing is that the overlay tends to open on odd taps, which doesn't feel super nice :)

Changing the behavior for which taps add to the skip can be debated and was kind of an annex to the report about the overlay.  
Personally, I find it clunkier to have to always tap twice to add 15 seconds to the skip, since it requires so much more taps to skip more than 15 seconds, but I can understand the decision to have it do that (For example, skipping 1 minute forward would require 5 taps for the YouTube behavior vs 8 for Swiftfin).
