### ISSUE TITLE
[TestFlight] Apple TV cannot read video Jellyfin.Api.Helpers.MediaInfoHelper: Profile: Unknown Profile

### ISSUE THREAD

**Issue by tregouetkevin** [jellyfin/Swiftfin#457]
### Describe the bug

Hello, Apple tv cannot play video.

On web browser, video play correctly.

On IOS jellyfin Mobile, that work too

On Apple tv, the same video don't start and i have that in the log : 

Jellyfin.Api.Helpers.MediaInfoHelper: Profile: Unknown Profile

That seems to be like this bug : https://github.com/jellyfin/jellyfin/issues/3815

### Application version

1.0.0 (75)

### Where did you install the app from?

TestFlight

### Device information

Apple TV

### OS version

TVOS 15

### Jellyfin server version

10.7.7

**Comment by LePips** [comment]
Please try toggling on Force Direct Play in Settings -> Experimental -> Force Direct Play.

**Comment by tregouetkevin** [comment]
Thank, that work
