### ISSUE TITLE
Jellyfin 10.8.0 opens on iPadAir2 but not iMac or iPadPro 

### ISSUE THREAD

**Issue by swadeX** [jellyfin/Swiftfin#462]
### Describe the bug

Jellyfin 10.7.7 worked great on all devices iMac, iPadPro, iPadAir2. Both iPads are current iOS 15.5.  After installing Jellyfin 10.8 on iMac, only the iPadAir2 will open the app. Tried reset app on iPadPro, checked my ip addresses, iMac allows incoming in firewall. Even tried to reset my password but could not do that as my email address is old. Cannot figure out how to get my email address changed. BTW, the error message I receive on the iPadPro is: “We’re unable to connect to the selected server right now. Please ensure it is running and try again”. The iMac will not open at all. I tried trashing 10.8 and reinstalling. Amateur here so hopefully there is a setting(s) I an unaware of. No terminal solutions please. Thanks

### Application version

10.8.0

### Device information

IPadPro

### OS version

15.5

### Jellyfin server version

10.8.0

**Comment by LePips** [comment]
Please file in the correct repo: https://github.com/jellyfin/jellyfin

**Comment by swadeX** [comment]
No - this is Jellyfin. Sorry for my ineptitude… Been a bad day
