### ISSUE TITLE
Can transcoding be offloaded to the server?

### ISSUE THREAD

**Issue by ericswpark** [jellyfin/Swiftfin#466]
Hi all, apologies if I'm misunderstanding how Jellyfin+Swiftin works. New to the project and trying to figure out how it's all structured as I move from Plex to Jellyfin. If you see anything wrong in this issue please let me know!

My understanding right now is that Jellyfin first asks the client what type of media container/codec it supports, then transcodes "unsupported" content on the server-side before streaming it to the client, which applies on both the web-based player (connecting directly to the Jellyfin built-in webserver) and the Expo client on Android and iOS since they're a wrapper (I think?) for the webUI.

On Android, you can choose to use an external player which supports more media types and negates the need for transcoding, at the cost of decoding the file on the client-side. Android also has more media type support compared to iOS (at least, AFAIK) so transcoding is minimized and the server can directly stream the file with minimal retouching (such as remux).

For Swiftfin, I see we're currently using VLCKit to expand the list of media types that the app supports, with preliminary plans to add (or replace VLCKit with) mpv (as outlined in issue #221), since iOS's default media player only accepts a limited number of media types and codecs.

My question is, **can we add a third option that uses the built-in media player of iOS, that offloads all transcoding work to the server?** That would negate the requirement to use an external framework like VLC or mpv to play media, and get rid of a whole suite of bugs that accompany such frameworks. It would also allow for faster development since we're not waiting on frameworks to ship new features or fix bugs (such as the audio disappearing bug or the timing sync issue present in VLCKit that is blocked on the release of v4).

Other potential benefits I can think of are improved battery life (since the client no longer has to use software decoders to decode "unsupported" content) and improved performance over poor network conditions as the transcoding can dynamically adjust bitrate and other parameters depending on connection speed and client type, etc.

Again, this issue is based upon my assumptions and guesses on how the Jellyfin system works as a whole, so please let me know if I'm incorrect in any areas. Thanks!

EDIT: just to clarify, I'm proposing this as an addition to software decoding solutions in VLCKit/mpv, since some users may prefer to lessen server loads by having the client handle all decoding of media (and/or they are not restricted by battery usage or network conditions).

**Comment by LePips** [comment]
No, as you are incorrect for how transcoding works. Transcoding works entirely on the server and we are served an HLS stream for the native player.

**Comment by ericswpark** [comment]
Great, thank you for the clarification!
