### ISSUE TITLE
tvOS - No way to enable local network permissions

### ISSUE THREAD

**Issue by sebirdman** [jellyfin/Swiftfin#467]
### Describe the bug

On my phone, i can connect to my server locally after enabling "local network" in the swiftfin settings option

on tvOS - i see no settings option or way to enable this, so i can't connect via my local network. 

both apple devices are on the same network, with the same subnet and all that jazz. 

### Application version

1.0.0(75)

### Where did you install the app from?

TestFlight

### Device information

iPhone 12 Pro - apple TV 4k

### OS version

latest

### Jellyfin server version

10.8.0

**Comment by sebirdman** [comment]
uninstalled the app, reinstalled the app - magically now connecting locally! 

i still don't see any settings or local network permission - maybe tvOS doesn't have that?

**Comment by LePips** [comment]
tvOS does not have that initial prompt, it does it by default. At the same time, local network discovery was broken in 75 but will be fixed in the next release.
