### ISSUE TITLE
Adding a second server with the same name replaces the first server

### ISSUE THREAD

**Issue by JJJ-M** [jellyfin/Swiftfin#468]
### Describe the bug

I would like to add the same server twice. Once with a local ip address and a second time with a remote address (using Tailscale for example).
When adding the second server, Swiftfin shows the message "existing server" "server (server name) already exists. Add new URL?"
If I click on "add URL", it replaces the URL of the first (existing) server. It's not possible to create a second server.
The best way would be, like in Jellyfin app, to add a second server.

### Application version

1.0.0

### Where did you install the app from?

TestFlight

### Device information

iPhone 8

### OS version

ioS 15.4

### Jellyfin server version

10.8.0

**Comment by LePips** [comment]
The way that we handle it is that the same server can have two URLs, but you only choose one URL to use at a time.

When you are prompted to add a new URL to the server, it adds that URL to its list and sets the current URL to that new one.

You can select which URL to use by selecting the server and logging in with a user, and then in settings select the Server -> URL select which URL to use. It is my intention to make this flow better and more intuitive.
