### ISSUE TITLE
tvOS - Missing Audio and other libraries

### ISSUE THREAD

**Issue by HeuristicPerson** [jellyfin/Swiftfin#469]
### Describe the bug

At the top of the main window I can see "Other libraries" but if I select that option, I can only see Movies and TV Series. It's my understanding that Audio libraries are supported (based on other issues and the fact the option other libraries do exists).

### Application version

1.0.0 (75)

### Where did you install the app from?

TestFlight

### Device information

Apple TV 4K

### OS version

tvOS 15.5.1

### Jellyfin server version

10.8.1

**Comment by LePips** [comment]
Audio libraries are not supported, we are only focused on video playback at the moment.
