### ISSUE TITLE
Intros plugin support

### ISSUE THREAD

**Issue by sunjam** [jellyfin/Swiftfin#471]
**Describe the feature you'd like**
Support for [intros plugin](https://github.com/dkanada/jellyfin-plugin-intros), to play before movies and tv shows.

**Additional context**
Currently a loading icon is shown for a moment, then the intro is skipped.

Thanks for considering!

**Comment by LePips** [comment]
After some conversation with the JF team, non-web clients will only support the official API and not external plug-ins.
