### ISSUE TITLE
Widgets on iPasOS 15 not working

### ISSUE THREAD

**Issue by Chiggy-Playz** [jellyfin/Swiftfin#472]
### Describe the bug

1. Edit home screen
2. Click on add a widget
3. Scroll down to select swiftfin from the menu
4. The widget just appears blank in both preview and on home. Clicking on it opens the app, and even when app is in the background the widget stays blank
![image0 (1)](https://user-images.githubusercontent.com/49774426/178115716-16d3abde-0001-44fb-9bb3-64ec586794f1.png)

### Application version

v1.0.0

### Where did you install the app from?

Testflight

### Device information

iPad air 5th generation

### OS version

iPad OS 15.5 (19F77)

### Jellyfin server version

10.7.7

**Comment by PangMo5** [comment]
I'll check when I have time

**Comment by LePips** [comment]
They do not work because of the shared group which we do not have anymore. This is the same discussion in the top shelf view for tvOS.

**Comment by PangMo5** [comment]
Oh, I see, if we apply app groups to CoreData now, it will affect the existing data.
Wouldn't it be better to finish all related work before distributing the App Store?

**Comment by LePips** [comment]
Yes, it would be better to handle closure to release. The main problem is the entitlements for the app group as only people with App Store Connect access can get that entitlement and it makes general contributions more tedious by having to delete the App Group while developing.

**Comment by LePips** [comment]
Just for consolidation, and since I ripped out the existing widget, just going to supersede this by #545.
