### ISSUE TITLE
Tapping on tab again does not navigate to tab home

### ISSUE THREAD

**Issue by daullmer** [jellyfin/Swiftfin#475]
### Describe the bug

1. Sign in
2. Navigate on the home tab to a movie / tv show
3. Optional: Change Tab to All Media
4. Go to home tab
5. Press on the home tab again and expect to get navigated to the home view

It works like this on any other tab-based app.

### Application version

1.0.0(75)

### Device information

iPhone 12

### OS version

iOS 15.5

### Jellyfin server version

10.8.1

**Comment by LePips** [comment]
This is not a bug, this is a shortcoming of SwiftUI. However, I recently did work on our coordinator package to provide such functionality: https://github.com/rundfunk47/stinsen/pull/77
