### ISSUE TITLE
Add an option to change the app's language

### ISSUE THREAD

**Issue by pixselious** [jellyfin/Swiftfin#485]
Please add an option to change the app's language

**Comment by PangMo5** [comment]
I'm sorry, but I didn't understand. Could you explain it in more detail?

**Comment by LePips** [comment]
We can just allow the user to select which strings to grab from our available languages: `en.lproj`, `sv.lrpoj`, `ko.lproj` and so on. This won't change System strings, like "Back" on the navigation bar, so we will have to see where these System strings are and how many.

Something like:
https://stackoverflow.com/questions/29985614/how-can-i-change-locale-programmatically-with-swift

**Comment by LePips** [comment]
After thinking about this today, I would prefer users to the native iOS functionality you shared.
