### ISSUE TITLE
Do not navigate to the same episode when the current route is the same episode

### ISSUE THREAD

**Issue by chepe263** [jellyfin/Swiftfin#488]
**Describe the feature you'd like**
When I see the page for a show's seasson, there's this vertical list of episodes. You can tap one and you are taken to the detail. If you tap the same episode again, you navigate to the same episode detail. You can keep doing this and the navigation will happen.
At the end you would have to hit back several times to return home.

Could you check the current route and if the current route (for episode, movie, etc.) is the same as the one you are about to navigate, cancel the navigation?

**Additional context**

**Comment by LePips** [comment]
Navigation of the app is changed in my work https://github.com/jellyfin/Swiftfin/pull/452. However, the idea of not navigating to a page because "you may already be on the page" is not something that should be done.
