### ISSUE TITLE
Series Items are clipped when focussed in tvOS

### ISSUE THREAD

**Issue by adamjcampbell** [jellyfin/Swiftfin#489]
### Describe the bug

1. Go to a series
2. Select a season

Expected: Season is scaled to a size of `1.1` with all content fully visible
Actual: Content is clipped so that you cannot see number of unplayed episodes or the season and year text properly

![clipped](https://user-images.githubusercontent.com/5327203/179734921-08cb6467-15ae-49bd-be34-30f8a6133eaf.png)

### Application version

1.0.0 (75)

### Where did you install the app from?

TestFlight

### Device information

Apple TV 4K

### OS version

tvOS 15.4

### Jellyfin server version

10.8.1

**Comment by adamjcampbell** [comment]
I'll throw up a PR for this even though it may be included in @LePips's PR as I've already done it

**Comment by LePips** [comment]
I closed the PR, but I'll close this issue when I finish my work.
