### ISSUE TITLE
Resume watching use title cards instead of series backdrop

### ISSUE THREAD

**Issue by jmvbrown** [jellyfin/Swiftfin#494]
Option to use the title card for the episode instead of the series backdrop

**Comment by jmvbrown** [comment]
Yeah, so I have title cards I’ve created for episodes so it is like the series backdrops just episode specific.
![55A82A0E-4560-453C-A836-820E6174AB17](https://user-images.githubusercontent.com/45808940/180042356-2d7ec30c-ed67-4f63-8f69-fb035dabe9c9.png)

**Comment by jmvbrown** [comment]
I also know this is an option on the other Jellyfin iOS app so just wanted to see if it was going to be an option on Swiftfin

**Comment by LePips** [comment]
Oh, the portrait photos. This can be an option!

**Comment by jmvbrown** [comment]
Thank you!
