### ISSUE TITLE
Skip Intro Plugin Support

### ISSUE THREAD

**Issue by matthew-jones-uk** [jellyfin/Swiftfin#495]
**Describe the feature you'd like**
There's a plugin that offers "intro skipping" support: https://github.com/ConfusedPolarBear/intro-skipper. To make it work usually a modified web interface is required, however that won't work with this - could support be built in?

**Additional context**
I believe there are talks to make this plugin owned by the Jellyfin family, perhaps if it goes through maybe this could be considered more seriously (I'm not sure support for a 3rd party plugin would be within the scope of this app).

Would solve requests such as https://github.com/jellyfin/Swiftfin/issues/367

**Comment by LePips** [comment]
We on the Jellyfin team have been talking a lot about how to properly support this on the server, along with other types of "skips". This will have to wait until the server officially has that functionality.

**Comment by The-Math-God** [comment]
then why not implement it as a temporary solution for people
