### ISSUE TITLE
Some Chinese subtitles dispaly as 口(▢ a hollow square)

### ISSUE THREAD

**Issue by HySand** [jellyfin/Swiftfin#497]
### Describe the bug

Only a few of words show wrongly.
e.g.
![IMG_1058](https://user-images.githubusercontent.com/77628540/180499492-400d99e0-e9d0-4bcd-bc69-81c51a83dbda.PNG)
ARCANE S1E4 12:23, using Subrip subtitle. The 口 in the subtitle should be "稳", which display correctly on Jellyfin web client:
![无标题](https://user-images.githubusercontent.com/77628540/180501755-0e3d88d7-195d-4848-99bc-82f5b0c54234.png)
Missing font?

### Application version

1.0.0(76)

### Where did you install the app from?

TestFlight

### Device information

Both iPhone XS MAX and iPad 2019

### OS version

IOS 15.6, iPad OS 15.6

### Jellyfin server version

10.8.1 unofficial docker(nyanmisaka/jellyfin) which adds addtional chinese support.

**Comment by PangMo5** [comment]
Thank you for leaving the issue.
We will support setting the subtitle font.

**Comment by LePips** [comment]
Sadly, this isn't necessarily fixed by choosing a different font. I only tested a few fonts on the same media and still get the box or even a different character in that space. Due to this finding, this is simply a VLCKit issue and we can't do anything about it.

![IMG_9466](https://user-images.githubusercontent.com/20747774/181811024-411d8607-d88d-4a08-9b41-68120dfea77a.PNG)

**Comment by HySand** [comment]
> Sadly, this isn't necessarily fixed by choosing a different font. I only tested a few fonts on the same media and still get the box or even a different character in that space. Due to this finding, this is simply a VLCKit issue and we can't do anything about it. However, you may be able to find a font that displays it correctly that I didn't test with.
> 
> ![IMG_9466](https://user-images.githubusercontent.com/20747774/181811024-411d8607-d88d-4a08-9b41-68120dfea77a.PNG)

I think that may be caused by the wrong font.
Swiftfin use fonts for traditional Chinese even when choosing a simplified Chinese subtitle.

Here is what i found form a font site.
Simplifiled Chinese words with PingFang SC Medium (Simplified Chinese font come with Apple mobile devices)
![image](https://user-images.githubusercontent.com/77628540/182005755-72de76d8-1440-4a6d-a50d-833eb78d2fd5.png)
Simplified Chinese words with PingFang TC Medium (Traditional Chinese font come with Apple mobile devices)
![image](https://user-images.githubusercontent.com/77628540/182005761-cdbb4a1f-765c-422b-81f0-dade520aea80.png)
Traditional Chinese words with PingFang TC Medium (Traditional Chinese font come with Apple mobile devices)
![image](https://user-images.githubusercontent.com/77628540/182005771-7b2ef86e-17d0-476e-b35b-6a4fbe482358.png)

There‘s no corresponding words (like "稳") for Simplified Chinese in Traditional Chinese fonts. That's why it display worngly when i select the subtitle in Simplified Chinese.
You can see some differences between two fonts from the last word “全”.
PingFang SC
![image](https://user-images.githubusercontent.com/77628540/182005925-c51b6e7f-2497-4778-8619-36993ff8aded.png)
PingFang TC
![image](https://user-images.githubusercontent.com/77628540/182005931-234df094-c71c-46e1-912c-5deb7bd671a5.png)

**Comment by LePips** [comment]
Thank you for your insight as I don't know the differences between Simplified and Traditional as an only English speaker. You may be able to find a font to fix the characters in the next release then! 🎉

**Comment by zhoudongliang** [comment]
求字幕的字体和颜色设置方法
19717610@qq.com

**Comment by petronny** [comment]
I find that this issue only happens when using the Subrip subtitles (.srt).
After simply converting Subrip subtitles to ASS subtitles with ffmpeg all words display fine, which can be used as a workaround.
