### ISSUE TITLE
What's the trick to force updating Swiftfin on tvOS?

### ISSUE THREAD

**Issue by MichlW** [jellyfin/Swiftfin#499]
I recognized that there was a new beta release of Swiftfin in the last week and I installed it immediately on my iPhone and my iPad.
But I now need some help to update my tvOS version too.
Whatever I tried, it's only version 75 that will be installed.
Where or how can I force updating to the new version 76?
Thanks in advance!

**Comment by LePips** [comment]
We have not released the next version of tvOS yet due to some submission issues. TestFlight should still say 75.
