### ISSUE TITLE
UDP Discovery Framework Not Included in tvOS Build

### ISSUE THREAD

**Issue by anthonylavado** [jellyfin/Swiftfin#504]
### Describe the bug

When building the tvOS archive, the UDP Discovery framework included as part of #474 is not added to the bundle.

This causes the build to fail validation from Apple with this error:
>ITMS-90562: Invalid Bundle - One or more dynamic libraries that are referenced by your app are not present in the dylib search path.

Reference:
https://medium.com/360learning-engineering/resolving-itms-90562-invalid-bundle-email-from-the-app-store-d4a1030418e5

**Comment by LePips** [comment]
Will be removed for general socketing capabilities. Planning on using [SwiftNIO] (https://github.com/apple/swift-nio).
