### ISSUE TITLE
Music media won’t show

### ISSUE THREAD

**Issue by NeonSupernova** [jellyfin/Swiftfin#505]
### Describe the bug

I have two libraries, one for videos and one for music. The video library show all my media perfectly fine. The music library, however shows nothing. I know that the music library does indeed work, because I can use it just fine with other clients. All the files are mp3. Whether this is an issue with the swiftfin or if it’s not implemented yet, idk. 
![29921882-0AD0-4D7A-A5D1-9ADB746DBF14](https://user-images.githubusercontent.com/78397254/181864874-3862c961-02c2-4a0f-9c60-fac8cdc3ef9e.png)
![6FE7DBA7-4A02-438C-9EB3-35FBF4BCC8AA](https://user-images.githubusercontent.com/78397254/181864875-6d50b4c4-ba2c-49ed-a5a5-3dfdeb70a998.png)
Top: Jellyfin
Bottom: Swiftfin

### Application version

1.0.0 (76)

### Where did you install the app from?

TestFlight

### Device information

iPhone SE v2

### OS version

iOS 16 Developer beta

### Jellyfin server version

10.8.1

**Comment by LePips** [comment]
We only support video media.

**Comment by leaf-ts** [comment]
> We only support video media.

will Music be supported in the future?
This would be my app to have to AppleTV so I won't have to fiddle around with my phone etc.

**Comment by LePips** [comment]
Maybe, but not for a long time.

**Comment by NeonSupernova** [comment]
I don't do much swift, but is adding audio media difficult, or is it just because the video features are what's being worked on right now?

**Comment by LePips** [comment]
We are only focused on video media right now.

**Comment by dibsies** [comment]
> Maybe, but not for a long time.

Long time as in 6-12 months, or more 2-3+ years? Trying to get an idea of how long it will be until I can finally abandon Plex.

**Comment by LePips** [comment]
When it's implemented. I've been giving it some more thought though.

**Comment by extraslute** [comment]
> > Maybe, but not for a long time.
> 
> 
> 
> Long time as in 6-12 months, or more like 2-3+ years? Trying to get an idea of how long it will be until I can finally abandon Plex.

You could also try using the DLNA or UPNP service and using something like the VLC app, MrMC, or other DLNA clients to access this media. I ditched and deleted my Plex account earlier this year and will never go back. PS3s are also very good at accessing media hosted by JELLYFIN.
