### ISSUE TITLE
iOS 16 Dev Beta Not Playing Videos

### ISSUE THREAD

**Issue by Fiji05** [jellyfin/Swiftfin#507]
### Describe the bug

I have Jellyfin up and running and have double checked by watching movies on web. However, on the Swiftfin app on iOS 16 dev beta, videos do not play. I am able to browse correctly, and everything else seems to be working fine, but once I try to play a video, it moves my device into landscape mode and stays on a black screen. The video does not play, and the app becomes unresponsive on this black screen, I am not able to do anything unless I quit the app and reload it.

### Application version

1.0.0 (Build 74)

### Where did you install the app from?

TestFlight

### Device information

iPhone 13

### OS version

iOS 16 Developer Beta 4

### Jellyfin server version

10.8.1

**Comment by LePips** [comment]
Do you have TLS 1.3? The behavior of being able to navigate just fine but having a blank screen for playing mirrors that issue.

**Comment by Fiji05** [comment]
> 

Yes, I do have TLS 1.3.

**Comment by LePips** [comment]
VLCKit does not work with TLS 1.3. You will have to step down to 1.2 for video playback to work.
