### ISSUE TITLE
Move SwiftFormat/Swiftgen to SPM Plugins

### ISSUE THREAD

**Issue by LePips** [jellyfin/Swiftfin#509]
Instead of installing these through Carthage look at using the new SPM Plugins. SwiftFormat at time of writing does not have support for it but SwiftGen does.

**Comment by PangMo5** [comment]
Yeah, many third party will soon support the SPM plugins 😁

**Comment by LePips** [comment]
Been a while and I just took a look at how SMP plugins are used in Xcode currently and it looks like it's a pain, so idc to do this.
