### ISSUE TITLE
Media View

### ISSUE THREAD

**Issue by G10vanni74** [jellyfin/Swiftfin#511]
On the Media View

Is it possible to delete the line where the cover of the media and its sypnosis is, because below this line this cover comes back again in TV show

The media page is very beautiful but a little too refined, can we see a button appear for an option such as adding to or deleting

For example, on Infuse  page where the sypnosis is next to the tabs with a LOGO above ,rating .....!!!

thanks again for your work

![Example](https://user-images.githubusercontent.com/76523016/183110450-7209e209-1f74-4fb2-a7a6-f9429a30d18f.png)

**Comment by LePips** [comment]
This is done in https://github.com/jellyfin/Swiftfin/pull/492. Regarding customization of individual components, this will come long after release if I think about it.
