### ISSUE TITLE
Support AV1 codec direct stream

### ISSUE THREAD

**Issue by kanersps** [jellyfin/Swiftfin#513]
I saw an issue about a year ago that mentioned that VLCKit didn’t support AV1 yet. But LibVLC has for a bit now and VLCKit has updated as well, I assume it should work fine now.

Currently Swiftfin requests a transcode for AV1 streams.

**Comment by LePips** [comment]
VLCKit currently hasn't released 3.4.1 and we won't update to a beta build for it. This could be a part of https://github.com/jellyfin/Swiftfin/issues/296.
