### ISSUE TITLE
Screen looks like "locked" if clicking before the animation ends

### ISSUE THREAD

**Issue by HySand** [jellyfin/Swiftfin#514]
### Describe the bug

1.Play any video
2.Click the screen
![E7F1EB78-4976-4010-B78C-5CC82F456FF2](https://user-images.githubusercontent.com/77628540/183267165-74490ad3-eb9d-4bf9-83c3-7961f63210b3.png)
3.Now click left(right) of screen to hide the buttons
4.Click right(left) of screen after the fade out animation starts but before it ends.
5.The screen is "locked" for seconds.
6.If you return to home before it recovery, the whole app stuck untill you kill it.

### Application version

1.0.0(76)

### Device information

iPhone XS Max

### OS version

IOS 15.6

### Jellyfin server version

10.8.2

**Comment by PangMo5** [comment]
Oh, I went through that bug, but I couldn't fix it because I didn't know the exact way to reproduce it.
I'll check. Thank you.
