### ISSUE TITLE
Mp4 with mo3 codec has no sound

### ISSUE THREAD

**Issue by GrandVizierNappa** [jellyfin/Swiftfin#523]
No sound with the following codec on mp4 file

Audio
Title: MP3 - Stereo - Default
Language: und
Codec: MP3
Codec tag: mp4a
Layout: stereo
Channels: 2 ch
Bitrate: 192 kbps
Sample rate: 48000 Hz
Default: Yes
Forced: No
External: No

all others with an AAC codec audio works fine

**Comment by LePips** [comment]
#296
