### ISSUE TITLE
Cant select episode on TvOs

### ISSUE THREAD

**Issue by userbradley** [jellyfin/Swiftfin#529]
### Describe the bug

1. Open app
2. click `TV`
3. Click TV Show
4. Click `Down` on trackpad
5. [Expected behaviour] Select Season
6. [Expected behaviour] Be able to select `Season` or `Episode` to watch
---

Not sure if this is PEBCAK, but I don't seem to be able to select what Episode or Season to watch on the Apple TV

### Application version

1.0.0

### Where did you install the app from?

TestFlight

### Device information

Apple TV 4K A2169

### OS version

tvOS: 15.6 (19M65)

### Jellyfin server version

lscr.io/linuxserver/jellyfin:latest (Arm)

**Comment by LePips** [comment]
No longer a concern with https://github.com/jellyfin/Swiftfin/pull/492 but won't be out for a bit.

**Comment by userbradley** [comment]
@LePips You ledge! Let me know if you need me to do any testing!
