### ISSUE TITLE
Not show list of content on appletv

### ISSUE THREAD

**Issue by xavisbd** [jellyfin/Swiftfin#540]
### Describe the bug

The app not show lists of contents. I have only contents in “other” sections . With jellyfin of ipad it works perfectly.

### Application version

1.0.0(79)

### Where did you install the app from?

TestFlight

### Device information

Appletv 

### OS version

TvOS 15.6

### Jellyfin server version

10

**Comment by LePips** [comment]
If you can't see any media then your library isn't set up properly. To help we only support video media.
