### ISSUE TITLE
iOS/iPadOS - Flashing Player Menu

### ISSUE THREAD

**Issue by LePips** [jellyfin/Swiftfin#559]
On iOS/iPadOS the player sets some property which causes the `Menu` of the overlay to flash as it reloads.

<details>
<summary>iOS - Example</summary>

https://user-images.githubusercontent.com/20747774/188299234-55731d6e-2f87-4617-a242-ca1a3b1a9cfc.mov
</details>

This will be fixed when I rewrite how playback is handled.

**Comment by chepe263** [comment]
When you open a menu item with menu items inside, the main menu that flashes grows vertically
