### ISSUE TITLE
The new feature seems not work for Chinese?

### ISSUE THREAD

**Issue by HySand** [jellyfin/Swiftfin#570]
### Describe the bug

Nothing changes after selecting different Chinese fonts. #497
I tried PingFang SC,PingFang TC,PingFang HK and their different styles from Ultrallight to Semibold but they display like the same.

### Application version

1.0.0(77)

### Device information

iPad Pro 11inch

### OS version

IOS 15

### Jellyfin server version

10.8.1

**Comment by LePips** [comment]
Sorry, there's nothing we can do on this part. If the font doesn't seem to work that's on the OS.
