### ISSUE TITLE
iOS 16 - Persistent Home Indicator

### ISSUE THREAD

**Issue by MikeO7** [jellyfin/Swiftfin#582]
### Describe the bug

1. Play media

I expect the white swipe bar to fade but it remains persistent during playback

![1504CC70-5EE1-4027-B5DE-252B1B460231](https://user-images.githubusercontent.com/7740954/189809033-8b430125-7354-48d6-9d31-6283657e287c.jpeg)

### Application version

1.0.0(78)

### Where did you install the app from?

TestFlight

### Device information

12 pro max

### OS version

iOS 16

### Jellyfin server version

10.8

**Comment by monkhaze** [comment]
I'm having the same issue on an iPhone 13 Pro max in ios 16 with swiftfin 1.0.0 (78).

I tried switching to the native player but that didn't seem to help.

**Comment by TopoR** [comment]
Yep, only way (until an update) is to use [Guided Access](https://support.apple.com/en-us/HT202612).

**Comment by matthew-jones-uk** [comment]
Also got the same issue. Tried the native player with no luck too. 

iPhone 12 
iOS 16.1

**Comment by Bonanzameh** [comment]
Adding some weight to this. Same issue; current practical workaround is to use another app like infuse, but we love Jellyfin and hope for this issue to be resolved soon.

**Comment by mrmodius** [comment]
Also getting this, using guided access for now but would love a fix!

**Comment by kalafalas** [comment]
I'm having the same bug. This (along with downloads) are the final piece of the puzzle to ditch infuse. Love the app, let us know how we can help!

**Comment by cupcakearmy** [comment]
Same here

**Comment by diogox** [comment]
Having the same issue. Would love a fix 🙇

**Comment by taedium8vitae** [comment]
I have the same issue on an IPhone 14 Pro, iOS 16.3.1, Swiftfin 1.0.1 (78)

**Comment by kaviseshan09** [comment]
Still having this bug on iPhone 12 iOS 16.3.1

**Comment by REHCTELF-FLETCHER** [comment]
Yep exact same issue, so annoying as the rest of the app is near perfect and beautifully designed but this one issue make it unusable

**Comment by cosmonet-fr** [comment]
We have this bug in IPAD Air 4 with IOS  16.1.

**Comment by zeroquinc** [comment]
Any update on this? I still have it and it's the only reason I can't use Swiftfin.

**Comment by Dario-Mantegazza** [comment]
This issue still exists on the latest version of both ios and swiftfin. @LePips, may I ask why is this issue closed? Did I missed a setting or something for avoiding this?
Thanks anyway for the great effort 🙂, this is just a minor problem.

**Comment by taedium8vitae** [comment]
> This issue still exists on the latest version of both ios and swiftfin. @LePips, may I ask why is this issue closed? Did I missed a setting or something for avoiding this? Thanks anyway for the great effort 🙂, this is just a minor problem.

Hey, the issue is fixed but only on the code on github. The version of the app on the App Store is way behind in terms of features and, I guess like everybody, I am also waiting for a well deserved update :)

**Comment by hox** [comment]
> Hey, the issue is fixed but only on the code on github. The version of the app on the App Store is way behind in terms of features and, I guess like everybody, I am also waiting for a well deserved update :)

Do we know what is preventing the iOS app from being updated, and/or when it will be updated? I see the last update to it was more than 1 year ago, it's quite sad to see issues like these already fixed in source but not the released iOS versions.

**Comment by mrmodius** [comment]
> > Hey, the issue is fixed but only on the code on github. The version of the app on the App Store is way behind in terms of features and, I guess like everybody, I am also waiting for a well deserved update :)
> 
> Do we know what is preventing the iOS app from being updated, and/or when it will be updated? I see the last update to it was more than 1 year ago, it's quite sad to see issues like these already fixed in source but not the released iOS versions.

I've been subscribing to Infuse whilst we wait for an update, it's a shame that app store releases aren't as frequent as we'd like but it does mean when there is an update it'll be substantial.
