### ISSUE TITLE
tvOS - Subtitle Font

### ISSUE THREAD

**Issue by rexzhang** [jellyfin/Swiftfin#584]
**Describe the feature you'd like**

Add subtitle font settings in tvOS as the iOS version

**Additional context**

iOS version: TestFight 1.0.0(78)
tvOS version: TestFight 1.0.0(79)

**Comment by rexzhang** [comment]
![image](https://user-images.githubusercontent.com/238707/198873110-cc892206-c2a3-4d6b-8dc5-56edfc5e32e8.jpeg)

Change font maybe is a solution

**Comment by LePips** [comment]
Changing the font would not fix that issue, as found in https://github.com/jellyfin/Swiftfin/issues/497 and https://code.videolan.org/videolan/VLCKit/-/issues/635.
