### ISSUE TITLE
Can't identify well if transcoding is needed

### ISSUE THREAD

**Issue by Matzoh** [jellyfin/Swiftfin#597]
### Describe the bug

When I access jellyfin in the field, I use the tailscale group intranet for p2p hole punching, so my ip address is intranet.

The broadband is not enough uplink and I need to transcode the playback, if I don't transcode the playback will be very laggy.

Found that using Swiftfin does not automatically transcode for me (ffmpeg on the server side is not started), using the old jellyfin ios client I can manually select the bitrate, for example 1080p 20Mbps.

### Application version

1.0.0(78)

### Where did you install the app from?

TestFlight

### Device information

iPhone13 Pro max 

### OS version

iOS 16.0 (20A362)

### Jellyfin server version

Windows Server 10.8.4

**Comment by LePips** [comment]
Duplicate https://github.com/jellyfin/Swiftfin/issues/184
