### ISSUE TITLE
ios端出现字幕无法下滑问题

### ISSUE THREAD

**Issue by bactdt** [jellyfin/Swiftfin#598]

**Comment by LePips** [comment]
I apologize, but I can only take issues in English.

**Comment by QiuYueBaiJXW** [comment]
> No description provided.
把视频暂停 然后就可以下滑字幕了

**Comment by QiuYueBaiJXW** [comment]
> I apologize, but I can only take issues in English.

He said that he cant choose subtitle, I told him to pause the video and then he can slide the ‘Subtitle’ menu to choose.
