### ISSUE TITLE
Missing Music Support

### ISSUE THREAD

**Issue by nicknick923** [jellyfin/SwiftFin#6]
Let's add Music Library support

**Comment by ThomasBeckham** [comment]
This should really be reconsidered, Swiftfin is the only available Jellyfin client for Apple tv so its currently impossible to use Jellyfin to stream music to any apple tv.

**Comment by bwlok** [comment]
I agree, would be really helpful to be able to stream music on the Apple TV

**Comment by JPKribs** [comment]
Hey all, please see our library support page here:

https://github.com/jellyfin/Swiftfin/blob/main/Documentation/libraries.md

Music is on our list but our existing TV / Movies needs a bit of love first. Additionally, tvOS needs some work to get our next release out the door which takes priority over new libraries.

That's to say, Music _should_ eventually make its way to Swiftfin but we have some other items that we need to address first. As an entirely volunteer driven project, it's difficult to provide timelines or estimates and I'm sorry I cannot provide one at this time. That being said, we appreciate everyone's patience in the interim!

As there are library support updates I will be sure to keep that documentation up to date!
