### ISSUE TITLE
tvOS Builds

### ISSUE THREAD

**Issue by rekonnected** [jellyfin/Swiftfin#601]
I've seen it mentioned in a couple other issues that tvOS builds haven't been uploaded due to "issues" but I haven't seen anyone mention what those issues are, since tvOS is now several updates behind the mainline builds and there are a few issues mentioning tvOS that have been closed yet the actual fix unreleased for tvOS (#529, #592 are examples), I was wondering if anyone could explain what the issues specifically are, that way perhaps more people could try to take a look at them.

Is the issue with actually submitting the app to TestFlight? Is Apple rejecting the submissions for some reason?

**Comment by LePips** [comment]
These issues actually come from me where I don't accept the state of the project to be released. I'd much rather wait to fix some things than deliver a bad product and get a bunch of complaints.

**Comment by rekonnected** [comment]
Fair enough, thank you!
