### ISSUE TITLE
[TV OS] Apple tv 4k 64gb impossible down tiles

### ISSUE THREAD

**Issue by mabed-fr** [jellyfin/Swiftfin#602]
### Describe the bug

Hello, I recently installed the application on my apple tv 4k tvos 16 and i watch for certain series a problem of moving down when the tiles are not aligned this phenomenon even occurs when the series has a long description I upload a video

https://photos.app.goo.gl/BSby5XHDBvWTuCvd9

### Application version

1.0.0

### Where did you install the app from?

TestFlight

### Device information

appletv 4k 64gb

### OS version

tv os 16

### Jellyfin server version

10.8.5

**Comment by LePips** [comment]
These screens have been changed but just not released yet.

**Comment by mabed-fr** [comment]
Thank
