### ISSUE TITLE
increase the Zoom effect  for the selection ,  please 

### ISSUE THREAD

**Issue by G10vanni74** [jellyfin/Swiftfin#605]
Hi 

When I select a media, that expands compared to the one that is not chosen, logical
it's just my opinion but can we increase the size of the icon of the media selected in the home, TV and movies pages so that it is more obvious to us, more effect because between the selection and the non-selection there is not much difference .

A zoom effect like plex, apple tv app or Infuse would be great

Thanks

**Comment by LePips** [comment]
I know what you mean and this is somewhat mitigated in work that has been done but not released yet. The views that are used by other apps are impossible to wrap in SwiftUI, so we can only do so much ourselves.
