### ISSUE TITLE
Admin Dashboard

### ISSUE THREAD

**Issue by bwlok** [jellyfin/Swiftfin#608]
Add the admin Dashboard that's already available on the website and AppStore app

![image](https://user-images.githubusercontent.com/65543013/196376821-ef43e274-2aa3-482e-9c99-38a12e06d145.jpeg)

**Comment by JPKribs** [comment]
So this is very very early but I was taking a crack at this My big question is what are people looking from for the 'admin dashboard' in Swiftfin? Is it primarily just the Active Devices and Scan Library? Or do people want to use Swiftfin to change settings / update users / update libraries? Here is what my screen look likes right now: 

![Simulator Screenshot - iPhone 15 Pro - 2024-09-04 at 22 03 54](https://github.com/user-attachments/assets/cfa21266-58cf-4153-bd2a-6185df9c92e3)

The red bars are covering the usernames but those are there.

**Comment by sjorge** [comment]
Active Sessions, Scan Library and start a scheduled task is what I sometimes use on my phone. In order of most -> least used.

**Comment by bwlok** [comment]
Same here mostly Scan Library for me

**Comment by JPKribs** [comment]
Please see https://github.com/jellyfin/Swiftfin/pull/1230

This PR includes:

1. Active Sessions
*LOCKED TO ADMINS ONLY*
2. Scan Library
3. Restart Server
4. Shutdown Server

I see a route for adding scheduled tasks that shouldn't be too difficult but I have a feeling this current PR is going to have some revisions. I'm going to focus on getting this cleaned up and merged then I will look at Scheduled Tasks at a later date.
