### ISSUE TITLE
Issue playing HDR content on Apple devices

### ISSUE THREAD

**Issue by sul4bh** [jellyfin/Swiftfin#610]
### Describe the bug

I am trying to play an HDR video with “Native Player” and “Force Direct play” experimental features turned on. I only get audio but no video. Same behavior on ios, ipados and tvos. Web client plays the video perfectly. See screenshot below:
![F06FC752-B948-4370-85FC-91B4EA9D4E65](https://user-images.githubusercontent.com/109486/197017626-66d3f206-3eaa-4087-883a-a541e9571293.jpeg)

Any thoughts on what is going on and if a fix is possible/planned?

### Application version

1.0.0 (78)

### Where did you install the app from?

TestFlight

### Device information

Iphone 14, ipad pro, apple tv 4k 1st gen

### OS version

Latest

### Jellyfin server version

10.8.5

**Comment by LePips** [comment]
I will not be taking any issues regarding the native player: https://github.com/jellyfin/Swiftfin/discussions/324

This may be related: https://github.com/jellyfin/Swiftfin/issues/296

**Comment by sul4bh** [comment]
@LePips 
Sorry for posting a message in a closed issue but I was able to fix this issue in a local build of Swiftfin and I have a proposal.

So I am wondering if you will take a PR that adds a new experimental setting "HDR profile" that simplifies profile generation in `DeviceProfileBuilder.buildProfile()` with a focus on supporting HDR videos? I know there is an ongoing effort to improve profile builder so this new setting can be a temporary fix. What are your thoughts?

**Comment by sul4bh** [comment]
@LePips please review the PR to fix this issue at your convenience: https://github.com/jellyfin/Swiftfin/pull/623

**Comment by n0thing2speak** [comment]
I have the same problem, I hope jellyfin can strengthen the ability of dirct streaming play, which can greatly reduce the cost of setting up the server.

**Comment by holow29** [comment]
@sul4bh Have you had any luck using native player to play anthing HEVC or 4K on Apple TV? I'm trying to work on the device profiles, and it is so strange because iOS works fine, but tvOS does not for me.

**Comment by sul4bh** [comment]
@holow29 I just checked and I have HDR running on iOS, macOS and tvOS. I have native player and fmp4 experimental features turned on. Server is on Version: 10.8.9.

**Comment by holow29** [comment]
@sul4bh Thank you; that is helpful to know. If it isn't too much trouble, could you please:

- Switch your Apple TV to "4K SDR" mode under Settings->Video and Audio->Format
- Make sure "Match Dynamic Range" is set to "Off" under Settings->Video and Audio->Match Content->Match Dynamic Range
- Try to play a 4K HDR file and tell me what happens

I am guessing you will see a 🚫 at the bottom of the screen, but I'd like to make sure.
I thought the native player could do tonemapping HDR->SDR, but I'm not sure how/if that is something we can use. In HLS specs, Apple seems to specify that an SDR stream must accompany HDR content.

**Comment by sul4bh** [comment]
@holow29 
You are right. I do see 🚫 and there is no audio and video.

There is “Media Stream Validator” you can find here to verify the spec: https://developer.apple.com/documentation/http_live_streaming/using_apple_s_http_live_streaming_hls_tools

I just noticed they have other tools there to help create a spec conforming hls playlist. Something I want to play with later today!
