### ISSUE TITLE
Seasons do not appear when first looking at a show

### ISSUE THREAD

**Issue by tknx** [jellyfin/Swiftfin#611]
### Describe the bug

1. Go to any show
2. Look at seasons
3. See NR until you click on the season drop-down whereupon it loads the actual episodes 

![B6E17ECF-7270-4C96-8747-3968ED0D1B35](https://user-images.githubusercontent.com/29260341/197362553-b97dac89-051f-4023-a2e8-7aa2f21e5544.png)

### Application version

1.0.0

### Where did you install the app from?

TestFlight

### Device information

iPhone 14 pro max

### OS version

iOS 16.1

### Jellyfin server version

Latest

**Comment by TopoR** [comment]
It's appears to me, that newer Jellyfin server versions changed something. It worked as intended on a version prior current app build.

**Comment by KNIX3** [comment]
I can confirm that I also have this issue.
