### ISSUE TITLE
Backdrop and Thumbnail are the same

### ISSUE THREAD

**Issue by G10vanni74** [jellyfin/Swiftfin#615]
HELLO 

Please Ethan find a solution like the the first time to add an option to use a backdrop different from thumbnail because, I looked for all thumbnails of my videos and today I have to remove them all because they appear twice with the Logo

Is this update planned ?

Thanks

**Comment by LePips** [comment]
iirc this issue was about the tvOS cinematic item selector on the home screen also using the thumb. This is no longer an issue.
