### ISSUE TITLE
TVOS UI Lag and Refresh

### ISSUE THREAD

**Issue by eximo84** [jellyfin/Swiftfin#619]
New update is really laggy when browsing and moving between items. 

Also refresh button is missing. Not sure if this now built in but marking an episode as watched doesn't make the next one appear in the next up section.

**Comment by Jpkribs** [comment]
Have the same issue. If someone could point me towards where logs might be I'd be happy to forward those along if that would help!

**Comment by psyciknz** [comment]
yep this.  Being able to turn off backgrounds might make it a little quicker.  But navigation is a bit of a slow mess.

**Comment by LePips** [comment]
My bad, I forgot to remove the link to this in my PR.

**Comment by middleagedman** [comment]
Is this every going to get updated?   It's been 3 years.. Kind of annoying to have to close the app everytime I want to see what new items are in my lists on tvOS
