### ISSUE TITLE
Picture in Picture

### ISSUE THREAD

**Issue by Jpkribs** [jellyfin/Swiftfin#620]
Definitely a lower priority. Unsure if this feature exists in VLCKit or if this would have to be Native Player only?

**Comment by LePips** [comment]
VLCKit does not support PiP and the background for PiP with the native player is here: https://github.com/jellyfin/Swiftfin/discussions/324

**Comment by nbitzz** [comment]
I'm not an iOS dev & haven't looked into it much, but at a glance, [VLCKit now has PiP](https://code.videolan.org/videolan/VLCKit/-/issues/582) -- is there any possibility that the Swiftfin player may receive PiP support in the future?

**Comment by JPKribs** [comment]
> I'm not an iOS dev & haven't looked into it much, but at a glance, [VLCKit now has PiP](https://code.videolan.org/videolan/VLCKit/-/issues/582) -- is there any possibility that the Swiftfin player may receive PiP support in the future?

Unfortunately, PiP is only available in VLC version 4, which I believe is an unstable (development) release. We are using 3.6 which is their current stable release. When 4.X becomes their official, stable channel this may be up for consideration but for now this is a more likely direction for us to go down: https://github.com/jellyfin/Swiftfin/issues/221

Funny enough, you can see in that issue there is some discussion about VLCKit 4.X coming out "soon" back almost 4 years ago. Here is the page we use for getting our compiled version of VLCKit for our app, as provided by VLC:

https://code.videolan.org/videolan/VLCKit/raw/master/Packaging/MobileVLCKit.json

You can see that 3.6.0 is our most recent version available at this time.
