### ISSUE TITLE
tvOS - Movies library empty - but not on iphone

### ISSUE THREAD

**Issue by psyciknz** [jellyfin/Swiftfin#621]
### Describe the bug

1. Go to TV Shows, populates
2. Go to Movies - library is empty.
3. Switch to jelly fin web site, movies library is populated.
4. Switch to ios jellyfin client, movies library is populated

### Application version

1.0.0(74) I think

### Where did you install the app from?

TestFlight

### Device information

Apple tv and apple tv 4k

### OS version

16.0

### Jellyfin server version

10.8.5

**Comment by Bronson-Brown-deVost** [comment]
I also have this problem. I can find my movies individually if I search for them. Also my movie "collections" work fine. 

The problem started after I moved my server and possibly switched from one version of Jellyfin server to another. My current version of Jellyfin server is 10.8.5, I don't know what my previous version was, sorry.

**Comment by ttonych** [comment]
The same problem began after upgrading Swiftfin to 1.0.0(83). The previous version worked fine. 
Jellyfin 10.8.5 and 10.8.7

**Comment by MichaelAllenHardeman** [comment]
I am experiencing this problem as well. Fresh install of 1.0.0(83). I don't see my movie library 

[Here is the log](https://pastebin.com/9kQsmeM7) from the server side of the tvOS login and playing a video from my TV Show libary.

The only thing that looks suspicious is the Warning I see in the logs about a Slow Response form includeItemTypes=movie

`Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from "http://192.168.2.226:8096/Users/2345e169c34c4f5a927b20c095a53ec6/Items?sortBy=SortName&sortBy=IsFolder&includeItemTypes=movie&fields=airTime&fields=canDelete&fields=canDownload&fields=channelInfo&fields=chapters&fields=childCount&fields=cumulativeRunTimeTicks&fields=customRating&fields=dateCreated&fields=dateLastMediaAdded&fields=displayPreferencesId&fields=etag&fields=externalUrls&fields=genres&fields=homePageUrl&fields=itemCounts&fields=mediaSourceCount&fields=mediaSources&fields=originalTitle&fields=overview&fields=parentId&fields=path&fields=people&fields=playAccess&fields=productionLocations&fields=providerIds&fields=primaryImageAspectRatio&fields=recursiveItemCount&fields=settings&fields=screenshotImageTags&fields=seriesPrimaryImage&fields=seriesStudio&fields=sortName&fields=specialEpisodeNumbers&fields=studios&fields=basicSyncInfo&fields=syncInfo&fields=taglines&fields=tags&fields=remoteTrailers&fields=mediaStreams&fields=seasonUserData&fields=serviceName&fields=themeSongIds&fields=themeVideoIds&fields=externalEtag&fields=presentationUniqueKey&fields=inheritedParentalRatingValue&fields=externalSeriesId&fields=seriesPresentationUniqueKey&fields=dateLastRefreshed&fields=dateLastSaved&fields=refreshState&fields=channelImage&fields=enableMediaSourceDisplay&fields=width&fields=height&fields=extraIds&fields=localTrailerCount&fields=isHD&fields=specialFeatureCount&enableUserData=true&sortOrder=ascending&recursive=true&startIndex=0&limit=34" to "192.168.2.253" in 0:00:00.5133504 with Status Code 200`

**Comment by Mat-Longinow** [comment]
I am also experiencing this issue, would love a fix!

**Comment by kcramer** [comment]
I experienced this issue with Swiftfin 1.0.0(83) from Oct 25 and Jellyfin server 10.8.7.

I debugged the issue in Xcode and, at least for me, it is an API issue.  The JSON decoding of the response from the server was failing.  MediaStreamType was "Data" but the API version with the Swiftfin client did not include that type so it failed.  I updated the API code and it did work as expected with movies being displayed again.

The Swiftfin tvOS app will need the API updated and a new build pushed.

**Comment by Mat-Longinow** [comment]
As a note, this is happening on my iPhone as well.
iPhone 12 Pro Max. Version 15.1.1.

**Comment by kuflierl** [comment]
I would like to note that I also have this issue on 1.0.0 (79). My movies and books libraries (20 or so entries) appear empty but my small collections and shows libraries (5 or so entries) seem to show up. Could this be a timeout issue? All libraries work on the main app and web.

**Comment by Mat-Longinow** [comment]
Yea unfortunately this issue has forced me to switch over to Infuse instead of Jellyfin as this is a pretty debilitating bug. I would personally mark this high priority if this was my project.

**Comment by Bronson-Brown-deVost** [comment]
Apparently @kcramer has the fix already. What do we need to push this thing through? I'm happy to help with any coding needed, but I assume someone with the right Apple developer credentials needs to build the app. 

By the way, big shout out to all the devs who have put so many hours into this fantastic project.

**Comment by kuflierl** [comment]
> Yea unfortunately this issue has forced me to switch over to Infuse instead of Jellyfin as this is a pretty debilitating bug. I would personally mark this high priority if this was my project.

The app is still in Early Development. I wouldn't expect it to work very well. That said it is a pretty bad bug that probably should get a lot of attention.

**Comment by Mat-Longinow** [comment]
> 

Totally fair. I didn't mean to come across as overly critical. I just mean that it is a little disappointing that the main feature of loading in the video library in order to watch movies/shows isn't working and it has seemed to get little attention.

Might be my expectations, but I would have anticipated this to be a critical failure thing that gets hotfixed right away.

**Comment by Bronson-Brown-deVost** [comment]
Probably folks don't upgrade their Jellyfin too aggressively, so it hits the new installs a lot harder and faster than most other users, so it goes... 
Very happy to hear you are working on it @LePips. Thank you very much for your time and effort.

**Comment by Rookwork** [comment]
This issue is coming up for me on the just released public version (1.0.0). Both iPadOS and tvOS versions don't see any movies in the Media tab, but Collections and manually searching work fine. I don't see anything interesting in Jellyfin logs aside from the some slow response times. Movies do show up in the Jellyfin webUI, though.

**Comment by psyciknz** [comment]
Me too.  Switched to the released version.   Same issue

**Comment by easton36** [comment]
This issue also occurs for me on the iOS and Apple TV clients (latest released version)

**Comment by matthewpritchett** [comment]
Same here.

**Comment by dahrknet** [comment]
I have the same problem. Initially, this was just with movies but now shows are not loading either, both libraries are empty.

**Comment by catalystech** [comment]
As @kcramer  mentioned updating the "MediaStreamType.swift" file to include "Data" as a case will fix the issue.

```swift
/** Enum MediaStreamType. */
public enum MediaStreamType: String, Codable, CaseIterable {
    case audio = "Audio"
    case data = "Data"  // ADDED THIS LINE
    case video = "Video"
    case subtitle = "Subtitle"
    case embeddedImage = "EmbeddedImage"
}
```

**Comment by LePips** [comment]
Don't worry, there's a reason this issue is tagged to my PR.

**Comment by Mat-Longinow** [comment]
Despite my griping, you guys are champions, and I appreciate you. Thanks for taking care of this 💪🏻

**Comment by fisherd80** [comment]
Evening,  I just downloaded the app on iOS and only the TV Shows were shown.  No Movies were displayed, or appear when search (funny the search sees the movies to pre-select).  I attempt to play a TV show but the app would refuse to play the video file.

Any suggestions to fix these.

**Comment by marvagabi** [comment]
> ```swift
> case data = "Data"  // ADDED THIS LINE
> ```

Can confirm this fixes the issue for me as well, here's what I was seeing in the logs prior to applying the fix:
` [🔴 ERROR] ViewModel#60:handleAPIRequestError(displayMessage:completion:) Request failed: JSON Decoding failed: Underlying Error: Cannot initialize MediaStreamType from invalid String value Data - Coding Path: [Items,Index 7,MediaSources,Index 0,MediaStreams,Index 2,Type]`

**Comment by avrgkarl** [comment]
Movie library is showing "No Results".

Downloaded the app a few days ago. First time using Jellyfin native app on my Apple TV's. Both have the same issue. Hope this can get fixed easily. I really enjoy the desktop app and iOS app. They both seem to work very well so far. 

Just wanted to let you know. I'm very new to all this, like only began building my media server a couple weeks ago. Cheers.

**Comment by rottedmood** [comment]
Same issue. Movies and Music Videos do not show up on either the iOS or tvOS apps. Shows  come up fine but nothing else seems too.

**Comment by davetunnicliff** [comment]
+1 for me too. Been through some manual troubleshooting steps to see if I can find a workaround.... nothing seems to be working for me. TV shows are working absolutely fine, but I'm finding that the Movies and Kids Movies libraries are causing the problems:

1. Removed the collections + movies + kids movies libraries I'd previously created. Tried re-adding and hit the same issue. 
2. Removed again. Added one movie. That worked. 
3. Added four more - that did not work and I was returned to the "No Results" message. 
4. Went back to the one move - and it reappeared again. 

I also found this thread on reddit which is quite useful to allow you to get to the swiftfin logs easily if you have an iphone: 
https://www.reddit.com/r/jellyfin/comments/106jzhe/swiftfin_apple_tvos_app_doesnt_work/

@marvagabi already posted this above... but just to confirm, this is the same error I'm seeing: 
 [🔴 ERROR] ViewModel#60:handleAPIRequestError(displayMessage:completion:) Request failed: JSON Decoding failed: Underlying Error: Cannot initialize MediaStreamType from invalid String value Data - Coding Path: [Items,Index 4,MediaSources,Index 0,MediaStreams,Index 1,Type]

**Comment by ThomasBeckham** [comment]
I'm having this issue too with a fresh install of both jellyfin and swiftfin on my apple tv 4k

**Comment by misaim** [comment]
I read this thread and couldn't see anything like this so:
I tried pulling up a movie on my android phone and watched for a few minutes. 
Afterwards, the movie showed up on my apple tv swiftfin (version 1.0.0) in the recent section in home tab.
I could play it just fine.
Movies tab is empty.

**Comment by dathbe** [comment]
For me, the problem is intermittent.  Sometimes I am able to see moves in the movies section, sometimes not.  Sometimes I am able to search for movies, sometimes not.  I can't find any pattern to it.

**Comment by timhansinger** [comment]
> > Version 1.0.1 seems to have fixed it for me... i can now see all my libraries.
> 
> I can now also see all libraries (tested the iPhone app v1.0.1). However I have one issue: It will not show multiple versions of one movie.

Now also multiple versions show up. Just had to wait a little while. Great update.

**Comment by davetunnicliff** [comment]
> Version 1.0.1 seems to have fixed it for me... i can now see all my libraries.

Me too - thanks very much team. Great update!
