### ISSUE TITLE
tvos - Start playback on item doesn't respond

### ISSUE THREAD

**Issue by psyciknz** [jellyfin/Swiftfin#622]
### Describe the bug

1. A media item, open it overview
2. Click on the play - unsure if it's always some content partially watched. - no response.  Verify the jellyfin server logs and no attempt or mention of attempted playback,

Seems to happen sometimes, and then it's essentially unusable.  Unsure if there sort of caching occuring, and because of #621 its showing things that aren't there?

### Application version

1.0.0(74) I think

### Where did you install the app from?

TestFlight

### Device information

Apple tv and apple tv 4k

### OS version

16.0

### Jellyfin server version

10.8.5

**Comment by tantalic** [comment]
Same here with an iPad, Apple TV and iPhone

**Comment by skellycode** [comment]
> I have something similar on iOS16.1, whereby playback of the same file works on other clients. Clicking play results in nothing happening on the device, though I do see a log on the Jellyfin server indicating it attempted to serve up the media for the Swiftfin client


Same issue, Swiftfin 1.0.0 on iPhone running iOS16.1

**Comment by dathbe** [comment]
I've found that it is an intermittent problem.  Some files will not play at some times.  At other times those files will play.  Sometimes restarting the app fixes it.
