### ISSUE TITLE
Can't remove server or change URL

### ISSUE THREAD

**Issue by michaelkrieger** [jellyfin/Swiftfin#629]
### Describe the bug

I had a server with one user on an Apple TV.
I have recently changed the IP address of the server.

* Despite all the holding, swiping, etc. there appears to be no way for me to remove the existing server.  I was able to remove the user, however.
* If I click to add a URL and enter the new URL, it tells me that [servername] is already present and asks if I want to add a URL to it, but the only option is to cancel (so it doesn't add the URL).

I had to delete the app and reinstall it 

### Application version

1.0.0(83)

### Where did you install the app from?

TestFlight

### Device information

Apple TV 4K

### OS version

16.1

### Jellyfin server version

10.8.7

**Comment by SlothCroissant** [comment]
Can confirm this is an issue. I'm on 10.8.8 and the only solution is to delete and reinstall the app.

**Comment by eliotalanfoss** [comment]
I also had this issue the first time I used the app.  I accidentally used an incorrect URL and I couldn't fix the issue without reinstalling the app.

**Comment by Pollyanna584** [comment]
Same issue.  The URL defaults to http:// in the setup menu so if you have an https:// server and if you enter the URL wrong the first time it can't be changed or removed and you can't add another server.  I tried to delete it but the Apple TV will either make me delete the app from all devices or just remove it from the home screen.

**Comment by campfred** [comment]
I found a workaround.
Basically, I open the settings (cogwheel icon at the top right) and tap « Switch user » (hopefully I translated this right, mine is in French).
That allows me to get to a server selection screen where I can add and remove servers.
That's also how I added other URLs for a given server.

**Comment by James3UK** [comment]
This is easy to reproduce by changing the server ip and then trying to add or update it.
The server is deemed to be the same even if the IP has changed, some additional checks are needed and the ability to remove servers needs to be added as well as cancel being the only button.

https://github.com/jellyfin/Swiftfin/blob/638ccab69208ebbd3185ea70072017b3fc55f983/Shared/Services/SwiftfinStore.swift#L224

[    return L10n.tr("Localizable", "serverAlreadyConnected", p1, fallback: "Server %s is already connected")](https://github.com/jellyfin/Swiftfin/blob/638ccab69208ebbd3185ea70072017b3fc55f983/Shared/Strings/Strings.swift#L479)

**Comment by DareDareHub** [comment]
Same issue, 
I unloaded the app (instead of deleting it) and it refreshed the settings…

**Comment by RexYuan** [comment]
Issue still persists. There's no way to remove a server
