### ISSUE TITLE
`(null)` as episode number

### ISSUE THREAD

**Issue by MelanX** [jellyfin/Swiftfin#631]
### Describe the bug

1. Open a TV series
2. Navigate to an episode
3. Look at the episode number -> `(null)`

Maybe it's just a translation problem, I'm using Swiftfin on German and it said `Folge (null)`.

### Application version

1.0.0 (83)

### Where did you install the app from?

TestFlight

### Device information

Apple TV 4K (2022)

### OS version

tvOS 16.1.1 (20K80)

### Jellyfin server version

10.8.7

**Comment by bzz445** [comment]
already fixed #613
