### ISSUE TITLE
Crash on tvos when accessing a show

### ISSUE THREAD

**Issue by Ulyssedev** [jellyfin/Swiftfin#636]
### Describe the bug

1. Go to Swiftfin tvos 1.0.0(83)
2. Attempt to view the page of any TV show or anime.
3. The app crashes.

Note: (The language is set to French; this might be an issue, although this is strange since movies are working fine.)

I can provide any supplementary information if needed.

### Application version

1.0.0(83)

### Where did you install the app from?

TestFlight

### Device information

Apple tv 4k 2021

### OS version

tvOS 16.1 (latest)

### Jellyfin server version

10.8.8

**Comment by SlothCroissant** [comment]
FYI (not discounting your report), I can't reproduce this on the same Jellyfin/tvOS/App version, and same Apple TV (2021 4k 32GB)

Only difference is language set to English. Does your issue repro when using English?

**Comment by Ulyssedev** [comment]
After changing my Apple TV's language to English, I no longer had the issue, and I believe this bug is only affecting non-English devices.

**Comment by dns2utf8** [comment]
Fun fact, choosing a movie and watching it in one go works :shrug: 
Switching the device to en_US is not an option for my setup because it is a family device.
