### ISSUE TITLE
Too many drop downs

### ISSUE THREAD

**Issue by LePips** [jellyfin/Swiftfin#641]
### Discussed in https://github.com/jellyfin/Swiftfin/discussions/634

<div type='discussions-op-text'>

<sup>Originally posted by **tknx** November 26, 2022</sup>
I'd like to suggest moving a bit away from the number of hidden controls and interface element. I like the ability to skip forward and back in the normal app with arrows over having to do a drop down menu. 

Similarly, there are lots of submenus for language and subtitles that all feel like trying to avoid icons to keep it "minimal" instead of just easier to get to what you need. 

I do like how the bar is broken up by chapter though...</div>

**Comment by tknx** [comment]
I'll second this!
