### ISSUE TITLE
Add Basque locale

### ISSUE THREAD

**Issue by xabirequejo** [jellyfin/Swiftfin#642]
Hi,

Swiftfin has been translated to Basque for a few weeks or months now, it would be great to see the new locale live so that changes and adjustments can be made before the app is released on the App Store.

I believe there are also some other languages ready to be used —at least if I'm on the right [Weblate](https://translate.jellyfin.org/projects/swiftfin/swiftfin/)— that haven't been added to the app yet.

Thanks

**Comment by LePips** [comment]
They will be pushed eventually.
