### ISSUE TITLE
No sound for TrueHD Atmos 7.1 content

### ISSUE THREAD

**Issue by JackJ74** [jellyfin/Swiftfin#643]
### Describe the bug

1. Play a video with TrueHD Atmos 7.1 audio format.
2. No sound playing even comfirming TureHD Atmos 7.1 audio tack is selected

Expect:
Sound playing 

### Application version

1.0.0(79)

### Where did you install the app from?

TestFlight

### Device information

iPhone 11

### OS version

iOS 16.2

### Jellyfin server version

10.8.6

**Comment by lavavex** [comment]
I noticed this as well on my new AppleTV 4k, but it seems like Apple doesn't support TrueHD audio. Hopefully they can make it so it auto selects Dolby Digital instead of TrueHD

**Comment by LePips** [comment]
If the system or VLCKit don't support it, there's nothing we can do. I'm also not inclined for an automatic selection until we figure out the device builder for supported formats.
