### ISSUE TITLE
Weird season index

### ISSUE THREAD

**Issue by fredmorais** [jellyfin/Swiftfin#653]
### Describe the bug

I just installed Swiftfin on my iPhone today and I noticed 2 bugs related to seasons in TV shows. I posted these 2 bugs together as I believe they might be related. Both these bugs also happen on my iPad.

First, when I open a TV show it selects the first season, but it says no content available. I would expect it to show either the season I'm currently watching or the first one.

![IMG_4480](https://user-images.githubusercontent.com/40044095/210024345-d58d73fc-3c9f-4f2b-9773-8ea6f169da5c.PNG)

When I go to change season, it is not in an ordered list, but rather in a random order.

![IMG_4481](https://user-images.githubusercontent.com/40044095/210024349-77edf25e-a2bd-475f-8df9-73e1e936d791.PNG)

### Application version

1.0.0(79)

### Where did you install the app from?

App Store

### Device information

iPhone XR

### OS version

16.1.2

### Jellyfin server version

10.8.7

**Comment by Vortikai** [comment]
Same problem. Clicking on season one no results will crash the program.

**Comment by sidney-eliot** [comment]
The bug still isn't fixed, even after "fix nil episodes"

**Comment by Lucchese-Anthony** [comment]
Ditto, this is still a bug needing to be fixed. There is a workaround but not desireable
