### ISSUE TITLE
I cannot see groups that aren't shows

### ISSUE THREAD

**Issue by CoconutMacaroon** [jellyfin/Swiftfin#654]
Under Home, I can see Next Up, Recently Added, and Latest shows

Is there some way to view media that isn't categorized as a show? I.e., I have some audio files in a separate category, but I don't see an obvious way to play them. Am I missing something obvious? They show up in the Jellyfin app, but not in Swiftfin. I'm having this issue on iOS 15. I also can't see those files under "All Media" either

**Comment by LePips** [comment]
Swiftfin only shows movies and shows.
