### ISSUE TITLE
401 Unauthorized user

### ISSUE THREAD

**Issue by sam-harry** [jellyfin/Swiftfin#660]
I've been testing the recently released Swiftfin app (thank you!) but I am unable to login to my server. My steps to reproduce are:

1. Add my jellyfin server. My server is located by the app and recognizes the server name as well as login options.
2. Enter the credentials of any login user.

The login is rejected with the error "401 unauthorized user" as in the screenshot below. I have triple checked my passwords (and even created a test user with empty password) however I am unable to login.

![swiftfin_login_failure](https://user-images.githubusercontent.com/43934818/210154859-b9a7d184-8973-4ee0-875f-b796b67e8ae6.png)

This behavior on occurs only on the swiftfin app: I can login and play media with the web app, jellyfin app, and finamp app. This behavior was mostly tested on my iPhone SE (2nd Gen, iOS 16.2) but also occurred on my Apple TV HD (4th Gen, tvOS 16.1).

On my Jellyfin 10.8.8 server (Debian 11 on x86, [apt packages,](https://jellyfin.org/docs/general/installation/linux#repository) [nginx from a subdomain](https://jellyfin.org/docs/general/networking/nginx/#nginx-from-a-subdomain-jellyfinexampleorg)) the logs show the message:

`[INF] AuthenticationScheme: "CustomAuthentication" was challenged.`

for each failed login attempt.

Any advice to resolve this would be much appreciated.

### Application version

1.0.0 (79)

### Where did you install the app from?

App Store

### Device information

iPhone SE (2nd Generation)

### OS version

16.2

### Jellyfin server version

10.8.8

**Comment by LePips** [comment]
Make sure that you put the correct http/https scheme when adding your server.

**Comment by sam-harry** [comment]
Solved my issues, thank you for the fast response.

**Comment by JoeMansour2003** [comment]
I have this exact problem but only for my admin account. All my other accounts work fine I've also verified that it's using HTTP and not https.

**Comment by perkyquirky** [comment]
I too am getting this issue.
[2025-02-21 16:06:50.940 +11:00] [INF] AuthenticationScheme: "CustomAuthentication" was challenged.
Swiftfin keeps trying to revert from https:// to http://
I have two separate AppleTV's which connect. One works the other has the issue.
No differences between them as far as I can tell.
The one that does not work does works from that IP address on iPhones, so it's not a networking issue.

**Comment by ItalianJack** [comment]
Can't speak as to @perkyquirky's issue with it reverting back to http://, but I can confirm that switching from http:// to https:// allowed me to connect without problems. With http:// it showed all of my users, but I got the same 401 unauthorized and `[INF] AuthenticationScheme: "CustomAuthentication" was challenged.` log.

**Comment by hardingt** [comment]
Same issue, I had to uninstall swiftin from my apple tv and re-add the server with an "s" it was defaulting to http for some unknown reason. It was very frustrating to try and use the app today and suddenly my users were gone and I was getting 401s unless I uninstalled and reinstalled. There wasn't even a button to "remove" a server.
