### ISSUE TITLE
1.001 and 1.005 errors, network timeout and unknown

### ISSUE THREAD

**Issue by cblinq** [jellyfin/Swiftfin#662]
### Describe the bug

I’m logging in the server, logged successfully, I can see folders in the media tab so I know I’m logged in and after a few seconds I receive the errors. This happens in both iPhone and Apple TV apps.

Logs:
 [🔵 DEBUG] HomeViewModel#62:refresh() Refresh called.
 [🔵 DEBUG] HomeViewModel#62:refresh() Refresh called.
 [🔵 DEBUG] HomeViewModel#89:refreshLibrariesLatest() Retrieved user view: 9d7ad6afe9afa2dab1a2f6e00ad28fa6 (Collections) with type boxsets
 [🔵 DEBUG] HomeViewModel#89:refreshLibrariesLatest() Retrieved user view: 9f2f3bc30fa09e72d898f15d41242e73 (Folders) with type folders
 [🔵 DEBUG] HomeViewModel#89:refreshLibrariesLatest() Retrieved user view: f137a2dd21bbc1b99aa5c0f6bf02a805 (Movies) with type movies
 [🔵 DEBUG] HomeViewModel#89:refreshLibrariesLatest() Retrieved user view: 1666137e53e9c422b5001e4549352763 (Movies-4K) with type movies
 [🔵 DEBUG] HomeViewModel#89:refreshLibrariesLatest() Retrieved user view: f87e8b7659225c01569e3bc2db960003 (Movies-4KDV) with type movies
 [🔵 DEBUG] HomeViewModel#89:refreshLibrariesLatest() Retrieved user view: 767bffe4f11c93ef34b805451a696a4e (TV Shows) with type tvshows
 [🔵 DEBUG] HomeViewModel#89:refreshLibrariesLatest() Retrieved user view: d2938297bb39f6ca4039f0ed96f6ccaf (TV-4k) with type tvshows
 [🔵 DEBUG] HomeViewModel#89:refreshLibrariesLatest() Retrieved user view: e64a0833bef81cbc17882727d30e8b01 (TV-Anime) with type tvshows
 [🔴 ERROR] ViewModel#46:handleAPIRequestError(displayMessage:completion:) Request failed: URL request failed with error -1001: The operation couldn’t be completed. (JellyfinAPI.ErrorResponse error 0.)
 [🔴 ERROR] ViewModel#46:handleAPIRequestError(displayMessage:completion:) Request failed: URL request failed with error -1001: The operation couldn’t be completed. (JellyfinAPI.ErrorResponse error 0.)
 [🔴 ERROR] ViewModel#46:handleAPIRequestError(displayMessage:completion:) Request failed: URL request failed with error -1001: The operation couldn’t be completed. (JellyfinAPI.ErrorResponse error 0.)
 [🔴 ERROR] ViewModel#46:handleAPIRequestError(displayMessage:completion:) Request failed: URL request failed with error -1001: The operation couldn’t be completed. (JellyfinAPI.ErrorResponse error 0.)
 [🔴 ERROR] ViewModel#46:handleAPIRequestError(displayMessage:completion:) Request failed: URL request failed with error -1001: The operation couldn’t be completed. (JellyfinAPI.ErrorResponse error 0.)
 [🔴 ERROR] ViewModel#46:handleAPIRequestError(displayMessage:completion:) Request failed: URL request failed with error -1001: The operation couldn’t be completed. (JellyfinAPI.ErrorResponse error 0.)
 [🔴 ERROR] ViewModel#46:handleAPIRequestError(displayMessage:completion:) Request failed: URL request failed with error -1001: The operation couldn’t be completed. (JellyfinAPI.ErrorResponse error 0.)
 [🔴 ERROR] ViewModel#46:handleAPIRequestError(displayMessage:completion:) Request failed: URL request failed with error -1001: The operation couldn’t be completed. (JellyfinAPI.ErrorResponse error 0.)
 [🔴 ERROR] ViewModel#46:handleAPIRequestError(displayMessage:completion:) Request failed: URL request failed with error -1001: The operation couldn’t be completed. (JellyfinAPI.ErrorResponse error 0.)
 [🔴 ERROR] ViewModel#46:handleAPIRequestError(displayMessage:completion:) Request failed: URL request failed with error -1001: The operation couldn’t be completed. (JellyfinAPI.ErrorResponse error 0.)
 [🔴 ERROR] ViewModel#46:handleAPIRequestError(displayMessage:completion:) Request failed: URL request failed with error -1001: The operation couldn’t be completed. (JellyfinAPI.ErrorResponse error 0.)
 [🔴 ERROR] ViewModel#46:handleAPIRequestError(displayMessage:completion:) Request failed: URL request failed with error -1001: The operation couldn’t be completed. (JellyfinAPI.ErrorResponse error 0.)
 [🔴 ERROR] ViewModel#46:handleAPIRequestError(displayMessage:completion:) Request failed: URL request failed with error -1001: The operation couldn’t be completed. (JellyfinAPI.ErrorResponse error 0.)
 [🔴 ERROR] ViewModel#46:handleAPIRequestError(displayMessage:completion:) Request failed: URL request failed with error -1001: The operation couldn’t be completed. (JellyfinAPI.ErrorResponse error 0.)
 [🔴 ERROR] ViewModel#46:handleAPIRequestError(displayMessage:completion:) Request failed: URL request failed with error -1001: The operation couldn’t be completed. (JellyfinAPI.ErrorResponse error 0.)
 [🔴 ERROR] ViewModel#46:handleAPIRequestError(displayMessage:completion:) Request failed: URL request failed with error -1005: The operation couldn’t be completed. (JellyfinAPI.ErrorResponse error 0.)
 [🔴 ERROR] ViewModel#46:handleAPIRequestError(displayMessage:completion:) Request failed: URL request failed with error -1001: The operation couldn’t be completed. (JellyfinAPI.ErrorResponse error 0.)

### Application version

1.0.0 (79)

### Where did you install the app from?

App Store

### Device information

iPhone 12 Pro Max / Apple TV 4K 3rd generation 64GB

### OS version

iOS 16.2 / tvOS 16.2

### Jellyfin server version

10.8.5

**Comment by Metuant** [comment]
Seeing the same error and debug log.

Adding a datapoint - sometimes (maybe 50% success) if I select the "media" button and let that page load (usually takes awhile, 30-40 seconds) upon first opening the app then the homepage populates without this error. 

Application version

1.0.0 (79)

Where did you install the app from?

App Store

Device information

iPhone 12 Pro

OS version

iOS 16.2 / tvOS 16.2

Jellyfin server version
10.8.8

**Comment by cblinq** [comment]
I’ve tested with another server, version 10.8.7 using the same devices and versions and getting no error.

**Comment by LePips** [comment]
There has been considerable refactoring done since this issue was created with better error handling and logging.
