### ISSUE TITLE
Quick Connect login not working

### ISSUE THREAD

**Issue by davemsh** [jellyfin/Swiftfin#667]
### Describe the bug

When I try to use the Quick Connect feature to log in using Swiftfin, it doesn't work.

Once I type the six-digit code into another authorized device, I get a 401 "Unauthorized User" error in Swiftfin.

I've verified I can still log in using Quick Connect in the Jellyfin iOS web client app.

### Application version

1.0.0(79)

### Where did you install the app from?

App Store

### Device information

iPad (6th generation)

### OS version

iPad OS 15.5

### Jellyfin server version

10.8.8

**Comment by LePips** [comment]
Make sure that you put the correct http/https scheme when adding your server.

**Comment by davemsh** [comment]
I used the autodiscovery functionality to connect to my Jellyfin server. However, it appears you are correct, judging by the server listing in Swiftfin, it says HTTP and not HTTPS like it needs to be using.

The web client app also discovers it as HTTP in the same manner, but it successfully logs in anyway. If I had to guess, if HTTP fails due to an unauthorized error, it re-attempts with HTTPS.

I just tried editing my server's published server path to include the protocol ("https://jellyfin.mydomain.com"), rather than just the domain ("jellyfin.mydomain.com"), but this doesn't seem to have changed the autodiscovery broadcast response. Both Swiftfin and the web client continue to show the server was discovered at HTTP.

**Comment by davemsh** [comment]
I also noticed that on the Servers screen, where it shows my autodiscovered server, it's showing "http:jellyfin.mydomain.com", missing the // in the protocol. Could this be the reason it's failing to connect?

**Comment by grahamgraham** [comment]
Anecdotal, but I fixed this by uninstalling the app and reinstalling it.

**Comment by adavidzh** [comment]
Just had same problem. Same anecdotal solution worked.
