### ISSUE TITLE
iPhone SE can only play back with Native Player

### ISSUE THREAD

**Issue by homeisfar** [jellyfin/Swiftfin#670]
### Describe the bug

I have an original iPhone SE (2016). Swiftfin will only playback content with the Native Player. There aren't really any logs that indicate an error that I can see on the server. This problem doesn't occur on my iPhone 11.

If the source content is h.264 it will play with Native Player via direct play. If the source content is hevc the additional option "Use fmp4 with HLS" must also be selected or else it will only play back audio.

### Application version

1.0.0(79)

### Where did you install the app from?

App Store

### Device information

iPhone SE (1st gen)

### OS version

15.7.2

### Jellyfin server version

10.8.8

**Comment by LePips** [comment]
Yes, because hevc can only be played in an mp4 container, it's a `.ts` stream by default.

**Comment by homeisfar** [comment]
OK, that addresses the HEVC part (and I assume other codecs), but it doesn't address why h.264 content can only be played back with with the "Native Player" option enabled, considering that this is not a requirement on the iPhone 11.

Honestly, it isn't important to me - I just thought I'd report the feature disparity.

**Comment by LePips** [comment]
That's great and thank you for reporting. Don't worry, that won't go unnoticed as I will have a decision on all of the current playback issues soon.
