### ISSUE TITLE
iOS New Content Push Notification

### ISSUE THREAD

**Issue by samuraimarv** [jellyfin/Swiftfin#672]
**Describe the feature you'd like**

iOS push notification support.

**Additional context**

Would like to receive a push notification for a new episode of a series the user is watching. 

If a user is not watching the series or when a new movie is added user should get a push notification from the app that a new series or movie was added. This should only happen the first time the movie or series is added to the library. 

Would ideally include an option to determine if the user wants these kinds of notifications or not. 

In the future could be expanded to enable admins to get all server notification types via Push Notification from the iOS app.

**Comment by LePips** [comment]
This is not remotely possible at all. This would require individuals to have an Apple Developer Account to get the right entitlements, build their own version of the app, have the implementation also on the server-side, and that would only work for content from that single server.

That was just the bare minimum of what would be required, but ultimately this is not possible in the realm of self-hosted open source applications unless you do it yourself.

**Comment by samuraimarv** [comment]
I'm a bit confused, the end user would need an apple developer account? If thats not what you meant, I thought the Swiftfin team already had a developer account. 

I apologize if I come off as ignorant, I am not a developer but I do have coding and dev ops experience but no real experience with Swift or iOS development.

**Comment by LePips** [comment]
Frankly, the only thing I'm open to say is to learn how APNs works. This is not possible.

https://developer.apple.com/documentation/usernotifications/registering_your_app_with_apns

**Comment by samuraimarv** [comment]
Thank you for your patience and for providing that link. From what I understand from that and watching this video: https://www.youtube.com/watch?v=UJree24HWx0&t=55s each users own instance of Jellyin Server would be what sends the notification to the APNs and that would then forward the push notification to the device. 

I see now why you said it wasn't possible. Again thank you for your patience and for providing me that link.

**Comment by LePips** [comment]
You're right, each JF server would send notification requests. Each JF server would need their own Certificate/key as generated from having an Apple Developer Account and this has to be the same account used to compile the application on your device.

**Comment by samuraimarv** [comment]
Yeah what you in your original justification for closing the issue out makes perfect sense. I apologize for my ignorance and do appreciate you answering my questions and breaking it down for me. 

I'm looking at getting into iOS development, maybe by the time I have that all figured out I'll be able to help find a solution to getting it working.
