### ISSUE TITLE
Audio track is delayed

### ISSUE THREAD

**Issue by jenkshields** [jellyfin/Swiftfin#677]
### Describe the bug

When starting any media, the audio track is delayed by 0.5-1s. On pausing or closing media, audio continues for that second even while the video stops.

this issue does not appear with the native player. It appears both with the TestFlight build and the App Store build.

I’m running the latest version on an Apple TV 4K 3rd gen wifi running 16.2

### Application version

1.0.0

### Where did you install the app from?

App Store

### Device information

Apple TV 4k

### OS version

16.2

### Jellyfin server version

10.7.7

**Comment by LePips** [comment]
Sadly this is in VLCKit and there is nothing we can do about it. As noted in the current Contributing Guidelines:

> Intended Behaviors Due to Technical Limitations ... Audio delay when starting playback and un-pausing, may be fixed in VLCKit v4

**Comment by jenkshields** [comment]
Oh, that’s interesting, thank you for clarifying! This wasn’t behaviour I saw a few days ago so I wondered if something had changed.

**Comment by tysonstewart** [comment]
For clarity, does this mean that an audio delay _during playback_ is expected behavior?

The only way I can find to not have this delay is to enable the native player, but that causes the video quality to become very poor unfortunately.

**Comment by juliangaal** [comment]
Are there any updates on this?

**Comment by patrickomeara** [comment]
Strangely enough if you're watching tv shows you can go forward an episode and then back and the delay is gone.

**Comment by Tiebe-Vercoutter** [comment]
> Strangely enough if you're watching tv shows you can go forward an episode and then back and the delay is gone. 

This works haha but unfortunately still not fixed

**Comment by ptfuzi** [comment]
I guess this issue still persists.
