### ISSUE TITLE
Video transcoding

### ISSUE THREAD

**Issue by GavinIves** [jellyfin/Swiftfin#681]
### Describe the bug

There is no transcoding through Internet connection, and there is no transcoding option, which is a problem for people with insufficient bandwidth. Is there a plan to fix this problem

### Application version

1.0.0(79)

### Where did you install the app from?

App Store

### Device information

iphone12

### OS version

ios16

### Jellyfin server version

10.8.6

**Comment by LePips** [comment]
Duplicate of #184
