### ISSUE TITLE
Subtitles don't work on Apple TV's experimental player

### ISSUE THREAD

**Issue by lourenci** [jellyfin/Swiftfin#684]
### Describe the bug

1. Active both experimental features:
  - Use native player
  - Use fmp4 with HLS
2. Try to run any video with subtitles, it could be either embedded or external (SRT). 

### Application version

1.0.0 (84)

### Where did you install the app from?

App Store

### Device information

Apple TV 4K (3rd generation)

### OS version

tvOS 16.2

### Jellyfin server version

10.8.8

**Comment by LePips** [comment]
Please see https://github.com/jellyfin/Swiftfin/discussions/324, the native player is very much just in development. At the same time, the server doesn't have the best HLS support that Apple expects so it will never really be as expected compared to watching other media on an iOS/tvOS device.
