### ISSUE TITLE
Series art not loading

### ISSUE THREAD

**Issue by marvagabi** [jellyfin/Swiftfin#686]
### Describe the bug

On the Home Screen or in the Shows/ Movies library view certain series are not loading their artwork. Instead you just see a grey background with the initials of the series. 

On the web and iOS non-Swift app the series art loads up normally. I don't see anything in the logs that seem related to this.

![Simulator Screen Shot - iPhone 14 Pro - 2023-01-23 at 17 04 50](https://user-images.githubusercontent.com/94997977/214160319-0cf6d67d-c314-42de-afcb-0d587fe91cde.png)
![Simulator Screen Shot - iPhone 14 Pro - 2023-01-23 at 17 04 57](https://user-images.githubusercontent.com/94997977/214160336-c7e6e87a-1e56-48f9-8db8-663174f5da7a.png)

### Application version

1.0.0 (79)

### Where did you install the app from?

None

### Device information

iPhone 14 Pro

### OS version

16.2

### Jellyfin server version

10.8.9

**Comment by marvagabi** [comment]
Forcing a replacement of all metadata on the server for the affected series/movies seems to fix the issue. This is a workaround but still doesn't address why they don't show up in the first place. So for now I'l leave this report open, unless the Swiftfin devs want to close it.

**Comment by LePips** [comment]
JF has a straightforward URL structure, so requiring a metadata refresh doesn't surprise me. There will be a more informative logging system after #593 so if this issue occurs again we can have more info.

**Comment by LePips** [comment]
I have no longer seen issues of expected art not loading on the latest main.
