### ISSUE TITLE
tvOS - Library List View

### ISSUE THREAD

**Issue by Smiggel** [jellyfin/Swiftfin#687]
**Describe the feature you'd like**
The layout of all movies and tv-series is a poster view layout, where all items are displayed as a poster next to each other. I prefer to look at my content as a list. Therefor I would like to feature request to switch between a list view and poster view.

**Comment by LePips** [comment]
Is this for tvOS? This is possible on iOS.

**Comment by Smiggel** [comment]
Oops, forgot to mention that. Yes, for TVOS i mean.

**Comment by JPKribs** [comment]
I've had some free time as of late and I thought I would take a look at this. Does this look what you were expecting @Smiggel? To mirror iPad, I allowed for up to 3 columns. iPad it's 4 but for tvOS, 4 was falling off the page. IMO, it looks like maybe 3 is a bit too much (see below) but if people like 3+ I'm fine to include it.

![Library List Layout](https://github.com/user-attachments/assets/8004e88b-76f6-49bf-84e7-af43b68d183c)

**Comment by Smiggel** [comment]
Personally I like the 1 column layout the most. But it’s great if anyone can set the amount of columns they prefer. 👍

**Comment by JPKribs** [comment]
There may be some changes required but I believe I have this working. PR can be found here: https://github.com/jellyfin/Swiftfin/pull/1213
