### ISSUE TITLE
Swiftfin triggering Crowdsec http-probing ban

### ISSUE THREAD

**Issue by Sixth2538** [jellyfin/Swiftfin#690]
Setup:
Docker Jellyfin server 10.8.8
Traefik proxy
Crowdsec
iOS Swiftfin

Problem:
Crowdsec http-probing bouncer is triggered thus temporarily banning when connecting to media server with Swiftfin. 

Other information:
This problem only occurs with Swiftfin. Other access over web, iOS Jellyfin and does not trigger such issue, and neither does my other self hosted services.

Here is a description on Crowdsec http-probing bouncer:
https://hub.crowdsec.net/author/crowdsecurity/configurations/http-probing

Swiftfin has been an amazing addition to the Jellyfin eco system and has been blazing fast and smooth for me. Hope there is a simple fix to this issue.

Thank you dev for your time.

**Comment by LePips** [comment]
If the issue comes from a bunch of 4XX calls, the only thing I can recommend is making sure the http/https scheme is correct. Other than that, there's nothing we can do on our end.

**Comment by Sixth2538** [comment]
Updated my docker-compose with recommended traefik setting from Jellyfin doc, changed network scheme on Swiftfin settings to “https” and tried on all other platform. Only loading homepage on Swiftfin triggers http-probing ban. 

No problem streaming afterwards when manually unbanning myself.

As it only happen on Swiftfin, not with my other self-hosted services, just thought I’d bring it to attention over here.

**Comment by jameskimmel** [comment]
I am having the same issue. Looking at the NGINX logs, the reason for this false positive of crowdsec, is Jellyfin having multiple 404 errors.

First this error once
```
IP_of_external_client - - [15/Oct/2023:18:35:30 +0200] "GET /Branding/Splashscreen HTTP/2.0" 404 161 "-" "Swiftfin%20tvOS/70 CFNetwork/1474 Darwin/23.0.0"
```

than multiple entries like this
```
IP_of_external_client - - [15/Oct/2023:18:38:01 +0200] "GET /Items/f2475f94833aafb8fc0adf80508f6f85/Images/thumb?maxWidth=700 HTTP/2.0" 404 53 "-" "Swiftfin%20tvOS/70 CFNetwork/1474 Darwin/23.0.0"
```
and this
```
IP_of_external_client - - [15/Oct/2023:18:38:05 +0200] "GET /Items/6e6d2a411eedcaeccff46ba265a6a26c/Images/primary?maxWidth=400 HTTP/2.0" 404 98 "-" "Swiftfin%20tvOS/70 CFNetwork/1474 Darwin/23.0.0"
```
and this
```
IP_of_external_client - - [15/Oct/2023:18:38:01 +0200] "GET /Items/8455c12f017be45a726e6a0be5fe9c01/Images/thumb?maxWidth=700 HTTP/2.0" 404 43 "-" "Swiftfin%20tvOS/70 CFNetwork/1474 Darwin/23.0.0"
```

Let me know if I can help you with additional details. 
@LePips could you please reopen this?

**Comment by LePips** [comment]
Thank you for posting these logs, they come from items that have no images. This got me thinking as currently we will request images from items without checking even if they have the necessary image via the `BaseItemDto`'s tags, which I looked and the web seems to do this.

I see this as more of an optimization, instead of it directly fixing this issue, as I don't want to necessarily make changes for specific networking setups.

I have made a proper issue to track this as you can see in the linked issue.
