### ISSUE TITLE
Dolby Vision not activated

### ISSUE THREAD

**Issue by smidley** [jellyfin/Swiftfin#693]
### Describe the bug

When playing an MKV file with Dolby Vision video, it's only displaying in SDR.  I have compared this playback with Infuse and don't have the same issue with the same file.

### Application version

1.0.0(74)

### Where did you install the app from?

App Store

### Device information

iPhone 11 Pro and Apple TV 4K 3rd Gen

### OS version

iOS 16.3 and tvOS 16.3

### Jellyfin server version

10.8.9

**Comment by smidley** [comment]
This applies to Dolby Vision also.

**Comment by holow29** [comment]
https://github.com/jellyfin/Swiftfin/issues/525
