### ISSUE TITLE
Airplay playback is missing

### ISSUE THREAD

**Issue by iwa** [jellyfin/Swiftfin#698]
**Describe the feature you'd like**
When watching a video, it's not possible to airplay the content to an Apple TV or a Mac
When using the screen mirroring and launching a video, it keeps mirroring the screen instead of starting an Airplay video playback

**Additional context**
I can provide a little screen recording if needed

**Comment by LePips** [comment]
VLCKit does not support Airplay, I will also consider this duplicate of #606

**Comment by iwa** [comment]
that's strange because the official vlc ios app has the feature, so it should be possible to add it in a way, right?
