### ISSUE TITLE
Swift package manager can't  resolvePackageDependencies

### ISSUE THREAD

**Issue by yangtianxiang0313** [jellyfin/Swiftfin#705]
### Describe the bug

  Dependencies could not be resolved because no versions of 'swift-algorithms' match the requirement 1.0.0..<2.0.0 and root depends on 'swift-algorithms' 1.0.0..<2.0.0.

### Application version

main

### Where did you install the app from?

None

### Device information

any

### OS version

any

### Jellyfin server version

any

**Comment by LePips** [comment]
There are a lot of packages, so sometimes Xcode quits before it can resolve. The only solution is to reset the package cache or re-open Xcode.
