### ISSUE TITLE
Bar Still Exists

### ISSUE THREAD

**Issue by zshc** [jellyfin/Swiftfin#706]
### Describe the bug

When playing a video on an iPhone 10, the bar still exists on the bottom.
![IMG_0098](https://user-images.githubusercontent.com/62533831/220538638-f1a9fd6b-cb98-4fe8-ad89-501efd795382.jpg)

### Application version

1.0.0(79)

### Where did you install the app from?

App Store

### Device information

iPhone 10

### OS version

iOS 16.1.1

### Jellyfin server version

10.8.9

**Comment by LarsCelie** [comment]
I have the same issue on IPhone 10S

**Comment by JesseChen64u** [comment]
I have the same issue on IPhone 14
iOS16.3.1

**Comment by LarsCelie** [comment]
Maybe related? https://github.com/apache/cordova-ios/issues/919

**Comment by LarsCelie** [comment]
Or maybe this? https://developer.apple.com/documentation/uikit/uiviewcontroller/2887510-prefershomeindicatorautohidden

**Comment by LePips** [comment]
Duplicate: #582
