### ISSUE TITLE
TvOS: Unable enter search bar

### ISSUE THREAD

**Issue by Dereen** [jellyfin/Swiftfin#707]
### Describe the bug

Im unable enter to search bar after first search. I need to reinstall app to search again.

### Application version

1.0.0 (64)

### Where did you install the app from?

App Store

### Device information

AppleTV 4k 

### OS version

1.0.0 (64)

### Jellyfin server version

10.8.9

**Comment by LePips** [comment]
I don't see this issue on latest `main`.
