### ISSUE TITLE
TvOS Slow Interface

### ISSUE THREAD

**Issue by Peroids** [jellyfin/Swiftfin#708]
Hello,

I really appreciate the hard work that goes on behind the scenes.

I have Swiftfin for TvOS and it's unusable, when I try scrolling everything lags. I've never had this issue with any other TvOS app.

I don't really know what to do.

**Comment by obxjames** [comment]
Im seeing the same thing, however only on my Apple TV HD variant. The Apple TV 4K doesn't seem to be an issue. I'm happy to get some debug logs if that will help anyone.

**Comment by Peroids** [comment]
You're right, I do not have the Apple TV 4K but I made an assumption that might've been the problem

**Comment by igwall** [comment]
I got the issue on the 4K one 😅

**Comment by snod** [comment]
I switched from an Apple TV HD where the app was unusable to an Apple TV 4K (128) and gave it a try to see if maybe works now. And to my surprise the app is running perfectly fine on it.

**Comment by thornbill** [comment]
An update (version 1.0.1) just went out yesterday that should help with this I believe.

**Comment by LePips** [comment]
Duplicate: #619
