### ISSUE TITLE
SkipIntro Integration

### ISSUE THREAD

**Issue by mattipunkt** [jellyfin/Swiftfin#709]
**Describe the feature you'd like**

Just a function that was recently added to the Jellyfin Media Player for Desktops. Allows an Intro-Skip Button when the IntroSkipper Plugin by ConfusedPolarBear detected an intro in a TV Show
**Additional context**

**Comment by crobibero** [comment]
> Note: Adding support for this is intended to alleviate the alternative which is people manually patching the client. Please do not bother other Jellyfin client maintainers to add unofficial plugin support. In the event that official Jellyfin functionality replaces unofficial plugins or renders them unusable, unofficial plugins will be dropped.

From https://github.com/jellyfin/jellyfin-media-player/releases/tag/v1.8.1
