### ISSUE TITLE
Subtitles won't play on native player

### ISSUE THREAD

**Issue by kabdelhalem** [jellyfin/Swiftfin#710]
### Describe the bug

I'm using the native player because 5.1 channels don't sound correct on the regular player (i.e center channel doesn't play). Using the native player on tvOS, my subtitle options are Automatic, Off or CC, neither Automatic or CC plays any subtitle tracks that are on the movie/show. 

### Application version

1.0.0(84)

### Where did you install the app from?

App Store

### Device information

Apple TV 4K 3d generation (A2843)

### OS version

tvOS 16.3.2

### Jellyfin server version

10.8.9

**Comment by LePips** [comment]
See: https://github.com/jellyfin/Swiftfin/issues/684
