### ISSUE TITLE
Crashes when selecting a movie/show

### ISSUE THREAD

**Issue by everdrone** [jellyfin/Swiftfin#716]
### Describe the bug

1. Open SwiftFin on apple TV
2. Select any movie or show
3. Crashes

### Application version

latest

### Where did you install the app from?

App Store

### Device information

Apple TV 4k

### OS version

tvOS 16.3.2

### Jellyfin server version

10.7.8

**Comment by jester-xbmc** [comment]
Try updating your server to the latest version ?

Side note (not to take over this Issue) I'm running both the latest swiftfin on TVOS and server and no issues except one movie which makes it crash on entry

**Comment by everdrone** [comment]
Hi, I looked more into the logs and turns out I was missing ffmpeg on my server, so the web client couldn't stream either.

It should probably be handled as an error with an alert on Apple TV, but encoding was the issue ultimately
