### ISSUE TITLE
Split screen multitasking on iPad?

### ISSUE THREAD

**Issue by rachtsingh** [jellyfin/Swiftfin#717]
**Describe the feature you'd like**
It would be fantastic if this app supported split-screen multi-tasking on the iPad. This essentially means that you can split the view in half, with Swiftfin on the left half and another app on the right half.

**Additional context**
I think this can be achieved by first removing the “UIRequiresFullScreen” entitlement, then *possibly* implementing `traitCollectionDidChange` (see [here](https://developer.apple.com/documentation/uikit/app_and_environment/multitasking_on_ipad)). I recognize this might be a niche ask, but I suspect it might be as simple as that, since layout might not need to change; I don’t understand SwiftUI at all, though.

**Comment by LePips** [comment]
Duplicate: #321
