### ISSUE TITLE
New Build for iOS TestFlight

### ISSUE THREAD

**Issue by IchBinGROOT** [jellyfin/Swiftfin#725]
As the problems with the iOS TestFlight beta are now hopefully over (i.e. those people who just want to use the app can download it from the App Store now), do you have plans to reopen the TestFlight, maybe resetting the people in it? 
I have no problem with using the App Store version of the app, but I really like the project and would like to continue to support it even if it is only by testing not yet public versions, as I am not familiar enough with Swift to help coding.

**Comment by LePips** [comment]
We do have plans to reset the TestFlight so that people who are actually interested in beta builds can rejoin.
