### ISSUE TITLE
Add the capability to display the library folders 

### ISSUE THREAD

**Issue by tdavidesrifrance** [jellyfin/Swiftfin#733]
Hello, first, thank you for your work for this apps :)
This is my enhancement request...
My personal videos (like tutorial videos) are organized in folders and have no metadata. In Swiftfin, they all appear at the same time. I would like folder view to be available.
thanks in advance :)
Thomas

**Comment by Sector14** [comment]
As with the above poster, I'd like to see this too.

I have a "Videos" library added in Jellyfin under the "other" type that also contains misc items that would not fit in Movies or TV Shows and are best browsed via folder and file name. 

In the Jellyfin web client this is broken out into browsable per-folder views. Infuse does the same on iOS. Swiftfin however lists everything in one giant list.

In addition, the top nav bar with "Movies" shows all those "other" items in the movies list too. The only way to view just movies is going to "Media" in the top bar then "Movies". 

Infuse on the other hand, appears to show libraries in the same way as the web client.

**Comment by LePips** [comment]
Folders are enabled by first enabling:

`Dashboard -> Libraries -> Display -> Display a folder view to show plain media folders`

and then is able to be shown on the `Media` tab. How is this any different?

**Comment by rburettt** [comment]
Hi,

I have tutorials organized like this:
masterclass/programming/python/some-course.

On the app, I can see that there is a folder view that lists every folder under masterclass when I click on it. But when I click on folder masterclass/programming for instance it does shows the folders in the directory  but instead recursively list everything video under masterclass/programming.

Is it the expected behaviour?

**Comment by Sector14** [comment]
Folders view is _almost_ what I want, but as rburett mentions, it only has a limited number of nested folders before every video in any subsequent folder is instead listed as one flat view and any futher sub-folders are lost.

In my case when I go into Videos/Computers/ every video within any further sub-directory is listed all in the same level. All the sub-folders such as Videos/Computers/Programming/... or Videos/Computers/Retro/... are not showing. Instead the videos within Programming or Retro are all shown in a single list within Videos/Computers/ 

Infuse provides a view much like the jellyfin web ui does, where in "My Media" I'll see a Videos item, in that Computers, within that Programming, Retro, ...

The web ui also shows the "Folders" item when enabled, however in the web ui it works as I'd expect. Any item that has sub-folders shows the sub folders no matter how many levels deep you may have them. If Swiftfin worked in the same way then going via the "Folders" option would be fine I think.
