### ISSUE TITLE
mTLS support

### ISSUE THREAD

**Issue by kiwiz** [jellyfin/Swiftfin#736]
**Describe the feature you'd like**
Support for specifying a client certificate in the iOS client, for Jellyfin servers behind a reverse proxy with TLS client authentication.

**Additional context**

**Comment by LePips** [comment]
Duplicate of #379

**Comment by kiwiz** [comment]
Hi, thanks for taking a look. I don't think this is quite a duplicate of the other feature request. That one involves specifying a custom CA for the Swiftfin client to validate the server certificate against. This feature request is to allow specifying a client certificate in the Swiftfin client that will be used by the server to validate the client.

**Comment by LePips** [comment]
Ah I apologize, however the result will be the same: I have no intention of custom client certificate selection whatsoever.

**Comment by kiwiz** [comment]
Oh, that's a bummer. Thanks for clarifying :+1:

**Comment by mertalev** [comment]
Is this something you’d consider as a PR? I recently implemented mTLS for URLSession in the Immich app and it wasn’t much code (basically a file picker and a URLSession delegate callback). Of course, it depends on how network requests are done in Swiftfin.

**Comment by Ecco** [comment]
Note: Do we even need a picker? One can add a `.p12` file in iOS directly, which is picked up by Mobile Safari. Swiftfin could simply do the same, which doesn't require any extra UI.

**Comment by mertalev** [comment]
Unfortunately not. Safari will use client certificates in the OS store, but other apps aren't allowed to on iOS (presumably for security reasons).
