### ISSUE TITLE
Autoplay not happening - One episode is picked, plays, then just stops

### ISSUE THREAD

**Issue by Neoakb** [jellyfin/Swiftfin#737]
### Describe the bug

Friend installs swiftfin on Apple TV (the fat one with the semi touch remote) and says it only will play one ep, then just stops. It doesn't end the episode either, it just pauses at the end of the stream. 

I unfortunately can't provide a lot more details, I'm not near the person who's having the issue and she isn't the most tech savy. 
I did have to get her to check "use native player" to get anything to show up at all as before that an ep would start, but it didn't show any video or play any audio, though on my sever end it showed it was playing like normal. 

I can provide any server side info as requested.

### Application version

1.0.0

### Where did you install the app from?

App Store

### Device information

Apple TV - Fat

### OS version

Unknown, thought she seems like she has the default settings, so if it has auto update I would assume it's updated.

### Jellyfin server version

10.8.9

**Comment by eval-on-point** [comment]
I've experienced this and am happy to produce diagnostic information if that would be helpful. I unfortunately do not have the time to dig in and fix it myself.

**Comment by zguithues** [comment]
On of my users is also experiencing swiftfin not playing the next episode.  Says it started randomly about a week ago.  Any suggestions would be welcome

**Comment by pdtheowl** [comment]
I am experiencing this too

**Comment by howdy-im-david** [comment]
Just noting that I also am having this issue and happy to provide any diag information as required to help resolve.

**Comment by FabulousSoldier** [comment]
I am experiencing the same on an Apple TV 4k 2022.

**Comment by maximecurioni** [comment]
I also experienced this issue yesterday. In my case, it was due to the native player being on.

Turning the native player off resolved the issue for me.

**Comment by weirdofhermiston** [comment]
I'm also having this issue and can provide diag info too

**Comment by zguithues** [comment]
i don't have an apple tv, but one of my main users does.  he has reported the issue after i have reset the server, meaning swiftfin has to remake the connection.  he has found if he completely uninstalls the app, and reinstalls, it works fine.  until i restart the server.

i just instructed him to try disabling the native player and will report if it fixes it

**Comment by FabulousSoldier** [comment]
Today, I discovered that there's a button in the player to toggle autoplay on and off. This revelation explained why autoplay wasn't working on my Apple TV – it simply wasn't enabled in the player.

![swiftfin](https://github.com/jellyfin/Swiftfin/assets/4923534/d9e499bb-4832-48f8-bce1-135bde1a3d32)

I'm sharing this information in case others encounter a similar issue. However, I'd like to suggest considering also placing this autoplay switch within a settings menu as the button's functionality might not be immediately apparent to users within the player interface.

**Comment by Stetsed** [comment]
So I use the iOS app on my iPad mini 6th gen, and I noticed this same issue which was annoying. I see that disabling the native player lets me select it and does fix the not auto playing issue. 

However I do hope this can be fixed in the native player as it would allow me to have better format/HDR support while watching it on there.

**Comment by LePips** [comment]
If this entire issue is just that auto play doesn't work with the native player, that's because it isn't supported in the native player.

**Comment by mrjones2014** [comment]
I'm having this issue and the native player is not on in settings. Any helpful info I can get for you?
