### ISSUE TITLE
Swiftfin on TVOS 16.1.1 crashes with some abnormal subtitles

### ISSUE THREAD

**Issue by lavavex** [jellyfin/Swiftfin#740]
Weirdly formatted subtitles can cause Swiftfin to crash on tvos 16.1.1 and drop frames really bad on iOS 15.4.1 (not sure if it matters, but putting ios version here anyways) Here is a photo of the subtitles causing the issue as the video doesnt crash on my iPhone. (leave my trash taste in anime alone, i know its trash, but i enjoy the trash)
![IMG_0009](https://user-images.githubusercontent.com/27239435/230532833-f7980fea-ca97-4c31-9a51-5c915e5ac3c0.PNG)

Its about 10 minutes into the video, I'll link the extracted subtitle file below as well.
[subtitles.ass.zip](https://github.com/jellyfin/Swiftfin/files/11175802/subtitles.ass.zip)

Here is the output of ffmpeg -i

> Input #0, matroska,webm, from '/Volumes/Data/Media/TV/Iseleve/I Got a Cheat Skill in Another World and Became Unrivaled in the Real World, Too - 01 - To Another World.mkv':
  Metadata:
    encoder         : libebml v1.4.2 + libmatroska v1.6.4
    creation_time   : 2023-04-04T10:30:44.000000Z
  Duration: 00:24:00.08, start: 0.000000, bitrate: 8155 kb/s
  Stream #0:0(jpn): Video: h264 (High), yuv420p(tv, bt709, progressive), 1920x1080 [SAR 1:1 DAR 16:9], 23.98 fps, 23.98 tbr, 1k tbn (default)
    Metadata:
      BPS             : 7982746
      DURATION        : 00:23:59.982000000
      NUMBER_OF_FRAMES: 34525
      NUMBER_OF_BYTES : 1436876467
      _STATISTICS_WRITING_APP: mkvmerge v70.0.0 ('Caught A Lite Sneeze') 64-bit
      _STATISTICS_WRITING_DATE_UTC: 2023-04-04 10:30:44
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:1(jpn): Audio: aac (LC), 44100 Hz, stereo, fltp (default)
    Metadata:
      BPS             : 127999
      DURATION        : 00:24:00.032000000
      NUMBER_OF_FRAMES: 62017
      NUMBER_OF_BYTES : 23040511
      _STATISTICS_WRITING_APP: mkvmerge v70.0.0 ('Caught A Lite Sneeze') 64-bit
      _STATISTICS_WRITING_DATE_UTC: 2023-04-04 10:30:44
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:2(eng): Subtitle: ass (default)
    Metadata:
      title           : English
      BPS             : 194
      DURATION        : 00:23:51.960000000
      NUMBER_OF_FRAMES: 341
      NUMBER_OF_BYTES : 34765
      _STATISTICS_WRITING_APP: mkvmerge v70.0.0 ('Caught A Lite Sneeze') 64-bit
      _STATISTICS_WRITING_DATE_UTC: 2023-04-04 10:30:44
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:3(por): Subtitle: ass
    Metadata:
      title           : Portuguese(Brazil)
      BPS             : 176
      DURATION        : 00:23:51.960000000
      NUMBER_OF_FRAMES: 296
      NUMBER_OF_BYTES : 31624
      _STATISTICS_WRITING_APP: mkvmerge v70.0.0 ('Caught A Lite Sneeze') 64-bit
      _STATISTICS_WRITING_DATE_UTC: 2023-04-04 10:30:44
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:4(spa): Subtitle: ass
    Metadata:
      title           : Spanish(Latin_America)
      BPS             : 158
      DURATION        : 00:23:51.890000000
      NUMBER_OF_FRAMES: 279
      NUMBER_OF_BYTES : 28381
      _STATISTICS_WRITING_APP: mkvmerge v70.0.0 ('Caught A Lite Sneeze') 64-bit
      _STATISTICS_WRITING_DATE_UTC: 2023-04-04 10:30:44
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:5(spa): Subtitle: ass
    Metadata:
      title           : Spanish
      BPS             : 157
      DURATION        : 00:23:51.890000000
      NUMBER_OF_FRAMES: 279
      NUMBER_OF_BYTES : 28250
      _STATISTICS_WRITING_APP: mkvmerge v70.0.0 ('Caught A Lite Sneeze') 64-bit
      _STATISTICS_WRITING_DATE_UTC: 2023-04-04 10:30:44
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:6(fre): Subtitle: ass
    Metadata:
      title           : French
      BPS             : 117
      DURATION        : 00:23:52.050000000
      NUMBER_OF_FRAMES: 248
      NUMBER_OF_BYTES : 21093
      _STATISTICS_WRITING_APP: mkvmerge v70.0.0 ('Caught A Lite Sneeze') 64-bit
      _STATISTICS_WRITING_DATE_UTC: 2023-04-04 10:30:44
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:7(ger): Subtitle: ass
    Metadata:
      title           : German
      BPS             : 220
      DURATION        : 00:23:52.060000000
      NUMBER_OF_FRAMES: 331
      NUMBER_OF_BYTES : 39387
      _STATISTICS_WRITING_APP: mkvmerge v70.0.0 ('Caught A Lite Sneeze') 64-bit
      _STATISTICS_WRITING_DATE_UTC: 2023-04-04 10:30:44
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:8(ita): Subtitle: ass
    Metadata:
      title           : Italian
      BPS             : 163
      DURATION        : 00:23:52.030000000
      NUMBER_OF_FRAMES: 289
      NUMBER_OF_BYTES : 29193
      _STATISTICS_WRITING_APP: mkvmerge v70.0.0 ('Caught A Lite Sneeze') 64-bit
      _STATISTICS_WRITING_DATE_UTC: 2023-04-04 10:30:44
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:9(rus): Subtitle: ass
    Metadata:
      title           : Russian
      BPS             : 345
      DURATION        : 00:23:52.190000000
      NUMBER_OF_FRAMES: 365
      NUMBER_OF_BYTES : 61888
      _STATISTICS_WRITING_APP: mkvmerge v70.0.0 ('Caught A Lite Sneeze') 64-bit
      _STATISTICS_WRITING_DATE_UTC: 2023-04-04 10:30:44
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:10: Attachment: ttf
    Metadata:
      filename        : arialbd.ttf
      mimetype        : application/x-truetype-font
  Stream #0:11: Attachment: ttf
    Metadata:
      filename        : arialbi.ttf
      mimetype        : application/x-truetype-font
  Stream #0:12: Attachment: ttf
    Metadata:
      filename        : Arial_0.ttf
      mimetype        : application/x-truetype-font
  Stream #0:13: Attachment: ttf
    Metadata:
      filename        : ariblk_0.TTF
      mimetype        : application/x-truetype-font
  Stream #0:14: Attachment: ttf
    Metadata:
      filename        : calibri.ttf
      mimetype        : application/x-truetype-font
  Stream #0:15: Attachment: ttf
    Metadata:
      filename        : comicbd.ttf
      mimetype        : application/x-truetype-font
  Stream #0:16: Attachment: ttf
    Metadata:
      filename        : comic_0.ttf
      mimetype        : application/x-truetype-font
  Stream #0:17: Attachment: ttf
    Metadata:
      filename        : georgiab.ttf
      mimetype        : application/x-truetype-font
  Stream #0:18: Attachment: ttf
    Metadata:
      filename        : georgiaz.ttf
      mimetype        : application/x-truetype-font
  Stream #0:19: Attachment: ttf
    Metadata:
      filename        : georgia_0.ttf
      mimetype        : application/x-truetype-font
  Stream #0:20: Attachment: ttf
    Metadata:
      filename        : impact_0.ttf
      mimetype        : application/x-truetype-font
  Stream #0:21: Attachment: ttf
    Metadata:
      filename        : Tahoma_0.ttf
      mimetype        : application/x-truetype-font
  Stream #0:22: Attachment: ttf
    Metadata:
      filename        : times_0.ttf
      mimetype        : application/x-truetype-font
  Stream #0:23: Attachment: ttf
    Metadata:
      filename        : trebuc_0.ttf
      mimetype        : application/x-truetype-font
  Stream #0:24: Attachment: ttf
    Metadata:
      filename        : verdana_0.ttf
      mimetype        : application/x-truetype-font
  Stream #0:25: Attachment: ttf
    Metadata:
      filename        : AdobeArabic-Bold.otf
      mimetype        : application/x-truetype-font
  Stream #0:26: Attachment: ttf
    Metadata:
      filename        : AdobeArabic-BoldItalic.otf
      mimetype        : application/x-truetype-font
  Stream #0:27: Attachment: ttf
    Metadata:
      filename        : AdobeArabic-Italic.otf
      mimetype        : application/x-truetype-font
  Stream #0:28: Attachment: ttf
    Metadata:
      filename        : AdobeArabic-Regular.otf
      mimetype        : application/x-truetype-font

**Comment by LePips** [comment]
I'm going to have to say that this is a VLCKit issue, at that point the sub rendering is at that layer.
