### ISSUE TITLE
AirPlay should continue to work while app is backgrounded

### ISSUE THREAD

**Issue by slocook** [jellyfin/Swiftfin#741]
**Describe the feature you'd like**
When using the Native Player with AirPlay on iOS, the video should continue to play on the AirPlay receiver while the iPhone app is backgrounded. Currently, if I AirPlay to my TV and then switch to another app, the AirPlay session stops.

**Additional context**
There is a really simple fix for this by changing the Background Mode in capabilities in Xcode settings.

**Comment by LePips** [comment]
Apologies for not merging your PR first, this was also implemented in #786.
