### ISSUE TITLE
Two-finger tap to pause/resume playback

### ISSUE THREAD

**Issue by dertasiu** [jellyfin/Swiftfin#743]
**Describe the feature you'd like**
When you tap on the screen with two fingers it should pause and resume the video similar to how [VLC works](https://wiki.videolan.org/Documentation:IOS#Gestures) .

**Additional context**
I just updated my iPad to iOS 16.3.1 just so I can finally try this app. The gestures are a nice feature.

**Comment by LePips** [comment]
Forgot to close is as part of #593
