### ISSUE TITLE
Airplay audio output support

### ISSUE THREAD

**Issue by advinliu** [jellyfin/Swiftfin#746]
I am using Swiftfin 1.0.1(70) on my appleTV 4K gen2. When I was in tvOS 16.3, I can output audio to my pair of HomePod gen2 (eARC) and airplay to pair of HomePod mini at the same time as temporary audio output. However after 16.4 update this is no longer working, and only the pair of eARC HomePod got the audio
Output.
Tried switch to Apple Music app or YouTube app, all 4 HomePod can act as audio output as before. Tried to unplug and restart all the devices, including the appleTV but no luck. 
Realized for those apps that make airplay successful (Apple Music, youtube), they will show a pop up on my iPhone when playing for media control, but not for Swiftfin. Is it the reason for unable to do airplay (I guess the player is not supported?)

**Comment by LePips** [comment]
Sadly, this is a limitation of VLCKit and nothing that we can do about it.

**Comment by dilipva** [comment]
Vlc player itself works with airplay for audio without any issues.
