### ISSUE TITLE
Auto sign off user after the app goes to background

### ISSUE THREAD

**Issue by ispiropoulos** [jellyfin/Swiftfin#747]
**Describe the feature you'd like**
On our home we have 3 users. Two adults (my spouse and myself) as well as our child.

On our Apple TV, if an adult logs in their account, it remains logged in even if the app goes to background and even if it's terminated.

The requested feature is:

When the app goes to background and then is brought back to foreground, show the profile selector so that the user can pick their account and enter their Easy PIN code.

**Comment by LePips** [comment]
Dev notes: have this be an option to:
1 - do nothing when backgrounded
2 - go to current server user selection screen
3 - go to server selection screen

**Comment by radaiko** [comment]
Hi, I wanted to switch from Plex to Jellyfin but I can't because this feature is missing.
Without that it's not possible to use it on an Apple TV with kids!

**Comment by shiftoptk** [comment]
+1 - This is a desirable feature when we have accounts with access restrictions in the same household.
