### ISSUE TITLE
TestFlight - "This beta isn't accepting any new testers right now."

### ISSUE THREAD

**Issue by Jpkribs** [jellyfin/Swiftfin#753]
I've been following [this PR](https://github.com/jellyfin/Swiftfin/pull/593) and was excited to see it get merged in this week. TestFlight gave me an expired build warning for SwiftFin so I tried re-adding it and got "This beta isn't accepting any new testers right now."

I know from [this issue](https://github.com/jellyfin/Swiftfin/issues/628) ya'll we're letting the existing TF instance expire to help clean up some of the unused seats. Is TestFlight going to be open to testers or should I just sit tight for changes to hit the App Store?

Thanks for everything y'all have been doing on this!

**Comment by LePips** [comment]
We will empty the TestFlight shortly and announce with the new/existing link.

**Comment by Jpkribs** [comment]
Perfect! Thank you.

**Comment by jfrcom** [comment]
When can we expect the TestFlight instance to be open to new users? Really looking forward to it!

**Comment by thornbill** [comment]
[When it's ready](https://jellyfin.org/docs/general/faq#when-will-release-x-happen-when-will-feature-x-be-available) 😉
