### ISSUE TITLE
Ability to Disable Autoplay

### ISSUE THREAD

**Issue by haydenstith** [jellyfin/Swiftfin#756]
**Describe the feature you'd like**
Under the settings menu there should be an option to disable autoplay. 

**Additional context**
Not proud to admit this but I use the sleep function of my Apple TV quite often if I doze off while watching a show. Unfortunately I cannot disable autoplay so instead of an episode ending and my TV turning off, I can wake up and find myself in a whole other season.

**Comment by LePips** [comment]
Auto play can be disabled by pressing the play/stop looking button. If it looks like the stop button, then auto play is off.

In my recent work I have made it so buttons are more customizable so it is (more) clear what each button does and where they show up on the player.

**Comment by Kivylius** [comment]
I know this already closed and thanks for the help @LePips but I had to google how to do this, so it’s not very intuitively placed ui , maybe also add it to setting as just as op we both could not find it very easy ? Thanks for you work
