### ISSUE TITLE
a08a92e introduced a crash on tvOS 16.4.1

### ISSUE THREAD

**Issue by romantomjak** [jellyfin/Swiftfin#768]
### Describe the bug

1. Go to detail view of any video
2. Tap on "Play"
3. Application crashes

SwiftUI/EnvironmentObject.swift:82: Fatal error: No ObservableObject of type VideoPlayerViewModel found. A View.environmentObject(_:) for VideoPlayerViewModel may be missing as an ancestor of this view.
2023-05-07 18:31:42.624253+0100 Swiftfin tvOS[531:74054] SwiftUI/EnvironmentObject.swift:82: Fatal error: No ObservableObject of type VideoPlayerViewModel found. A View.environmentObject(_:) for VideoPlayerViewModel may be missing as an ancestor of this view.

No crashes if I checkout 87738af58744b1280da365aa94a29602172c7015 which is just before the a08a92e98ae3306f9464a5f34202534436f0def2

### Application version

a08a92e98ae3306f9464a5f34202534436f0def2

### Where did you install the app from?

None

### Device information

Apple TV 4K

### OS version

tvOS 16.4.1

### Jellyfin server version

10.8.10

**Comment by LePips** [comment]
Yes, my hunch is that something was changed in Swift 5.8 but I haven't looked deeply into it yet.

**Comment by romantomjak** [comment]
Thanks for taking a look, but I'm still seeing a crash with the same error message 🙈

**Comment by LePips** [comment]
My bad, I forgot tvOS in #774. Fix is now #779.
