### ISSUE TITLE
Episodes show up as “no results”

### ISSUE THREAD

**Issue by buggerman** [jellyfin/Swiftfin#773]
### Describe the bug

1. Go to any show
2. Episodes show up as “no results” (screenshot)
3. Click seasons, and change the season
4. Switch to original season where it was showing “no results” and it will now show episodes

screenshot:
![IMG_0371](https://github.com/jellyfin/Swiftfin/assets/11626756/4690af85-3bff-4eda-9db8-d1d2f0d93f5a)

### Application version

1.0.1(78)

### Where did you install the app from?

App Store

### Device information

iPhone 13

### OS version

iOS 16.4.1 (a)

### Jellyfin server version

10.8.10

**Comment by nerethos** [comment]
This bug also causes the app to crash if there is only one season available. Also present on TVOS.

**Comment by buggerman** [comment]
If you tap the season drop down and tap season 1, it shows the episodes and generally doesn't crash.

**Comment by revam** [comment]
Is this the same issue as #653?

**Comment by buggerman** [comment]
> Is this the same issue as #653?

Yes, I think it is similar.

**Comment by mhackdo18** [comment]
Up for this same! Need to click the season..

**Comment by Jurrer** [comment]
I have been experiencing the same issue regardless of the series.
I always have to select it manually from the list to load the episodes

**Comment by devPDG** [comment]
I am also getting the same issue. Selecting it will crash the app.

**Comment by qdore** [comment]
+1, it is super weird for me
