### ISSUE TITLE
iOS Dynamic Island Screen Size

### ISSUE THREAD

**Issue by patdavid** [jellyfin/Swiftfin#789]
### Describe the bug

Playing a movie expands to fill the screen but doesn't take into account the gutter for the dynamic island (rendering the movie _behind_ the dynamic island).  The official jellyfin iOS app _sort of_ does this as well (only extending about halfway into the dynamic island).

### Application version

1.0.1 (78)

### Where did you install the app from?

App Store

### Device information

iPhone 14 Pro Max

### OS version

iOS 16.5 (20F66)

### Jellyfin server version

10.8.10

**Comment by LePips** [comment]
Replaced by #944.
