### ISSUE TITLE
Sync settings information between devices using iCloud

### ISSUE THREAD

**Issue by rexzhang** [jellyfin/Swiftfin#792]
**Describe the feature you'd like**
like as infuse

**Comment by LePips** [comment]
I will have to _think_ about this because Jellyfin has profiles and I will eventually want to have individual settings per user.

**Comment by rexzhang** [comment]
Yes, I missed the multi-user problem.

**Comment by LePips** [comment]
I'm kind of open to still have this, I'll probably just have the server + user ID pair as the unique identifier for settings across users across devices.
