### ISSUE TITLE
Apple TV https not connecting 

### ISSUE THREAD

**Issue by BashyBoy** [jellyfin/Swiftfin#801]
### Describe the bug

After setting up https with jellyfin server handling the port hosting, using a personal ssl through let’s encrypt, jelly fin does not allow your to connect to the server from Apple TV. 

The iOS mobile app had similar issues but just happen to disappear by using safari to access the https site and choosing the options to proceed to visit the site because of the ssl cert not being trusted by safari. This seem to allow iOS to use the certificate. 

AppleTV seems to be blocking the ssl certificate and there is no way to have the box accept this certificate. 

### Application version

Latest 

### Where did you install the app from?

None

### Device information

AppleTV 

### OS version

15

### Jellyfin server version

Latest

**Comment by LePips** [comment]
Please see: #379
