### ISSUE TITLE
Question: Is an update Due?

### ISSUE THREAD

**Issue by eximo84** [jellyfin/Swiftfin#808]
Seems like there hasn't been any updates recently especially for TVOS which is the main reason I'm using the app. 

Recently noticed some additional UI bugs since upgrading to TVOS 17.

**Comment by LePips** [comment]
I haven’t used tvOS 17 yet, so yes I’ll make an issue to address any issues that I see with it.

**Comment by sa7mon** [comment]
@anthonylavado Any reason there hasn’t been a new release in a year?

**Comment by thornbill** [comment]
https://jellyfin.org/docs/general/faq#when-will-release-x-happen-when-will-feature-x-be-available
