### ISSUE TITLE
tvOS - Signing out of server constantly

### ISSUE THREAD

**Issue by ioslife** [jellyfin/Swiftfin#809]
### Describe the bug

Every time I open SwiftFin, it asks me to connect to the server again. It’s like it is failing to store the server and user information in UserDefaults or something. 

### Application version

Updated

### Where did you install the app from?

App Store

### Device information

Apple TV 4K

### OS version

16.6

### Jellyfin server version

10.7.6

**Comment by thornbill** [comment]
Duplicate of #776

Just a heads up, you are also on an unsupported version of the Jellyfin server.

**Comment by ioslife** [comment]
@thornbill Hi, I’m actually on 10.8.10. Where can I find supported versions?
