### ISSUE TITLE
Swiftfin iOS ChromeCast Support

### ISSUE THREAD

**Issue by trickbaze** [jellyfin/Swiftfin#813]
### Describe the bug

Is there anyway to use ChromeCast support in Swiftfin? Or did i need get applied for the Testflight version?

### Application version

1.0.1(78)

### Where did you install the app from?

App Store

### Device information

iPhone 14 Pro

### OS version

iOS 17 (beta)

### Jellyfin server version

10.8.10

**Comment by thornbill** [comment]
Duplicate of #271
