### ISSUE TITLE
Audio track is delayed

### ISSUE THREAD

**Issue by premalone69** [jellyfin/Swiftfin#820]
### Describe the bug

Apple TV 4k, Swift fin app there is a delay of 1ms b/w audio and video.
My setup:
OS : macOS 13.4.1 © (22F770820d)
Server : MAC mini Native with M2 chip
CPU : M2
GPU : M2
Memory : 8 Gigs
Version: 10.8.10
Operating System: Darwin
Architecture: X64

- working perfectly on my Mac book Air, Ipad, Ios.
- uninstalled and reinstalled the app (tvOS), same.
- Tried with different format of videos same issue.
- Turned on the native player, In experimental, there is no dealy works perfecty when turned on, but no subtitles 

### Application version

1.0.1 - Released 8 Mar 2023

### Where did you install the app from?

App Store

### Device information

Apple TV 4k 2023

### OS version

tvOS 16.6

### Jellyfin server version

10.8.10

**Comment by Stuke00** [comment]
I am experiencing the same issue.  When not using the native player, there is a significant delay in the audio track, probably more like 1000-2000ms.  Native player does not have subs and does not auto play.

**Comment by LePips** [comment]
As part of #593, there will be an option for audio offset. This will soon be on TestFlight.
