### ISSUE TITLE
Add to playlist and sorting albums

### ISSUE THREAD

**Issue by fabiomorreale** [jellyfin/Swiftfin#824]
Hi there,

I found this app fantastic, definitely the best Jellyfin experience on iOS. I still mostly use Finamp because two features that are missing from Swiftfin:

1. The possibility of adding songs to playlists. This should be a possibility both from the playlist page ("add to this playlist") and from the visualisation of the current song ("add to playlist").
2. The possibility of sorting albums other than using the alphabetic order (release date, add date, random, ...).

Thanks!

**Comment by LePips** [comment]
Swiftfin doesn't support music?
