### ISSUE TITLE
swiftfin homepage can't auto refresh

### ISSUE THREAD

**Issue by Yumega** [jellyfin/Swiftfin#834]
### Describe the bug

swiftfin homepage can't auto refresh, the playback history can't show the right time last time played

### Application version

1.0.0-58

### Where did you install the app from?

App Store

### Device information

iphone 13 mini

### OS version

ios 16

### Jellyfin server version

10.8.10

**Comment by Jurrer** [comment]
I have the same issue. Pull down action does not trigger a refresh.

**Comment by LePips** [comment]
Duplicate #619
