### ISSUE TITLE
401 Error on User Login [+Server Logs]

### ISSUE THREAD

**Issue by SebTNT** [jellyfin/Swiftfin#835]
### Describe the bug

Enter usename, password, login - ERROR.
401. Logs show this:
023-08-30 12:54:08.059 +01:00] [INF] [66] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: "CustomAuthentication" was challenged.

### Application version

1.0.1 (78)

### Where did you install the app from?

App Store

### Device information

iPhone SE 2 & Apple TV 4K

### OS version

ios17 dev beta & iOS 17.4 beta

### Jellyfin server version

Stable Unknown

**Comment by SebTNT** [comment]
Reinstalled server - error still occurs.

Running on Windows Server 2019

**Comment by 24fpsDaVinci** [comment]
same issue

tvos 17.1 beta 
jellyfin version 1.0.1(70)

**Comment by krystofbe** [comment]
Had the same problem, it went away after using https instead of http for the server url

**Comment by SebTNT** [comment]
Found Part of Issue - Windows Server (Fixed after switching to Ubuntu Server VM in Proxmox rather than Windows Server 2019)
