### ISSUE TITLE
Default manual connection to https

### ISSUE THREAD

**Issue by TechBLT** [jellyfin/Swiftfin#843]
I setup a remote client the other day and the url defaults to http. I use a reverse proxy with letsencrypt like users should remotely (unless they use Tailscale or other VPN). I would like to suggest that the default be https:// instead of http:// or there should be an option to choose ssl which would flip from http to https. Changing this in the url is difficult to explain to a remote user.

**Comment by LePips** [comment]
I'm confident in saying that most people use the app on their local network which is mostly `http`, so `http` will remain the default.
