### ISSUE TITLE
Playback progress reporting sends back the start of the video file, even when resuming

### ISSUE THREAD

**Issue by ericswpark** [jellyfin/Swiftfin#844]
### Describe the bug

1. Resume playback of an item with existing progress data
2. Playback will start at the last stopped timestamp
3. However, Swiftfin will report 0:00 to the server, and the server will consequently start counting up from the start.

### Application version

main branch

### Where did you install the app from?

None

### Device information

iPhone 14 Pro Max

### OS version

iOS 16.6

### Jellyfin server version

10.8.10

### Note

To reproduce this with the Xcode build, you will have to disable the `DEBUG` check found here:

https://github.com/jellyfin/Swiftfin/blob/f16f15e631e25e213bcae88ce9e70a9eb4a114fc/Shared/ViewModels/VideoPlayerManager.swift#L170

**Comment by ericswpark** [comment]
Here's a screenshot from the phone immediately after resuming:

![IMG_6079](https://github.com/jellyfin/Swiftfin/assets/13326074/fe4baea1-8ea4-4332-a57c-49e6a91bfb57)

And what's shown on the dashboard:

<img width="317" alt="Screenshot 2023-09-15 at 1 43 18 PM" src="https://github.com/jellyfin/Swiftfin/assets/13326074/cb812866-c549-4c0a-8c61-44eb59e83616">

I've tried logging out `startInfo`:

```
PlaybackStartInfo(aspectRatio: nil, audioStreamIndex: Optional(-1), brightness: nil, canSeek: nil, isMuted: nil, isPaused: nil, item: nil, itemID: Optional("[id redacted]"), liveStreamID: nil, mediaSourceID: Optional("[id redacted]"), nowPlayingQueue: nil, playMethod: nil, playSessionID: nil, playbackStartTimeTicks: Optional(16947997730000000), playlistItemID: nil, positionTicks: Optional(0), repeatMode: nil, sessionID: Optional("[id redacted]"), subtitleStreamIndex: Optional(-1), volumeLevel: nil)
```

So for some reason `positionTicks` is 0, and that gets sent to the server as-is. Maybe some sort of race condition where Swiftfin reports the progress before the video player has fully initialized and jumped to the resume spot?

**Comment by ericswpark** [comment]
Disregard the bug report – I somehow completely missed the part where the `sendProgressReport()` function had the `DEBUG` check as well. I should've put two and two together when no progress reports were sent after the initial one when playback started. Sorry!

**Comment by hacustom** [comment]
Hi @ericswpark , do you mean that this behavior is intentional and it shouldn't be reporting playback progress?

**Comment by ericswpark** [comment]
Hi @hacustom, that is correct. If you are running a debug build (any selfsigned build installed via Xcode I believe) then playback reporting will be disabled unless you toggle the option in the debug settings page. Prior to this issue report the debug settings page was actually inaccessible until this PR added it: https://github.com/jellyfin/Swiftfin/pull/845

**Comment by hacustom** [comment]
I'm not running a debug build, I'm just running whatever version was publicly available in the App Store.  I don't have a debug settings page in my Swiftfin client on AppleTV.  Hm.

**Comment by ericswpark** [comment]
@hacustom in that case playback progress reporting should work, although the current state of the codebase is vastly different to the release version out on the App Store, so it is possible that the version you're using has a bug that I cannot reproduce. (I also don't own an Apple TV :( )

I suggest filing a separate bug so that it can be tracked until the App Store release is updated.
