### ISSUE TITLE
Use fanart instead of thumbs for home view background in tvOS

### ISSUE THREAD

**Issue by LeviSnoot** [jellyfin/Swiftfin#853]
**Describe the feature you'd like**
Currently Swiftfin on tvOS uses the item's thumb image for the top shelfs background. This ends up not looking very good as thumb images are often not very high resolution, and contain logos. This view already places the logo in the bottom left. The thumb image is also already appropriately placed in the shelf item itself, meaning the background image just ends up being a duplicate.

Fanart images are intended for this exact use case. They are high resolution and do not contain logos or text.

**Additional context**
![IMG_2930](https://github.com/jellyfin/Swiftfin/assets/13402525/32536f0d-8848-4505-9a05-d056a5d4c908)

**Comment by brendanperry** [comment]
I'm currently looking into this because it seems like a good small task to tackle for my first attempted contribution. I have a rough solution on my machine right now with this functionality. I'll work on getting things cleaned up and tested more before putting up a PR as I have time over the next few days.

**Comment by deadpetz** [comment]
Hello. It’s almost 2026 and this issue still hasn’t been fixed…is it still scheduled ? This is the main reason I don’t use Swiftfin on Apple TV, but love the rest of the app.

**Comment by JPKribs** [comment]
> Hello. It’s almost 2026 and this issue still hasn’t been fixed…is it still scheduled ? This is the main reason I don’t use Swiftfin on Apple TV, but love the rest of the app.

Resolved and will be included in our next release:

https://github.com/jellyfin/Swiftfin/discussions/1294
