### ISSUE TITLE
Show episode watched status.

### ISSUE THREAD

**Issue by psyciknz** [jellyfin/Swiftfin#854]
**Describe the feature you'd like**
In the regular jellyfin client, watched videos have the blue circle.  In swiftfin on tvOS there is no indication as to a watched video.  And click on just plays.  

Long press dies bring up a context menu to set as played.

**Additional context**

**Comment by LePips** [comment]
Implemented in #593

**Comment by psyciknz** [comment]
Which version were all these features released under that I might see them?

**Comment by LePips** [comment]
In the current `main` but the next release won't come for a bit.
