### ISSUE TITLE
Quicker User switching

### ISSUE THREAD

**Issue by linedpaper** [jellyfin/Swiftfin#855]
Currently to switch to a different user in the app I must go into settings, choose switch user, select my server then select the user.  It would be nice if there was a way to switch users quicker as it happens so frequently for watch status and content ratings with kids of different ages in the house.

**Comment by theg00s3** [comment]
this would definitely be a major QoL improvement, preferably something like the Google TV app with the switcher upon opening the app

**Comment by cmtonkinson** [comment]
Any of you former Plex users? I really like the login splash screen UX for kids. Their user has no passcode, mine does, and then the libraries each user has access to are delineated by content rating. Or are you all thinking just more ergonomic switching once in the app?

**Comment by chelming** [comment]
> Any of you former Plex users? I really like the login splash screen UX for kids. Their user has no passcode, mine does, and then the libraries each user has access to are delineated by content rating. Or are you all thinking just more ergonomic switching once in the app?

That's exactly what I'm looking for.

**Comment by linedpaper** [comment]
That’s exactly what I’d like as well!
________________________________

**Comment by ihatetoregister** [comment]
Something like this would be interesting for Apple TV
https://developer.apple.com/documentation/tvservices/mapping_apple_tv_users_to_app_profiles

**Comment by cmtonkinson** [comment]
@ihatetoregister I saw that while doing homework on this issue. Not saying it isn’t a useful feature for some, but it misses the mark for my use case. A) user switching on tvOS itself isn’t [a lot] easier than current user switching in Jellyfin, and B) it’s the splash screen / startup workflow I (and it sounds like a few others here) are really looking for.

**Comment by iamnikv** [comment]
Since the changes from #1045 do not fix this for tvOS, could at least an option be provided for choosing which user to sign in with on every app startup? I think that would be useful enough for most and similar enough to the Android Jellfin client.

**Comment by AlexKalopsia** [comment]
+1 for quick user switching. 

My use case: me and wife watch separate things and have separate "watched" status on movies and shows. 
We just turn on the TV, start Jellyfin, and wanna select "who's watching now".

We could achieve this - more or less - with EasyPassword, but that has been deprecated for security reasons (https://github.com/jellyfin/jellyfin/pull/9820). Is it really a problem if within your local network you allow login with no password? 

Having to input a password every time seems incredibly overkill to be honest :/

**Comment by lediszep** [comment]
Any updates regarding this? I would also love to have an option on startup for the rest of the family to easily select their profile
