### ISSUE TITLE
Can't set up the same Jellyfin server two times but with a different IP address

### ISSUE THREAD

**Issue by MrBananaPants** [jellyfin/Swiftfin#856]
When I'm on my home network, I use my private IP address to access Jellyfin so I have the fastest possible connection and don't waste bandwidth.

But when I'm on a different network, I use Tailscale to connect to my server. I found out that Swiftfin has a feature to add multiple Jellyfin servers. I thought I could add one server with my private IP address and one with my Tailscale IP address so I can easily switch between them. However, when adding the Tailscale IP address, I get the message "Existing Server, Server [name] already exists, Add new URL?". When I press "Add URL", it replaces the server with my private IP address. So it's not possible to have both my private IP address and my Tailscale address in the servers. Is it possible to add the functionality to add both?

**Comment by LePips** [comment]
This was previously implemented (and is currently on the iOS store), but with the giant refactor the new implementation wasn't complete. I'll have this as a tracker.

**Comment by ShahnurIslam** [comment]
+1 for this feature
