### ISSUE TITLE
[Bug] Unable to connect to server

### ISSUE THREAD

**Issue by 8RATH** [jellyfin/SwiftFin#86]
When I try to connect to my home server I get Error: Try Again.

Tested on the official Jellyfin app, browser, and Infuse, all of which work.

Since my server is set up with a custom domain like this:
http://jellyfin.custom.domain:8096/
I tries directly using the IP address like this:
http://1.1.1.1:8096/
And it works. The IP I used is exactly the same the domain's only A record pointing at.
Weird.

**Comment by acvigue** [comment]
app uses system dns - as long as domain resolves to IP, it’s not the app’s problem. Make sure if your server uses HTTP, you type it in. Defualts to https.

**Comment by 8RATH** [comment]
> app uses system dns - as long as domain resolves to IP, it’s not the app’s problem. Make sure if your server uses HTTP, you type it in. Defualts to https.
> […](#)

But according to my simple http sniffing, the app does nothing when you enter a domain, even it's known resolves to some IPs (for example Google.com).
What I expect it to do is request the server by HTTP and then give me an error(that's what the app does when I try to give it a wrong port/IP which doesn't run jellyfin, but is running some other HTTP based stuff) , instead of not even trying.
![IMG_2968](https://user-images.githubusercontent.com/60999122/123237038-e483ca00-d50f-11eb-9331-819009e65c3c.PNG)
//192.168.10.2 302 redirected to 192.168.10.2:5000 , which isn't running jellyfin but is running some other HTTP server.

![IMG_2969](https://user-images.githubusercontent.com/60999122/123237062-e8afe780-d50f-11eb-8aae-0d84781c5f8b.PNG)
//That's what the app does whatever domain I input. even when it's a domain I'm sure will respond some HTTP packet.

**Comment by acvigue** [comment]
If the app doesn’t work with domains then your device has a problem resolving DNS. The app has no special treatment in place for IP addresses.

**Comment by acvigue** [comment]
Me and many team members using this app all use domains to access the server
