### ISSUE TITLE
HomePod Stereo Pair Audio Sync

### ISSUE THREAD

**Issue by db4c0n** [jellyfin/Swiftfin#860]
### Describe the bug

Two HomePods connected to an AppleTV 4k as a stereo pair, and the audio won’t sync correctly. Have tried the built in settings options for the AppleTV to adjust the audio syncs but it does not seem to work. Can also confirm that this is the only app that has this issue with this setup on our devices.

### Application version

1.0.1(70)

### Where did you install the app from?

App Store

### Device information

AppleTV 4k (A2169) 64GB

### OS version

16.6 (20M73)

### Jellyfin server version

10.8.10

**Comment by jiggyjigsj** [comment]
I also ran into audio sync issues. When i switched from home pod to sound bar, the audio lag disappears. 

> AppleTV OS 17.0
> Jellyfin tvOS 1.0.1
> Server OS Version: 10.8.10

**Comment by LePips** [comment]
Indeed I apologize, there is nothing we can actually do about this.
