### ISSUE TITLE
Auto hide iPhone home bar

### ISSUE THREAD

**Issue by Daryan97** [jellyfin/Swiftfin#862]
**Describe the feature you'd like**
When I play something on Swiftfin app I would like the home bar to hide like other media player applications.

**Additional context**
This home bar is a little distracting and I think many of us would appreciate it to be hidden while we are playing something.
![IMG_7732](https://github.com/jellyfin/Swiftfin/assets/29106122/50cc81dd-6a67-4dd8-b7d8-b6b86bfd7b9f)

**Comment by LePips** [comment]
Duplicate #582.
