### ISSUE TITLE
Swiftfin iOS does not respect aspect ratio metadata

### ISSUE THREAD

**Issue by dathbe** [jellyfin/Swiftfin#866]
### Describe the bug

When a tag is added to a video file to specify an anamorphic aspect ratio, the Jellyfin webplayer and Jellyfin iOS app respect the tag and stretch the video.  Swiftfin does not.  

1. Change the aspect ratio of a video file with ffmpeg:
`ffmpeg -i input.mkv -aspect 221:100 -c copy output.mkv`
This results in a video with characteristics like the following:
`Stream #0:0: Video: hevc (Main 10), yuv420p10le(tv, bt709), 1920x922 [SAR 1:1 DAR 960:461], SAR 52:49 DAR 49920:22589, 23.98 fps, 23.98 tbr, 1k tbn, 23.98 tbc (default)`
The second SAR/DAR information is the tag, telling players to stretch the image slightly.
2. Play the file.
3. Bug occurs

### Application version

1.0.1

### Where did you install the app from?

App Store

### Device information

iPhone 13 mini

### OS version

17

### Jellyfin server version

10.8.10

**Comment by LePips** [comment]
This would be an issue with VLCKit, nothing we can do about it.
