### ISSUE TITLE
Play next episode after a delay

### ISSUE THREAD

**Issue by EternalDeiwos** [jellyfin/Swiftfin#868]
It would be nice to let one episode run into the next after a configurable delay or count down timer. The option to skip the timer would also be necessary.

The goal here would be to not have to explicitly press a button to start the next episode.

**Comment by EternalDeiwos** [comment]
Looks like this might be a bug rather than a lack of a feature #737

**Comment by LePips** [comment]
Autoplay does exist, but only within the Swiftfin player.
