### ISSUE TITLE
Remember language and subtitle selection

### ISSUE THREAD

**Issue by stephenb10** [jellyfin/SwiftFin#87]
After selecting a language or subtitle track, exiting and reopening the video reverts back to the default tracks

**Comment by acvigue** [comment]
this is intended to be added with the "auto select subtitle language" in Settings, but I just haven't had time to work on it

**Comment by PangMo5** [comment]
Do other players usually save that information for each video?

I think it would be good to include subtitle language and voice language that you prefers in Settings.

And it would be good to supports automatic options by get the device language :)

**Comment by stephenb10** [comment]
> Do other players usually save that information for each video?

The web client remembers selections between sessions

**Comment by acvigue** [comment]
> And it would be good to supports automatic options by get the device language :)

not by default no, some people strongly dislike subtitles.
i do agree on having the user set a default language.

**Comment by acvigue** [comment]
added in build 54
