### ISSUE TITLE
Subtitles are cut off the screen when video is zoomed in

### ISSUE THREAD

**Issue by swadeshp** [jellyfin/Swiftfin#870]
### Describe the bug

1. Play a video. 
2. Zoom it to fill the screen

The subtitle will go off the screen instead of staying at the bottom edge.

![IMG_7090](https://github.com/jellyfin/Swiftfin/assets/12512448/b5791092-7362-45d6-9d9c-c09d23ec629b)

![IMG_7091](https://github.com/jellyfin/Swiftfin/assets/12512448/04c48538-efed-4567-8d8b-25d287f35212)

### Application version

1.0.1 (78)

### Where did you install the app from?

App Store

### Device information

iPhone 14 Pro

### OS version

iOS 17.0.2

### Jellyfin server version

10.8.11

**Comment by georgeoshardo** [comment]
@swadeshp not an ideal solution but I found you can switch to the web player in the client settings (at least on Android it is possible) and it does not suffer from this problem.

**Comment by swadeshp** [comment]
@georgeoshardo Unfortunately, no such option on jellyfin/swiftfin app on iOS.

**Comment by mitchins** [comment]
Not until VLCKit hits 4.0, which could be another 4-5 years, but hopefully sooner.
I hit the same issue, seems unfortunate but it is what it is.
