### ISSUE TITLE
10.9.0 Support is Broken

### ISSUE THREAD

**Issue by jet082** [jellyfin/Swiftfin#876]
### Describe the bug

1. Set up a jellyfin server on the latest unstable build
2. Try to connect to it with jellyfin android or iOS - it works
3. Try to connect to it with swiftfin - it doesn't. The error given is "200 - Unknown Error"

This is quite recent. Swiftfin used to work just fine with 10.9.0.

### Application version

1.0.1

### Where did you install the app from?

App Store

### Device information

iPad Pro (latest)

### OS version

iPad OS 17.1

### Jellyfin server version

10.9.0

**Comment by LePips** [comment]
Considering these are `502`s and 10.9.0 is unstable, this is frankly not a client problem.

**Comment by LePips** [comment]
Apologies, I was informed that this could be a serialization issue and I think it ultimately could be since the API did change a lot. I still don't consider this a bug however, just include support for it when we get there.

**Comment by LePips** [comment]
Having thought about this again, I still don't care to have this open since it is about the unstable server and something changed with the API, which would ultimately be a concern of the SDK.

This app only supports the officially released versions.

**Comment by 24fpsDaVinci** [comment]
@jet082 I also have the 200 unknown error issue. Interestingly using MrMc app which stopped all development in 2020 works with Jellyfin Unstable.

**Comment by LePips** [comment]
Nope. I don't support unstable versions of the server, nor will I ever.

**Comment by DaRealHansForSure** [comment]
What the real issue is i don't know, but as a workaround i implemented in `JsonDateTimeConverter` the following line in `Write` Method.
Always write a manually formatted ISO String:
```writer.WriteStringValue(value.ToString("yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffZ", CultureInfo.InvariantCulture));```

**Comment by 24fpsDaVinci** [comment]
fixed in today's unstable build

**Comment by 24fpsDaVinci** [comment]
what build are you running? i'm running [20240116.6-unstable](https://hub.docker.com/layers/jellyfin/jellyfin/20240116.6-unstable/images/sha256-5a8675e77fb2c795d3aecef5447bf12d5de3da5cc51b460a98df9a968524e70d?context=explore) and swiftfin is working for me.

**Comment by thornbill** [comment]
Yes unstable builds are broken atm pending a CI overhaul. There really isn't a reason to continue this discussion here though since Swiftfin will not provide support for unstable builds. 

> I don't "support" unstable versions of the server, nor will I ever.
