### ISSUE TITLE
tvOS does not recognize partially completed videos

### ISSUE THREAD

**Issue by jwrobertson86** [jellyfin/Swiftfin#882]
### Describe the bug

1. Start a video
2. Watch it, say, halfway through
3. Quit watching, go do something else for a while
4. Come back to resume it and the video does not show up in "Continue Watching" and selecting it starts over from 00:00.

I can confirm that the video shows as partially completed on the server and can be resumed from the stopping point on, for example, web. (This also happened previously when projecting from an iPad to the AppleTV, prior to using Swiftfin.)

Logs:
[FFmpeg.DirectStream-2023-10-15_14-56-40_b0c0ba793264fe8c79bd4cc381755f23_9073b217.log](https://github.com/jellyfin/Swiftfin/files/12910513/FFmpeg.DirectStream-2023-10-15_14-56-40_b0c0ba793264fe8c79bd4cc381755f23_9073b217.log)
[log_20231015.log](https://github.com/jellyfin/Swiftfin/files/12910511/log_20231015.log)

### Application version

1.0.1(70)

### Where did you install the app from?

App Store

### Device information

AppleTV A1625 (32 GB)

### OS version

tvOS 17.0 (21j354)

### Jellyfin server version

10.8.10

**Comment by LePips** [comment]
Duplicate #619
