### ISSUE TITLE
Cannot hide the homebar

### ISSUE THREAD

**Issue by SteamWo1f** [jellyfin/Swiftfin#888]
### Describe the bug

When playing a piece of media and not in the native player, the iOS home bar does not automatically hide.

### Application version

1.0.1 (78)

### Where did you install the app from?

App Store

### Device information

iPhone 12

### OS version

17.0.3

### Jellyfin server version

10.8.11

**Comment by LePips** [comment]
Duplicate https://github.com/jellyfin/Swiftfin/issues/582.
