### ISSUE TITLE
Switch player based on media format. Or use native by default but fall back if it can't be played.

### ISSUE THREAD

**Issue by elliots** [jellyfin/Swiftfin#890]
Native player is the only way to play HDR files, but it doesn't work for everything.

We could play those files in native based on the file...
i.e.

```swift
// Use the native player for hdr files only
let item = self.videoPlayerManager.currentViewModel.item
let hdr = item.mediaStreams?.contains(where: {$0.videoRange == "HDR"})
if hdr != nil && hdr! {
    NativeVideoPlayer(manager: self.videoPlayerManager)
} else {
    VideoPlayer(manager: self.videoPlayerManager)
}
```

Or, always try native first, and fall back if it fails?

I know VLC is being replaced by MPV, if that will support HDR this might not be needed.

**Comment by LePips** [comment]
I don't want this functionality, the difference in players are more than just looks. Additionally, I have been finally getting around to playing with MPV so that adds HDR support.
