### ISSUE TITLE
当iphone 竖屏锁定功能打开时 播放视频完成之后无法自动返回到竖屏状态

### ISSUE THREAD

**Issue by li1220** [jellyfin/Swiftfin#902]
### Describe the bug

当iphone 竖屏锁定功能打开时 播放视频完成之后无法自动返回到竖屏状态

When the iPhone vertical screen lock function is turned on, the video cannot automatically return to the vertical screen state after playing is completed

### Application version

1.0.1(78)

### Where did you install the app from?

App Store

### Device information

iPhone12 pro max

### OS version

iso 15.6

### Jellyfin server version

10.8.10

**Comment by LePips** [comment]
Dealt a little bit with #857.
