### ISSUE TITLE
Why is the appstore version not being updated anymore?

### ISSUE THREAD

**Issue by MrBananaPants** [jellyfin/Swiftfin#903]
I know this isn't the right place to ask but why is the appstore version not being updated anymore?
The last update was 7 months ago (version 1.0.1) and there have been hundreds of commits since then.
There's also no testflight version anymore. Am I missing something?

**Comment by ericswpark** [comment]
Over on the dev chat the team said they were working on getting TestFlight builds ready. In the meantime please stay patient, or you can try out the latest changes by compiling and installing the build with Xcode.

**Comment by LePips** [comment]
You can see the Matrix channel for more history. Also:

https://jellyfin.org/docs/general/faq/#when-will-release-x-happen-when-will-feature-x-be-available
