### ISSUE TITLE
Skip chapter based on chapter names

### ISSUE THREAD

**Issue by singersbalm** [jellyfin/Swiftfin#908]
I would suggest a overlay that pops up when a chapter is named "OP" or "ED". If clicked it should jump to the next chapter. In addition it could check also https://github.com/ergoz/jellyfin-intro-skipper/blob/master/docs/api.md
- [ ] Skip based on chapter name
- [ ] Skip based on api

**Comment by LePips** [comment]
I have only briefly mentioned/thought about having an experimental feature to detect "skippable" chapters based on the name but don't intend to implement that. We also don't support plugins.

However, the `Media Segments` idea on the server is finally being looked at which will have first party support for anything like this: https://github.com/jellyfin/jellyfin/pull/10530
