### ISSUE TITLE
Adding a second server results in `Unknown Error`

### ISSUE THREAD

**Issue by Samasaur1** [jellyfin/Swiftfin#909]
### Describe the bug

1. Install the Swiftfin app and connect to a server
2. Click the gear, “Switch User”, add another server
3. Log into that server
4. See the following image
![IMG_0035](https://github.com/jellyfin/Swiftfin/assets/30577766/2343d791-6eb2-48b6-8cea-18b1575cfa44)

I have double-checked that my username and password were correct. Also, I was able to sign in to the second Jellyfin server via the web interface. Furthermore, I tested on two devices connecting to my friend’s server (getting the same issue on both), and my friend got the same issue when trying to connect to my server.

Fortunately, we are both able to use the switch user functionality to switch back to the first server that we added in our respective apps

### Application version

1.0.1 (78)

### Where did you install the app from?

App Store

### Device information

Tested on iPhone 15 Pro, iPhone 14 Pro Max, and 2nd-generation 11-inch iPad Pro

### OS version

iOS 17.1.1; iPadOS 17.1

### Jellyfin server version

10.9.0; 10.8.11

**Comment by Samasaur1** [comment]
I actually just tried removing all servers from the Swiftfin app and then adding the failing server first, which _also_ did not work, so it might not be related to the fact that the servers were added second. However, since I am still able to access the failing server via the web interface, this is still a Swiftfin issue

**Comment by LePips** [comment]
> Jellyfin server version: 10.9.0

Does this only not work on that user with that server? See: #876.

**Comment by Samasaur1** [comment]
> > Jellyfin server version: 10.9.0
> 
> Does this only not work on that user with that server? See: #876.

That definitely explains me connecting to their server — let me check with my friend about exactly what they tried

**Comment by Samasaur1** [comment]
Yep, that was the issue. Thanks!
