### ISSUE TITLE
How can I get tvOS beta?

### ISSUE THREAD

**Issue by milesmcclane** [jellyfin/SwiftFin#92]
Hi there, As the title suggests, I can’t find a link to it. I regularly test apps on iOS, iPadOS and macOS - but this is the first time I will try it on the Apple TV. I may not be going about it in the right direction!

**Comment by stephenb10** [comment]
There is no beta for tvOS just yet, it is still in the works.

**Comment by milesmcclane** [comment]
AH! Ok then, that’s why I cant find it. Looking very much forwards to it arriving. Is there an eta? Meanwhile, I’ll close this issue.

**Comment by stephenb10** [comment]
> Is there an eta?

No ETA currently, as it is still very early stages but i would also like to see something come of it in the coming weeks.

**Comment by acvigue** [comment]
I would say at most two months. I'll say that I'm being much more delicate with what I put in that app.

**Comment by sasagr** [comment]
hi. Any progress, plan for the tvOS?
thanks

**Comment by acvigue** [comment]
no
sent from my iPhone
