### ISSUE TITLE
[ATV] Cannot exit playing session with native player

### ISSUE THREAD

**Issue by ShadowJonathan** [jellyfin/Swiftfin#925]
### Describe the bug

1. Login/setup Swiftfin \w Jellyfin server
2. Go to settings, toggle "player" to "native"
3. Go to any media, play
4. Press "return", see that it doesn't work, except the main-menu long-press return

### Application version

Latest main, eb17300061315ff310749871f5b79032385ba55a

### Where did you install the app from?

None

### Device information

Apple TV HD

### OS version

tvOS 17.1

### Jellyfin server version

10.8.12

**Comment by elliots** [comment]
Adding this to nativeplayer fixes it, but it isn't perfect as when you hit back while the info is displaying, it should just hide it instead of closing the video. 

```swift
override func pressesBegan(_ presses: Set<UIPress>, with event: UIPressesEvent?) {
        super.pressesBegan(presses, with: event)
    
        for press in presses {
            if press.type == .menu {
                self.stop()
                self.dismiss(animated: true, completion: nil)
            }
        }
    }
 ```
 
Anyone know how to fix that?

**Comment by nokeeo** [comment]
We can implement AVPlayerViewControllerDelegate to determine when to dismiss.  #947 fixes this.  PTAL when you all have a chance.
