### ISSUE TITLE
tvOS: Can no longer sign in

### ISSUE THREAD

**Issue by TriVoxel** [jellyfin/Swiftfin#930]
### Describe the bug

I already had a server signed in on a tvOS device. Now, it is signed out. I attempted to sign back in using the server URL, username, and password. This did not work. I tried Quick Connect using another device, it said the Quick Connect code was invalid. Restarted the server, same issue. The webapp still works fine, as does Infuse.

Steps to reproduce:

1. Enter server URL (mine is SSL encrypted using Caddy and a domain)
2. Enter username/password: error
3. Click quick connect: error

Expected behaviour:

Sign in.

### Application version

Stable from App Store (cannot check, not my device)

### Where did you install the app from?

App Store

### Device information

Apple TV HD (2021)

### OS version

latest, stable

### Jellyfin server version

10.8.12

**Comment by s-rog** [comment]
I fixed it by updating tvos.

**Comment by alexe0336** [comment]
> I fixed it by updating tvos.

Did that fix it for you @TriVoxel ?

**Comment by TriVoxel** [comment]
> > I fixed it by updating tvos.
> 
> Did that fix it for you @TriVoxel ?

I'll need to test. Will update when I do.
