### ISSUE TITLE
Please add external display video output support for iPad/iPhone

### ISSUE THREAD

**Issue by upstroke-version** [jellyfin/Swiftfin#932]
**Describe the feature you'd like**
When connecting external display to my iPad while playing video, Swiftfin only mirrors the iPad screen rather than displaying full screen video, thus giving lots of letterbox on external display. It would be great to have proper external display support like VLC, Apple TV, etc, giving proper fullscreen experience for user.

**Additional context**

**Comment by LePips** [comment]
Duplicate #606
