### ISSUE TITLE
KSPlayer. Worth a look?

### ISSUE THREAD

**Issue by elliots** [jellyfin/Swiftfin#938]
I spent a few hours and hacked in https://github.com/kingslay/KSPlayer/ (which uses https://github.com/kingslay/FFmpegKit )

It "worked", in that the video would play. Though without any of the player buttons appearing or the back button working.

I know you've been looking at mpv, and ffmpegkit supports building that apparently. Though I don't know if its used by ksplayer.

Not going to create a PR, as it was super dodgy (and i had to add cocoapods to bring in the dependency), but I could if you wanted to help me while I fix all the issues. I imagine it's not worth the hassle walking me through it, but the offer is there.

**Comment by LePips** [comment]
I have seen that and other "players", but have no interest in them. We'll only be moving to mpv.
