### ISSUE TITLE
BaseItemDto.seriesImageSource is broken

### ISSUE THREAD

**Issue by elliots** [jellyfin/Swiftfin#941]
### Describe the bug

Currently, tv shows dont have a logo or poster or backdrop in CinematicResumeView.

It never finds the image tag because its looking at the tags of the child. I adjusted `getImageTag` to accept a boolean `parent` param like this

```
    private func getImageTag(for type: ImageType, parent: Bool) -> String? {
        switch type {
        case .logo:
            return parent ? parentLogoImageTag : imageTags?[type.rawValue]
        case .backdrop:
            return parent ? parentBackdropImageTags?.first : backdropImageTags?.first
        case .screenshot:
            return screenshotImageTags?.first
        default:
            return imageTags?[type.rawValue]
        }
    }
 ```
    
 which does fix it, but doesn't seem like the smartest way

<img width="1048" alt="image" src="https://github.com/jellyfin/Swiftfin/assets/622455/55590f22-39ee-4591-ae39-6ed3a6cbc72d">

### Application version

main branch

### Where did you install the app from?

None

### Device information

apple tv 4k

### OS version

tvos 17

### Jellyfin server version

10.8.11

**Comment by LePips** [comment]
I've fixed this in the linked PR. All I did was force that series images to be created since they, at least in current usage, are the "parent" images and the items don't have tags for that. It would cause more 404s for the people that have firewalls or whatnot but the actual usage is minimal.
