### ISSUE TITLE
Content blocky on Apple TV

### ISSUE THREAD

**Issue by fishcharlie** [jellyfin/Swiftfin#945]
### Describe the bug

1. When playing a video on Apple TV the picture is extremely blocky (especially with a lot of dark colors)
2. This issue doesn't exist on the iPhone version of Swiftfin or the web

### Application version

1.0.1(70)

### Where did you install the app from?

App Store

### Device information

Apple TV

### OS version

tvOS 17.2 (21K365)

### Jellyfin server version

10.8.13

**Comment by LePips** [comment]
That's VLCKit not doing well with dark colors.
