### ISSUE TITLE
Hide HomeBar on Fullscreen Video

### ISSUE THREAD

**Issue by lsrmg** [jellyfin/Swiftfin#946]
**Describe the feature you'd like**
It would be great if the white „Home Bar“ would be hidden when playing full screen video.

**Additional context**
![Bildschirmfoto 2024-01-08 um 23 03 30](https://github.com/jellyfin/Swiftfin/assets/85181844/ea085bf0-79cf-4bcf-ad27-69eec9a5f5f4)

**Comment by thornbill** [comment]
Duplicate of #582
