### ISSUE TITLE
App stays in landscape after playback stops

### ISSUE THREAD

**Issue by krutburken** [jellyfin/SwiftFin#96]
It should revert to whatever orientation the device is in currently. Either that, or the user should be able to manually control the orientation.

**Comment by acvigue** [comment]
> It should revert to whatever orientation the device is in currently.

will do.

> Either that, or the user should be able to manually control the orientation.
no. most videos are in a landscape aspect ratio and the player will be locked.

**Comment by acvigue** [comment]
implemented.

**Comment by krutburken** [comment]
> no. most videos are in a landscape aspect ratio and the player will be locked.

This was more a suggestion because the casting controls currently move with the orientation of the player, which is quite annoying. I made that as a separate issue though, no worries.

Thanks!
