### ISSUE TITLE
Apple TV Sorting, Filters, etc.

### ISSUE THREAD

**Issue by craigtone** [jellyfin/Swiftfin#968]
The iOS app has great filters and sorting options (genre, alphabet, etc.)  I'd like to have that same functionality in the Apple TV app.

**Comment by FabulousSoldier** [comment]
This has been already requested two years ago here: https://github.com/jellyfin/Swiftfin/issues/333

They said it is planned but still no progress on that as it seems unfortunately....

**Comment by craigtone** [comment]
So you basically have a useless app?
