### ISSUE TITLE
Feature: separate controls for the casting function

### ISSUE THREAD

**Issue by krutburken** [jellyfin/Swiftfin#97]
Currently you have to first start the playback locally to be able to cast. Also becomes quite annoying due to #96

**Comment by acvigue** [comment]
would require reimplementation of the whole app.

**Comment by LePips** [comment]
I don't see this as requiring a reimplementation of the entire app, maybe just how we handle casting/on device playing.
Flow would go something like:
- cast icon next to play button
- check permissions
- if given permissions, search for cast devices on network
- show devices in a list
- select device
- push view player but it is in "Casting" mode, that displays a message saying that media is currently being casted to a device.

**Comment by LePips** [comment]
Closing as part of https://github.com/jellyfin/Swiftfin/issues/271
