### ISSUE TITLE
After exiting a video from potrait mode and going to home, app does not change to landscape when phone is tilted.

### ISSUE THREAD

**Issue by MannanSaood** [jellyfin/Swiftfin#973]
### Describe the bug

Whenever I exit the video playing in portrait mode, go to the home screen, and try to get landscape mode, it does not switch, even with auto-rotating. and the iOS notification bar also gets stuck on portrait mode because of this.

### Application version

1.0.1(78)

### Where did you install the app from?

App Store

### Device information

iPhone SE I

### OS version

iOS 15.8

### Jellyfin server version

10.8.13

**Comment by LePips** [comment]
Duplicate #384
