### ISSUE TITLE
Shows not displaying on Apple TV, can see in web browser

### ISSUE THREAD

**Issue by brotund** [jellyfin/Swiftfin#978]
### Describe the bug

Shows are not showing up via Swiftfin using the media browser on Apple TV 4k. I can navigate to them via search and they will play.

I can use Jellyfin chrome and see them in the episodes tab, but not the shows tab. Apple TV does not allow tab switching.

![Swiftfin_episodes](https://github.com/jellyfin/Swiftfin/assets/145820241/0e3a68fa-5cfa-446c-9197-06c3dd137c6c)
![Swiftfin_shows](https://github.com/jellyfin/Swiftfin/assets/145820241/b00f5bd4-dae9-4c82-a107-858aaf72fbbd)

### Application version

1.0.1 (70)

### Where did you install the app from?

App Store

### Device information

Apple TV 4K A2169

### OS version

tvOS 17.3

### Jellyfin server version

Version: 10.8.13

**Comment by LePips** [comment]
This looks like an issue with your server because it doesn't have a show. If the web doesn't have it listed, then really neither will any client.
