### ISSUE TITLE
Building is broken

### ISSUE THREAD

**Issue by isgallagher** [jellyfin/Swiftfin#983]
### Describe the bug

1. Clone repo
2. Brew install swiftgen (error)
3. Carthage update (error)

### Application version

main

### Where did you install the app from?

None

### Device information

Mac

### OS version

Sonoma

### Jellyfin server version

N/A

**Comment by LePips** [comment]
There is still some work that needs to be done on the iOS build before another update gets published and the Jellyfin team will publish it.

**Comment by isgallagher** [comment]
I’m interested in helping with visionOS changes and looking forward to a new build of the iPhone app as it fixes some annoying issues.
