### ISSUE TITLE
Missing "Add URL" button when trying to add a second server URL

### ISSUE THREAD

**Issue by Declan5233** [jellyfin/Swiftfin#987]
### Describe the bug

My server can be accessed from two different URLs. When I try to add the second URL, the "Existing Server, Server [name] already exists, Add new URL?" screen pops up like it should, but the only thing on the screen is a cancel button. The "Add URL" button is missing so I can't actually add it.

There's also no way to remove a server from the servers list, so the only way to switch between server URLs is to delete/reinstall the app and then add the server again.

### Application version

1.0.1 (70)

### Where did you install the app from?

App Store

### Device information

Apple TV 4K (3rd Generation)

### OS version

tvOS 17.3

### Jellyfin server version

10.8.12

**Comment by wpaix** [comment]
Experiencing the exact same, driving me absolutely nuts and completely hindering me from using the app. :(

**Comment by mjugger** [comment]
Why is this closed? The issue still exists.
